# OMO Ecological Informatics

## Notebook 00: Data Audit

### Objective

This notebook performs an initial audit of the tree inventory datasets from Omo Biosphere Reserve.

The audit aims to:

- verify all datasets
- identify data quality issues
- inspect variables
- identify duplicate species names
- identify missing values
- prepare for construction of the master ecological database

**Author:** Peter Ugege

**Project:** OMO Ecological Informatics

**Version:** 0.1

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Display options
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [2]:
from pathlib import Path

# Find project root automatically
project_root = Path.cwd().parent

raw_tree_path = project_root / "data" / "raw" / "trees"

print(raw_tree_path)

c:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\raw\trees

In [3]:
tree_files = sorted(raw_tree_path.glob("*.csv"))

print(f"{len(tree_files)} files found.\n")

for file in tree_files:
    print(file.name)

9 files found.

buffer_major_river_trees.csv
buffer_stream_trees.csv
buffer_upland_trees.csv
core_major_river_trees.csv
core_stream_trees.csv
core_upland_trees.csv
transition_major_river_trees.csv
transition_stream_trees.csv
transition_upland_trees.csv

In [4]:
tree_data = {}

for file in tree_files:
    tree_data[file.stem] = pd.read_csv(file)

print("Datasets loaded successfully.")

Datasets loaded successfully.

In [5]:
summary = []

for name, df in tree_data.items():

    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1]
    })

summary_df = pd.DataFrame(summary)

summary_df

                        Dataset  Rows  Columns
0      buffer_major_river_trees    26       17
1           buffer_stream_trees    34       17
2           buffer_upland_trees    29       17
3        core_major_river_trees    27       18
4             core_stream_trees    25       17
5             core_upland_trees    25       17
6  transition_major_river_trees    28       17
7       transition_stream_trees    15       17
8       transition_upland_trees    19       17

In [6]:
for name, df in tree_data.items():

    print("="*60)
    print(name)
    print("="*60)

    print(df.columns.tolist())

    print()

============================================================
buffer_major_river_trees
============================================================
['SPECIES', 'BmP1', 'BmP2', 'BmP3', 'BmP4', 'BmP5', 'BmP6', 'BmP7', 'BmP8', 'BmP9', 'BmP10', 'Freq', 'total', 'density', 'Rel.density', 'Rel. frequency', 'RIV']

============================================================
buffer_stream_trees
============================================================
['Species', 'BsP1', 'BsP2', 'BsP3', 'BsP4', 'BsP5', 'BsP6', 'BsP7', 'BsP8', 'BsP9', 'BsP10', 'Frequency', 'Individual', 'density', 'Rel density', 'Rel. Freq.', 'RIV']

============================================================
buffer_upland_trees
============================================================
['SPECIES', 'BuP1', 'BuP2', 'BuP3', 'BuP4', 'BuP5', 'BuP6', 'BuP7', 'BuP8', 'BuP9', 'BuP10', 'Frequency', 'Individual', 'Density', 'Rel. density', 'Rel. Freq.', 'RIV']

============================================================
core_major_river_trees
============================================================
['SPECIES', 'CmP1', 'CmP2', 'CmP3', 'CmP4', 'CmP5', 'CmP6', 'CmP7', 'CmP8', 'CmP9', 'CmP10', 'Freq.', 'Unnamed: 12', 'Abundance', 'density', 'Rel density', 'Rel. Freq.', 'RIV']

============================================================
core_stream_trees
============================================================
['Species', 'CSP1', 'CsP2', 'CsP3', 'CsP4', 'CsP5', 'CsP6', 'CsP7', 'CsP8', 'CsP9', 'CsP10', 'Frequency', 'total', 'density', 'Rel density', 'Rel. Freq.', 'RIV']

============================================================
core_upland_trees
============================================================
['Species', 'CuP1', 'CuP2', 'CuP3', 'CuP4', 'CuP5', 'CuP6', 'CuP7', 'CuP8', 'CuP9', 'CuP10', 'Frequency', 'Individual', 'Density', 'Rel density', 'Rel. Freq.', 'RIV']

============================================================
transition_major_river_trees
============================================================
['SPECIES', 'TmP1', 'TmP2', 'TmP3', 'TmP4', 'TmP5', 'TmP6', 'TmP7', 'TmP8', 'TmP9', 'TmP10', 'Freq.', 'Individuals', 'density', 'Rel.density', 'Rel. Freq.', 'RIV']

============================================================
transition_stream_trees
============================================================
['SPECIES', 'TsP1', 'TsP2', 'TsP3', 'TsP4', 'TsP5', 'TsP5.1', 'TsP7', 'TsP8', 'TsP9', 'TsP 10', 'Frequency', 'Individual', 'density', 'Rel density', 'Rel. Freq.', 'RIV']

============================================================
transition_upland_trees
============================================================
['Species', 'TuP1', 'TuP2', 'TuP3', 'TuP4', 'TuP5', 'TuP6', 'TuP7', 'TuP8', 'TuP9', 'TuP10', 'Frequency', 'Individual', 'Density', 'Rel. density', 'Rel. Freq.', 'RIV']

In [7]:
for name, df in tree_data.items():

    print("="*60)
    print(name)
    print("="*60)

    display(df.head())

    break

============================================================
buffer_major_river_trees
============================================================

,SPECIES,BmP1,BmP2,BmP3,BmP4,BmP5,BmP6,BmP7,BmP8,BmP9,BmP10,Freq,total,density,Rel.density,Rel. frequency,RIV
0,Alstonei boonei,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,2,2,0.0027,1.1560,2.0400,1.5984
1,Blighia sapida,2,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,1.0,5,5,0.0068,2.8901,5.1020,3.9961
2,Bombax buonopozene,Bombax buonopozene,NaN,NaN,2.0,1.0,2.0,1.0,NaN,1.0,NaN,5,7,0.0096,4.0462,5.1020,4.5741
3,Bosqueia angolensis,Bosqueia angolensis,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,NaN,3,4,0.0055,2.3121,3.0612,2.6866
4,Celtis zenkeri,NaN,1,NaN,1.0,1.0,NaN,1.0,2.0,NaN,NaN,4,5,0.0068,2.8901,4.0816,3.4859

In [8]:
# Inspect one complete dataset

tree_data["core_major_river_trees"]

,SPECIES,CmP1,CmP2,CmP3,CmP4,CmP5,CmP6,CmP7,CmP8,CmP9,CmP10,Freq.,Unnamed: 12,Abundance,density,Rel density,Rel. Freq.,RIV
0,Amphimas tetracoides,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,3,NaN,3,0.0048,1.1235,2.4590,1.7913
1,Annonidium manni,2.0,2.0,1.0,NaN,NaN,1.0,NaN,2.0,1.0,NaN,6,NaN,9,0.0144,3.3707,4.9180,4.1444
2,Anthonotha macrophylla,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,3,NaN,5,0.0080,1.8726,2.4590,2.1658
3,Blighia Sapida,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2,NaN,2,0.0320,0.7490,1.6393,1.1942
4,Celtis zenkeri,4.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,3,NaN,6,0.0069,2.2471,2.4590,2.3531
5,Cleistopholis patens,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,5,NaN,5,0.0800,1.8726,4.0983,2.9855
6,Diospyros dendo,3.0,1.0,2.0,5.0,7.0,7.0,5.0,6.0,8.0,8.0,10,NaN,52,0.0832,19.4756,8.1967,13.8360
7,Drypetes species,6.0,6.0,2.0,2.0,4.0,1.0,3.0,5.0,6.0,7.0,10,NaN,42,0.0672,15.7303,8.1967,11.9630
8,Funtumia elastica,NaN,NaN,NaN,2.0,NaN,NaN,3.0,NaN,1.0,1.0,4,NaN,7,0.0112,2.6217,3.2786,2.9502
9,Homalium aylmeri,1.0,2.0,NaN,2.0,NaN,1.0,1.0,1.0,NaN,1.0,7,NaN,9,0.0144,3.3707,5.7377,4.5542
10,irvinga gabonensis,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,5,NaN,5,0.0080,1.8726,4.0983,2.9855
11,Lecaniodiscus cupanioides,1.0,1.0,1.0,NaN,1.0,1.0,2.0,NaN,NaN,2.0,7,NaN,9,0.0144,3.3707,5.7377,4.5542
12,Lonchocarpus cilliata,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,2,NaN,3,0.0048,1.1235,1.6393,1.3814
13,Margaritaria discoidea,NaN,NaN,1.0,1.0,1.0,NaN,3.0,1.0,3.0,NaN,6,NaN,10,0.0160,3.7453,4.9180,4.3316
14,Millettia thoningii,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3,NaN,3,0.0048,1.1235,2.4590,1.7913
15,Monodora tenuifolia,2.0,NaN,2.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,4,NaN,7,0.0112,2.6217,3.2786,2.9502
16,Nesodogornia papaverifera,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,4,NaN,5,0.0080,1.8726,3.2786,2.5756
17,Picralima nitida,NaN,7.0,4.0,2.0,6.0,4.0,1.0,NaN,NaN,2.0,7,NaN,26,0.0416,9.7378,5.7377,7.7377
18,Pycnanthus angolensis,2.0,1.0,NaN,NaN,NaN,NaN,3.0,NaN,1.0,NaN,4,NaN,7,0.0112,2.6217,3.2786,2.9502
19,Ricinodendron heudelotii,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3,NaN,5,0.0080,1.8726,2.4590,2.1658
20,Scotellia coricea,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,3,NaN,3,0.0048,1.1235,2.4590,1.7913
21,Sterculia rhinopetala,NaN,1.0,1.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,6,NaN,8,0.0128,2.9962,4.9180,3.9571
22,Strombosia pustulata,3.0,6.0,4.0,2.0,6.0,1.0,NaN,3.0,NaN,2.0,8,NaN,27,0.0432,10.1123,6.5573,8.3348
23,Trichilia gilgiana,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,3,NaN,3,0.0048,1.1235,2.4590,1.7913
24,Trichilia monadelpha,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,2,NaN,3,0.0048,1.1235,1.6393,1.3814
25,Uapaca heudelotii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,2,NaN,3,0.0048,1.1235,1.6393,1.3814
26,26 species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122,NaN,267,0.4272,100.0000,100.0000,100.0000

In [9]:
tree_data["core_major_river_trees"].tail(10)

,SPECIES,CmP1,CmP2,CmP3,CmP4,CmP5,CmP6,CmP7,CmP8,CmP9,CmP10,Freq.,Unnamed: 12,Abundance,density,Rel density,Rel. Freq.,RIV
17,Picralima nitida,NaN,7.0,4.0,2.0,6.0,4.0,1.0,NaN,NaN,2.0,7,NaN,26,0.0416,9.7378,5.7377,7.7377
18,Pycnanthus angolensis,2.0,1.0,NaN,NaN,NaN,NaN,3.0,NaN,1.0,NaN,4,NaN,7,0.0112,2.6217,3.2786,2.9502
19,Ricinodendron heudelotii,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3,NaN,5,0.0080,1.8726,2.4590,2.1658
20,Scotellia coricea,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,3,NaN,3,0.0048,1.1235,2.4590,1.7913
21,Sterculia rhinopetala,NaN,1.0,1.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,6,NaN,8,0.0128,2.9962,4.9180,3.9571
22,Strombosia pustulata,3.0,6.0,4.0,2.0,6.0,1.0,NaN,3.0,NaN,2.0,8,NaN,27,0.0432,10.1123,6.5573,8.3348
23,Trichilia gilgiana,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,3,NaN,3,0.0048,1.1235,2.4590,1.7913
24,Trichilia monadelpha,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,2,NaN,3,0.0048,1.1235,1.6393,1.3814
25,Uapaca heudelotii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,2,NaN,3,0.0048,1.1235,1.6393,1.3814
26,26 species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122,NaN,267,0.4272,100.0000,100.0000,100.0000

In [10]:
tree_data["core_major_river_trees"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SPECIES      27 non-null     object
 1   CmP1         12 non-null     float64
 2   CmP2         15 non-null     float64
 3   CmP3         12 non-null     float64
 4   CmP4         10 non-null     float64
 5   CmP5         7 non-null      float64
 6   CmP6         13 non-null     float64
 7   CmP7         16 non-null     float64
 8   CmP8         11 non-null     float64
 9   CmP9         13 non-null     float64
 10  CmP10        13 non-null     float64
 11  Freq.        27 non-null     int64
 12  Unnamed: 12  0 non-null      float64
 13  Abundance    27 non-null     int64
 14  density      27 non-null     float64
 15  Rel density  27 non-null     float64
 16  Rel. Freq.   27 non-null     float64
 17  RIV          27 non-null     float64
dtypes: float64(15), int64(2), object(1)
memory usage: 3.9+ KB

In [11]:
tree_data["core_major_river_trees"].isnull().sum()

SPECIES         0
CmP1           15
CmP2           12
CmP3           15
CmP4           17
CmP5           20
CmP6           14
CmP7           11
CmP8           16
CmP9           14
CmP10          14
Freq.           0
Unnamed: 12    27
Abundance       0
density         0
Rel density     0
Rel. Freq.      0
RIV             0
dtype: int64