# Omo Forest Ecological Informatics Project

## Notebook 07A — Structural Data Reconstruction and Validation

### Functional Ecology Module — Part A

**Project:** Omo Forest Ecological Informatics Project  
**Notebook:** 07A  
**Stage:** Structural Data Reconstruction, Taxonomic Reconciliation and Validation  
**Date:** August 2026

---

## Objective

The objective of Notebook 07A is to recover, preserve, taxonomically harmonize,
and quality-control the historical Omo tree structural measurements without
altering the original source values or confusing realized structural attributes
with intrinsic functional traits.

The historical source contains structural summaries at the:

**Species × Management Zone × Habitat**

level for the nine combinations of:

- Core × Major River
- Core × Stream
- Core × Upland
- Buffer × Major River
- Buffer × Stream
- Buffer × Upland
- Transition × Major River
- Transition × Stream
- Transition × Upland

Reported structural variables include:

- Total DBH
- Mean DBH
- Total height
- Mean height
- Basal area
- Basal-area percentage

---

## Scientific Boundary

Notebook 07A is restricted to:

1. faithful reconstruction of the historical structural tables;
2. preservation of original species names and numerical values;
3. reconciliation with the validated Notebook 05 canonical taxonomy;
4. investigation of DBH/girth and measurement units;
5. internal mathematical consistency checks;
6. basal-area validation;
7. identification and documentation of questionable records; and
8. production of validated structural datasets for downstream analyses.

Notebook 07A will **not**:

- acquire external functional traits;
- calculate community-weighted means (CWMs);
- calculate functional-diversity indices;
- treat DBH, observed height or basal area as intrinsic species traits;
- distribute zone-habitat structural summaries artificially among individual plots;
- redesign the taxonomic decisions established in Notebooks 02–05; or
- silently correct historical numerical values.

All suspected errors or inconsistencies will be preserved and explicitly flagged.

---

## Validated Community Foundation

Notebook 07A inherits the validated community foundation from Notebooks 01–06:

- **90 plots**
- **127 canonical woody species**
- **1,750 individuals**
- **3 habitats:** Major River, Stream, Upland
- **3 management zones:** Core, Buffer, Transition
- **3 data-derived plant communities** identified in Notebook 06

The canonical 127-species inventory established in Notebook 05 is authoritative
for taxonomic reconciliation in Notebook 07A.

---

## Reproducibility Requirement

Notebook 07A will be considered complete only when:

**Restart Kernel → Run All**

executes successfully without manual intervention and reproduces all validated
outputs.

## 07A.1 — Project Setup and Paths

This section initializes the Python environment and defines the project paths
used throughout Notebook 07A.

No data transformation or taxonomic modification is performed in this section.

In [1]:
# =============================================================================
# 07A.1 — Project Setup and Paths
# =============================================================================

from pathlib import Path
import sys
import platform

import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Project root
# -----------------------------------------------------------------------------

PROJECT_ROOT = Path.cwd()

# Allow execution either from the project root or from the notebooks directory.
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent


# -----------------------------------------------------------------------------
# Core project directories
# -----------------------------------------------------------------------------

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

OUTPUT_DIR = PROJECT_ROOT / "outputs"
TABLE_DIR = OUTPUT_DIR / "tables"

# Dedicated Notebook 07A output directory
STRUCTURE_DIR = PROCESSED_DIR / "notebook_07a"

STRUCTURE_DIR.mkdir(parents=True, exist_ok=True)


# -----------------------------------------------------------------------------
# Notebook 07A input files
# -----------------------------------------------------------------------------

SPECIES_METADATA_FILE = (
    PROCESSED_DIR / "omo_species_metadata.csv"
)

COMMUNITY_MATRIX_FILE = (
    PROCESSED_DIR / "omo_community_matrix_harmonized.csv"
)

TAXONOMIC_CORRECTIONS_FILE = (
    PROCESSED_DIR / "community_taxonomic_corrections.csv"
)

TAXONOMIC_REVIEW_FILE = (
    PROCESSED_DIR / "community_taxonomic_review.csv"
)

SPECIES_INVENTORY_FILE = (
    PROCESSED_DIR / "community_species_inventory.csv"
)


# Historical structural source document
STRUCTURE_SOURCE_FILE = (
    RAW_DIR
    / "omo_tree_structure.docx"
)


# -----------------------------------------------------------------------------
# Notebook 07A output files
# -----------------------------------------------------------------------------

STRUCTURE_RAW_FILE = (
    STRUCTURE_DIR / "omo_tree_structure_raw.csv"
)

STRUCTURE_HARMONIZED_FILE = (
    STRUCTURE_DIR / "omo_tree_structure_harmonized.csv"
)

STRUCTURE_TAXONOMIC_MATCHING_FILE = (
    STRUCTURE_DIR / "structure_taxonomic_matching.csv"
)

STRUCTURE_QC_REPORT_FILE = (
    STRUCTURE_DIR / "structure_qc_report.csv"
)

STRUCTURE_CONSISTENCY_FILE = (
    STRUCTURE_DIR / "structure_internal_consistency.csv"
)


# -----------------------------------------------------------------------------
# Environment information
# -----------------------------------------------------------------------------

print("=" * 72)
print("OMO FOREST ECOLOGICAL INFORMATICS PROJECT")
print("Notebook 07A — Structural Data Reconstruction and Validation")
print("=" * 72)

print(f"\nPython version : {sys.version.split()[0]}")
print(f"Platform       : {platform.platform()}")
print(f"Pandas version : {pd.__version__}")
print(f"NumPy version  : {np.__version__}")

print("\nProject paths")
print("-" * 72)

print(f"Project root   : {PROJECT_ROOT}")
print(f"Raw data       : {RAW_DIR}")
print(f"Processed data : {PROCESSED_DIR}")
print(f"07A outputs    : {STRUCTURE_DIR}")

========================================================================
OMO FOREST ECOLOGICAL INFORMATICS PROJECT
Notebook 07A — Structural Data Reconstruction and Validation
========================================================================

Python version : 3.10.19
Platform       : Windows-10-10.0.26200-SP0
Pandas version : 2.3.3
NumPy version  : 2.2.6

Project paths
------------------------------------------------------------------------
Project root   : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics
Raw data       : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\raw
Processed data : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed
07A outputs    : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\notebook_07a

In [2]:
# =============================================================================
# 07A.1.1 — Input Path Check
# =============================================================================

input_files = {
    "Species metadata": SPECIES_METADATA_FILE,
    "Community matrix": COMMUNITY_MATRIX_FILE,
    "Taxonomic corrections": TAXONOMIC_CORRECTIONS_FILE,
    "Taxonomic review": TAXONOMIC_REVIEW_FILE,
    "Species inventory": SPECIES_INVENTORY_FILE,
    "Structural source": STRUCTURE_SOURCE_FILE,
}

print("Notebook 07A input-file check")
print("=" * 72)

for label, path in input_files.items():
    status = "FOUND" if path.exists() else "NOT FOUND"
    print(f"{label:<25} : {status}")
    print(f"{'':25}   {path}")

Notebook 07A input-file check
========================================================================
Species metadata          : FOUND
                            C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\omo_species_metadata.csv
Community matrix          : FOUND
                            C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\omo_community_matrix_harmonized.csv
Taxonomic corrections     : FOUND
                            C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\community_taxonomic_corrections.csv
Taxonomic review          : FOUND
                            C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\community_taxonomic_review.csv
Species inventory         : FOUND
                            C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\community_species_inventory.csv
Structural source         : FOUND
                            C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\raw\omo_tree_structure.docx

## 07A.2 — Load and Validate the Canonical Taxonomic Foundation

This section loads the validated taxonomic products inherited from Notebook 05.

The authoritative canonical inventory for Notebook 07A is defined by:

- `omo_species_metadata.csv`
- the species columns of `omo_community_matrix_harmonized.csv`

These two resources must independently contain the same 127 canonical taxa.

The pre-harmonization inventory and taxonomic review files are retained as
supporting audit resources. Notebook 07A does not redesign or rerun the
taxonomic harmonization performed in Notebook 05.

In [3]:
# =============================================================================
# 07A.2 — Load Canonical Taxonomic Resources
# =============================================================================

species_metadata = pd.read_csv(SPECIES_METADATA_FILE)

community_matrix = pd.read_csv(COMMUNITY_MATRIX_FILE)

taxonomic_corrections = pd.read_csv(TAXONOMIC_CORRECTIONS_FILE)

taxonomic_review = pd.read_csv(TAXONOMIC_REVIEW_FILE)

species_inventory = pd.read_csv(SPECIES_INVENTORY_FILE)


print("Taxonomic resources loaded successfully.")
print("=" * 72)

print(f"Species metadata       : {species_metadata.shape}")
print(f"Community matrix       : {community_matrix.shape}")
print(f"Taxonomic corrections  : {taxonomic_corrections.shape}")
print(f"Taxonomic review       : {taxonomic_review.shape}")
print(f"Species inventory      : {species_inventory.shape}")

Taxonomic resources loaded successfully.
========================================================================
Species metadata       : (127, 1)
Community matrix       : (90, 130)
Taxonomic corrections  : (140, 4)
Taxonomic review       : (140, 8)
Species inventory      : (140, 1)

In [4]:
# =============================================================================
# 07A.2.1 — Validate Canonical Species Inventory
# =============================================================================

# Expected metadata columns
required_metadata_columns = {"Species"}

missing_metadata_columns = (
    required_metadata_columns - set(species_metadata.columns)
)

assert not missing_metadata_columns, (
    f"Missing metadata columns: {missing_metadata_columns}"
)


# -------------------------------------------------------------------------
# Extract canonical species lists
# -------------------------------------------------------------------------

canonical_species_metadata = (
    species_metadata["Species"]
    .dropna()
    .astype(str)
    .str.strip()
    .tolist()
)


community_metadata_columns = {
    "Plot_ID",
    "Zone",
    "Habitat",
}

canonical_species_matrix = [
    column
    for column in community_matrix.columns
    if column not in community_metadata_columns
]


# -------------------------------------------------------------------------
# Basic inventory checks
# -------------------------------------------------------------------------

n_metadata_species = len(canonical_species_metadata)

n_unique_metadata_species = len(set(canonical_species_metadata))

n_matrix_species = len(canonical_species_matrix)

n_unique_matrix_species = len(set(canonical_species_matrix))


print("Canonical species validation")
print("=" * 72)

print(
    f"Species in metadata          : {n_metadata_species}"
)

print(
    f"Unique species in metadata   : {n_unique_metadata_species}"
)

print(
    f"Species columns in matrix    : {n_matrix_species}"
)

print(
    f"Unique matrix species        : {n_unique_matrix_species}"
)


# -------------------------------------------------------------------------
# Locked Notebook 05 expectations
# -------------------------------------------------------------------------

assert n_metadata_species == 127, (
    "Canonical metadata does not contain the expected 127 species."
)

assert n_unique_metadata_species == 127, (
    "Duplicate species detected in canonical metadata."
)

assert n_matrix_species == 127, (
    "Community matrix does not contain the expected 127 species columns."
)

assert n_unique_matrix_species == 127, (
    "Duplicate species columns detected in community matrix."
)


print("\nCanonical species counts: PASSED")

Canonical species validation
========================================================================
Species in metadata          : 127
Unique species in metadata   : 127
Species columns in matrix    : 127
Unique matrix species        : 127

Canonical species counts: PASSED

In [5]:
# =============================================================================
# 07A.2.2 — Confirm Metadata–Matrix Taxonomic Synchronization
# =============================================================================

metadata_species_set = set(canonical_species_metadata)

matrix_species_set = set(canonical_species_matrix)


metadata_only = sorted(
    metadata_species_set - matrix_species_set
)

matrix_only = sorted(
    matrix_species_set - metadata_species_set
)


print("Metadata–community matrix synchronization")
print("=" * 72)

print(
    f"Species present only in metadata : {len(metadata_only)}"
)

print(
    f"Species present only in matrix   : {len(matrix_only)}"
)


if metadata_only:
    print("\nMetadata-only taxa:")
    for species in metadata_only:
        print(f"  - {species}")


if matrix_only:
    print("\nMatrix-only taxa:")
    for species in matrix_only:
        print(f"  - {species}")


assert metadata_species_set == matrix_species_set, (
    "Canonical metadata and community matrix species do not match."
)


print("\nCanonical taxonomy synchronization: PASSED")

Metadata–community matrix synchronization
========================================================================
Species present only in metadata : 0
Species present only in matrix   : 0

Canonical taxonomy synchronization: PASSED

In [6]:
# =============================================================================
# 07A.2.3 — Validate Pre-Harmonization Taxonomic Audit Resources
# =============================================================================

assert "Scientific_Name" in species_inventory.columns, (
    "community_species_inventory.csv must contain 'Scientific_Name'."
)

assert "Original_Name" in taxonomic_review.columns, (
    "community_taxonomic_review.csv must contain 'Original_Name'."
)

assert "Original_Name" in taxonomic_corrections.columns, (
    "community_taxonomic_corrections.csv must contain 'Original_Name'."
)


# -------------------------------------------------------------------------
# Extract original taxon names
# -------------------------------------------------------------------------

inventory_taxa = (
    species_inventory["Scientific_Name"]
    .dropna()
    .astype(str)
    .str.strip()
)

review_taxa = (
    taxonomic_review["Original_Name"]
    .dropna()
    .astype(str)
    .str.strip()
)

correction_taxa = (
    taxonomic_corrections["Original_Name"]
    .dropna()
    .astype(str)
    .str.strip()
)


# -------------------------------------------------------------------------
# Basic record-count validation
# -------------------------------------------------------------------------

print("Pre-harmonization audit resources")
print("=" * 72)

print(f"Species inventory records    : {len(inventory_taxa)}")
print(f"Taxonomic review records     : {len(review_taxa)}")
print(f"Taxonomic correction records : {len(correction_taxa)}")


assert len(inventory_taxa) == 140, (
    "Expected 140 taxa in the pre-harmonization species inventory."
)

assert len(review_taxa) == 140, (
    "Expected 140 taxa in the taxonomic review."
)

assert len(correction_taxa) == 140, (
    "Expected 140 taxa in the taxonomic corrections file."
)


# -------------------------------------------------------------------------
# Normalize names FOR COMPARISON ONLY
#
# Important:
# This does not modify any source taxonomic values.
# It only removes formatting differences caused by capitalization or
# repeated whitespace.
# -------------------------------------------------------------------------

def normalize_taxon_name(name):
    return " ".join(str(name).split()).casefold()


inventory_taxa_normalized = {
    normalize_taxon_name(name)
    for name in inventory_taxa
}

review_taxa_normalized = {
    normalize_taxon_name(name)
    for name in review_taxa
}

correction_taxa_normalized = {
    normalize_taxon_name(name)
    for name in correction_taxa
}


# -------------------------------------------------------------------------
# Compare audit resources
# -------------------------------------------------------------------------

inventory_review_diff = sorted(
    inventory_taxa_normalized - review_taxa_normalized
)

review_inventory_diff = sorted(
    review_taxa_normalized - inventory_taxa_normalized
)

inventory_correction_diff = sorted(
    inventory_taxa_normalized - correction_taxa_normalized
)

correction_inventory_diff = sorted(
    correction_taxa_normalized - inventory_taxa_normalized
)


print("\nNormalized taxonomic comparison")
print("-" * 72)

print(
    f"Inventory-only taxa vs review     : "
    f"{len(inventory_review_diff)}"
)

print(
    f"Review-only taxa vs inventory     : "
    f"{len(review_inventory_diff)}"
)

print(
    f"Inventory-only taxa vs corrections: "
    f"{len(inventory_correction_diff)}"
)

print(
    f"Corrections-only taxa vs inventory: "
    f"{len(correction_inventory_diff)}"
)


# -------------------------------------------------------------------------
# Validate normalized equivalence
# -------------------------------------------------------------------------

assert inventory_taxa_normalized == review_taxa_normalized, (
    "Species inventory and taxonomic review still differ after "
    "case/whitespace normalization."
)

assert inventory_taxa_normalized == correction_taxa_normalized, (
    "Species inventory and taxonomic corrections still differ after "
    "case/whitespace normalization."
)

assert review_taxa_normalized == correction_taxa_normalized, (
    "Taxonomic review and corrections resources differ."
)


print("\nPre-harmonization audit layer: PASSED")
print(
    "Note: Original taxon spellings/capitalization remain unchanged; "
    "normalization was used only for validation."
)

Pre-harmonization audit resources
========================================================================
Species inventory records    : 140
Taxonomic review records     : 140
Taxonomic correction records : 140

Normalized taxonomic comparison
------------------------------------------------------------------------
Inventory-only taxa vs review     : 0
Review-only taxa vs inventory     : 0
Inventory-only taxa vs corrections: 0
Corrections-only taxa vs inventory: 0

Pre-harmonization audit layer: PASSED
Note: Original taxon spellings/capitalization remain unchanged; normalization was used only for validation.

In [7]:
# =============================================================================
# 07A.2.4 — Inspect Taxonomic Decision Fields
# =============================================================================

decision_fields = [
    "Accepted_Name",
    "Status",
    "Notes",
]

print("Taxonomic decision-field inspection")
print("=" * 72)

for field in decision_fields:

    if field in taxonomic_corrections.columns:

        populated = (
            taxonomic_corrections[field]
            .notna()
            .sum()
        )

        print(
            f"{field:<20} : {populated} populated records"
        )


review_issue_count = (
    taxonomic_review["Suspected_Issue"]
    .notna()
    .sum()
)

print(
    f"\nRecords with suspected issues in review file: "
    f"{review_issue_count}"
)


print(
    "\nNOTE:"
    "\nThe 127-species metadata and harmonized community matrix "
    "are therefore treated as the authoritative canonical taxonomy."
    "\nThe 140-taxon inventory/review resources are retained as "
    "supporting audit evidence."
)

Taxonomic decision-field inspection
========================================================================
Accepted_Name        : 0 populated records
Status               : 0 populated records
Notes                : 0 populated records

Records with suspected issues in review file: 13

NOTE:
The 127-species metadata and harmonized community matrix are therefore treated as the authoritative canonical taxonomy.
The 140-taxon inventory/review resources are retained as supporting audit evidence.

## 07A.3 — Structural Source Registration and Table Inventory

This section registers the historical Omo structural source and defines the
expected table structure before species-level reconstruction begins.

The source document contains structural summaries for nine combinations of:

**Management Zone × Habitat**

covering:

- Core × Stream
- Core × Major River
- Core × Upland
- Buffer × Major River
- Buffer × Stream
- Buffer × Upland
- Transition × Major River
- Transition × Stream
- Transition × Upland

No taxonomic correction or numerical modification is performed in this section.
The objective is solely to establish source provenance and a reproducible table
registry for downstream reconstruction.

In [8]:
# =============================================================================
# 07A.3 — Structural Source Registration
# =============================================================================

structure_source_registry = pd.DataFrame(
    [
        {
            "Source_Table": "4.1",
            "Source_Title": "Tree girth and height in core stream",
            "Management_Zone": "Core",
            "Habitat": "Stream",
            "Source_Page": 1,
        },
        {
            "Source_Table": "4.2",
            "Source_Title": "Tree girth and height in Core Major Rivers",
            "Management_Zone": "Core",
            "Habitat": "Major River",
            "Source_Page": 2,
        },
        {
            "Source_Table": "4.3",
            "Source_Title": "Tree girth and height in core Upland",
            "Management_Zone": "Core",
            "Habitat": "Upland",
            "Source_Page": 3,
        },
        {
            "Source_Table": "4.4",
            "Source_Title": "Tree girth and height in buffer major rivers",
            "Management_Zone": "Buffer",
            "Habitat": "Major River",
            "Source_Page": 4,
        },
        {
            "Source_Table": "4.5",
            "Source_Title": "Tree girth and height in buffer stream",
            "Management_Zone": "Buffer",
            "Habitat": "Stream",
            "Source_Page": 5,
        },
        {
            "Source_Table": "4.6",
            "Source_Title": "Tree girth and height of buffer upland",
            "Management_Zone": "Buffer",
            "Habitat": "Upland",
            "Source_Page": 6,
        },
        {
            "Source_Table": "4.7",
            "Source_Title": "Tree girth and height in transition major rivers",
            "Management_Zone": "Transition",
            "Habitat": "Major River",
            "Source_Page": 7,
        },
        {
            "Source_Table": "4.8",
            "Source_Title": "Tree girth and height in transition stream",
            "Management_Zone": "Transition",
            "Habitat": "Stream",
            "Source_Page": 8,
        },
        {
            "Source_Table": "4.9",
            "Source_Title": "Tree girth and height in transition upland",
            "Management_Zone": "Transition",
            "Habitat": "Upland",
            "Source_Page": 9,
        },
    ]
)


print("Structural source registry")
print("=" * 72)

display(structure_source_registry)

Structural source registry
========================================================================

,Source_Table,Source_Title,Management_Zone,Habitat,Source_Page
0,4.1,Tree girth and height in core stream,Core,Stream,1
1,4.2,Tree girth and height in Core Major Rivers,Core,Major River,2
2,4.3,Tree girth and height in core Upland,Core,Upland,3
3,4.4,Tree girth and height in buffer major rivers,Buffer,Major River,4
4,4.5,Tree girth and height in buffer stream,Buffer,Stream,5
5,4.6,Tree girth and height of buffer upland,Buffer,Upland,6
6,4.7,Tree girth and height in transition major rivers,Transition,Major River,7
7,4.8,Tree girth and height in transition stream,Transition,Stream,8
8,4.9,Tree girth and height in transition upland,Transition,Upland,9

In [9]:
# =============================================================================
# 07A.3.1 — Validate Structural Table Registry
# =============================================================================

expected_zones = {
    "Core",
    "Buffer",
    "Transition",
}

expected_habitats = {
    "Major River",
    "Stream",
    "Upland",
}


print("Structural source registry validation")
print("=" * 72)

print(
    f"Registered source tables : "
    f"{len(structure_source_registry)}"
)

print(
    f"Management zones         : "
    f"{sorted(structure_source_registry['Management_Zone'].unique())}"
)

print(
    f"Habitats                 : "
    f"{sorted(structure_source_registry['Habitat'].unique())}"
)


# -------------------------------------------------------------------------
# Core validation
# -------------------------------------------------------------------------

assert len(structure_source_registry) == 9, (
    "Expected exactly 9 structural source tables."
)

assert (
    set(structure_source_registry["Management_Zone"])
    == expected_zones
), (
    "Structural registry does not contain the expected management zones."
)

assert (
    set(structure_source_registry["Habitat"])
    == expected_habitats
), (
    "Structural registry does not contain the expected habitats."
)


# -------------------------------------------------------------------------
# Verify all 3 × 3 combinations are present exactly once
# -------------------------------------------------------------------------

expected_combinations = {
    (zone, habitat)
    for zone in expected_zones
    for habitat in expected_habitats
}

observed_combinations = set(
    zip(
        structure_source_registry["Management_Zone"],
        structure_source_registry["Habitat"],
    )
)


assert observed_combinations == expected_combinations, (
    "The 3 × 3 Zone × Habitat structural design is incomplete."
)


duplicate_combinations = (
    structure_source_registry
    .duplicated(
        subset=[
            "Management_Zone",
            "Habitat",
        ],
        keep=False,
    )
)

assert not duplicate_combinations.any(), (
    "Duplicate Zone × Habitat combinations found in structural registry."
)


print("\nNine-table structural design: PASSED")

Structural source registry validation
========================================================================
Registered source tables : 9
Management zones         : ['Buffer', 'Core', 'Transition']
Habitats                 : ['Major River', 'Stream', 'Upland']

Nine-table structural design: PASSED

## 07A.4 — Faithful Structural Data Reconstruction

This section reconstructs the nine historical structural tables into a single
machine-readable dataset.

The reconstruction follows a strict source-preservation rule:

- species names are retained exactly as reported;
- family names are retained exactly as reported;
- numerical values are retained as reported;
- duplicate source records are not removed;
- suspicious values are not corrected;
- taxonomic harmonization is not performed at this stage.

Management zone, habitat, source table and source page are added only as
provenance fields.

The resulting dataset represents the historical source and will be exported as:

`omo_tree_structure_raw.csv`

Any taxonomic reconciliation or structural-quality assessment will be performed
on derived datasets in subsequent sections.

In [10]:
# =============================================================================
# 07A.4.1 — Inspect Structural Source Document
# =============================================================================

from docx import Document


document = Document(STRUCTURE_SOURCE_FILE)


print("Structural source document inspection")
print("=" * 72)

print(f"Source file       : {STRUCTURE_SOURCE_FILE.name}")
print(f"Word tables found : {len(document.tables)}")
print(f"Paragraphs found  : {len(document.paragraphs)}")


# -------------------------------------------------------------------------
# Inspect dimensions of detected tables
# -------------------------------------------------------------------------

table_summary = []

for i, table in enumerate(document.tables, start=1):

    n_rows = len(table.rows)

    n_cols = max(
        len(row.cells)
        for row in table.rows
    )

    table_summary.append(
        {
            "Word_Table": i,
            "Rows": n_rows,
            "Columns": n_cols,
        }
    )


table_summary = pd.DataFrame(table_summary)

display(table_summary)

Structural source document inspection
========================================================================
Source file       : omo_tree_structure.docx
Word tables found : 2
Paragraphs found  : 12

   Word_Table  Rows  Columns
0           1    28        9
1           2   240       10

In [11]:
# =============================================================================
# 07A.4.2 — Inspect Raw Word Table Contents
# =============================================================================

def clean_cell_text(text):
    """
    Clean Word cell text for display only.

    This does NOT modify the source document.
    """
    return " ".join(str(text).split())


print("WORD TABLE 1 — FIRST 15 ROWS")
print("=" * 100)

table_1 = document.tables[0]

for i, row in enumerate(table_1.rows[:15]):
    values = [
        clean_cell_text(cell.text)
        for cell in row.cells
    ]

    print(f"Row {i:03d}: {values}")


print("\n\nWORD TABLE 2 — FIRST 25 ROWS")
print("=" * 100)

table_2 = document.tables[1]

for i, row in enumerate(table_2.rows[:25]):
    values = [
        clean_cell_text(cell.text)
        for cell in row.cells
    ]

    print(f"Row {i:03d}: {values}")

WORD TABLE 1 — FIRST 15 ROWS
====================================================================================================
Row 000: ['4.1 Tree girth and height in core stream', '4.1 Tree girth and height in core stream', '', '', '', '', '', '', '']
Row 001: ['Species', 'Family', 'T dbh', '', 'M dbh', 'T Height', 'M height', 'BA m2', 'BA %']
Row 002: ['Alstonia boonei', 'Apocynaceae', '181.7', '', '36.34', '177.9', '35.58', '1037.6', '2.64']
Row 003: ['Blighia sapida', 'Sapindaceae', '233.8', '', '33.4', '246.4', '35.2', '876.51', '2.23']
Row 004: ['Bombax buonopozene', 'Bombacaceae', '126.1', '', '31.5', '126.2', '31.5', '779.63', '1.98']
Row 005: ['Bosquei angolensis', 'Moraceae', '86.2', '', '28.7', '34.3', '28.1', '647.19', '1.65']
Row 006: ['Celtis zenkeri', 'Ulmaceae', '235.8', '', '29.4', '235', '31', '679.14', '1.73']
Row 007: ['Cleistopholis Patens', 'Annonaceae', '248.5', '', '31', '263.4', '34.9', '755.07', '1.92']
Row 008: ['Dialium guinensis', 'Caesalpiniodeae', '66.2', '', '33.1', '65.2', '32.6', '860.84', '2.19']
Row 009: ['Diospyros dendo', 'Ebenaceae', '653.2', '', '21.5', '649.4', '24.9', '363.2', '0.92']
Row 010: ['Drypetes', 'Euphorbiaceae', '680.2', '', '25.1', '696.8', '25.8', '495.01', '1.26']
Row 011: ['Ficus exasperata', 'Moraceae', '225.6', '', '56.4', '217.6', '54.4', '2499.3', '6.37']
Row 012: ['Grewia pubescens', 'Tiliaceae', '409.5', '', '31.5', '425', '32.6', '779.63', '1.98']
Row 013: ['Homalium alymeri', 'Rubiceae', '312.8', '', '52.1', '30.7', '50.45', '2132.8', '5.44']
Row 014: ['Lecaniodiscus cupanioides', 'Sapindaceae', '48', '', '23.7', '52', '26', '441.33', '1.12']


WORD TABLE 2 — FIRST 25 ROWS
====================================================================================================
Row 000: ['SPECIES', 'FAMILY', 'Total dbh', 'Total dbh', 'Mean dbh', 'Mean dbh', 'Total height', 'Mean Height', 'BA m2', 'BA %']
Row 001: ['Amphimas tetracoides', 'Papilionoideae', '64.2', '', '', '21.4', '66.5', '22.1', '359.8', '2.02']
Row 002: ['Annonidium manni', 'Annonacaceae', '271.6', '', '', '30.2', '267.1', '29.6', '716.6', '4.02']
Row 003: ['Anthonotha macrophylla', 'Caesalpinoideae', '91', '', '', '18.2', '84.5', '16.9', '260.2', '1.46']
Row 004: ['Blighia Sapida', 'Sapindaceae', '40.4', '', '', '20.2', '48.5', '24.25', '320.6', '1.80']
Row 005: ['Celtis zenkeri', 'Ulmaceae', '125', '', '', '25', '105.8', '21.16', '491.0', '2.75']
Row 006: ['Cleistopholis patens', 'Annonaceae', '199', '', '', '39.8', '201.7', '40.34', '1244.', '6.98']
Row 007: ['Diospyros dendo', 'Ebenaceae', '1123.2', '', '', '19.4', '1183.7', '20.4', '295.7', '1.66']
Row 008: ['Drypetes', 'Euphorbiaceae', '595', '', '', '13.8', '95.3', '22.1', '149.6', '0.84']
Row 009: ['Funtumia elastica', 'Apocyanaceae', '170.8', '', '', '24.4', '204.5', '29.2', '467.7', '2.62']
Row 010: ['Homalium aylmeri', 'Samydaceae', '354.5', '', '', '32.2', '383.1', '34.8', '814.6', '4.57']
Row 011: ['irvinga gabonensis', 'Irvingaceae', '118.3', '', '', '23.6', '13.8', '22.7', '437.6', '2.45']
Row 012: ['Lecaniodiscus cupanioides', 'Sapindaceae', '194', '', '', '19.4', '213.4', '21.34', '295.7', '1.66']
Row 013: ['Lonchocarpus ciliata', 'Fabaceae', '190.7', '', '', '23.8', '194', '24.25', '445.0', '2.49']
Row 014: ['Margaritaria discoidea', 'Euphorbiaceae', '294.3', '', '', '26.75', '300.6', '27.3', '562.2', '3.15']
Row 015: ['Millettia thoningii', 'Papilionoideae', '56.4', '', '', '18.8', '53.3', '17.8', '277.7', '1.55']
Row 016: ['Monodora lenuifolia', 'Monimiaceae', '185.8', '', '', '26.5', '185.9', '26.5', '551.7', '3.09']
Row 017: ['Nesodogornia papaverifera', 'Sterculiaceae', '283', '', '', '56.6', '274.4', '54.8', '2517.', '14.13']
Row 018: ['Picralima nitida', 'Apocyanaceae', '539.1', '', '', '20.7', '528.5', '20.3', '336.6', '1.89']
Row 019: ['Pycanthus angolensis', 'Myristiacaceae', '182.5', '', '', '26', '181.1', '25.8', '531.1', '2.98']
Row 020: ['Ricinodendron heudeloti', 'Euphorbiaceae', '324.9', '', '', '64.8', '332.2', '66.5', '3299.', '18.52']
Row 021: ['Scotellia coricea', 'Flacourtiaceae', '82.6', '', '', '27.5', '99.8', '33.2', '594.2', '3.33']
Row 022: ['Sterculia rhinopetala', 'Sterculiaceae', '133', '', '', '16.6', '119.5', '14.9', '216.5', '1.21']
Row 023: ['Strombosia pustulata', 'Olacaceae', '734.8', '', '', '27.2', '723.9', '26.8', '581.3', '3.26']
Row 024: ['Trichilia gilgiana', 'Meliaceae', '33.9', '', '', '16.9', '41', '20.5', '224.4', '1.25']

In [12]:
# =============================================================================
# 07A.4.3 — Locate Historical Table Boundaries
# =============================================================================

search_terms = [
    "4.1",
    "4.2",
    "4.3",
    "4.4",
    "4.5",
    "4.6",
    "4.7",
    "4.8",
    "4.9",
    "core",
    "buffer",
    "transition",
]


print("Potential structural-table boundaries")
print("=" * 100)


for table_number, table in enumerate(document.tables, start=1):

    for row_number, row in enumerate(table.rows):

        values = [
            clean_cell_text(cell.text)
            for cell in row.cells
        ]

        row_text = " | ".join(values).lower()

        if any(term.lower() in row_text for term in search_terms):

            print(
                f"Word Table {table_number}, "
                f"Row {row_number:03d}: "
                f"{values}"
            )

Potential structural-table boundaries
====================================================================================================
Word Table 1, Row 000: ['4.1 Tree girth and height in core stream', '4.1 Tree girth and height in core stream', '', '', '', '', '', '', '']
Word Table 1, Row 005: ['Bosquei angolensis', 'Moraceae', '86.2', '', '28.7', '34.3', '28.1', '647.19', '1.65']
Word Table 1, Row 007: ['Cleistopholis Patens', 'Annonaceae', '248.5', '', '31', '263.4', '34.9', '755.07', '1.92']
Word Table 1, Row 009: ['Diospyros dendo', 'Ebenaceae', '653.2', '', '21.5', '649.4', '24.9', '363.2', '0.92']
Word Table 1, Row 011: ['Ficus exasperata', 'Moraceae', '225.6', '', '56.4', '217.6', '54.4', '2499.3', '6.37']
Word Table 1, Row 015: ['Margaritaria discoidea', 'Euphorbiaceae', '199.2', '', '24.9', '210.8', '26.4', '487.15', '1.24']
Word Table 1, Row 018: ['Pavetta crassipes', 'Rubiaceae', '64', '', '32', '66', '33', '804.57', '2.05']
Word Table 1, Row 019: ['Picralima nitida', 'Apocynaceae', '232.7', '', '46.5', '239.4', '47.8', '1698.9', '4.33']
Word Table 1, Row 023: ['Sterculia rhinopetala', 'Sterculiaceae', '395.3', '', '49.4', '361.7', '45.2', '1917.4', '4.89']
Word Table 1, Row 025: ['Strombosia pustulata', 'Olacaceae', '469.3', '', '42.6', '384.7', '35.2', '1425.9', '3.63']
Word Table 2, Row 001: ['Amphimas tetracoides', 'Papilionoideae', '64.2', '', '', '21.4', '66.5', '22.1', '359.8', '2.02']
Word Table 2, Row 003: ['Anthonotha macrophylla', 'Caesalpinoideae', '91', '', '', '18.2', '84.5', '16.9', '260.2', '1.46']
Word Table 2, Row 004: ['Blighia Sapida', 'Sapindaceae', '40.4', '', '', '20.2', '48.5', '24.25', '320.6', '1.80']
Word Table 2, Row 009: ['Funtumia elastica', 'Apocyanaceae', '170.8', '', '', '24.4', '204.5', '29.2', '467.7', '2.62']
Word Table 2, Row 010: ['Homalium aylmeri', 'Samydaceae', '354.5', '', '', '32.2', '383.1', '34.8', '814.6', '4.57']
Word Table 2, Row 013: ['Lonchocarpus ciliata', 'Fabaceae', '190.7', '', '', '23.8', '194', '24.25', '445.0', '2.49']
Word Table 2, Row 014: ['Margaritaria discoidea', 'Euphorbiaceae', '294.3', '', '', '26.75', '300.6', '27.3', '562.2', '3.15']
Word Table 2, Row 017: ['Nesodogornia papaverifera', 'Sterculiaceae', '283', '', '', '56.6', '274.4', '54.8', '2517.', '14.13']
Word Table 2, Row 020: ['Ricinodendron heudeloti', 'Euphorbiaceae', '324.9', '', '', '64.8', '332.2', '66.5', '3299.', '18.52']
Word Table 2, Row 021: ['Scotellia coricea', 'Flacourtiaceae', '82.6', '', '', '27.5', '99.8', '33.2', '594.2', '3.33']
Word Table 2, Row 022: ['Sterculia rhinopetala', 'Sterculiaceae', '133', '', '', '16.6', '119.5', '14.9', '216.5', '1.21']
Word Table 2, Row 023: ['Strombosia pustulata', 'Olacaceae', '734.8', '', '', '27.2', '723.9', '26.8', '581.3', '3.26']
Word Table 2, Row 024: ['Trichilia gilgiana', 'Meliaceae', '33.9', '', '', '16.9', '41', '20.5', '224.4', '1.25']
Word Table 2, Row 025: ['Trichilia monadelpha', 'Meliaceae', '84.5', '', '', '21', '75.1', '18.7', '346.5', '1.94']
Word Table 2, Row 026: ['Uapaca heudelotii', 'Euphorbiaceae', '130', '', '', '43.3', '164.8', '54.9', '1473.', '8.27']
Word Table 2, Row 030: ['4.3 Tree girth and height in core Upland', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 033: ['Baphia nitida', 'Sapindaceae', '124.7', '', '', '17.8', '135.3', '19.3', '248.9', '2.23']
Word Table 2, Row 035: ['Cola species', 'Sterculiaceae', '40.6', '', '', '13.5', '42.4', '14.1', '143.2', '1.28']
Word Table 2, Row 036: ['Diospyrous dendo', 'Ebenaceae', '1785.', '', '', '20.5', '1874.9', '21.5', '330.2', '2.95']
Word Table 2, Row 037: ['Diospyros mespiliformis', 'Ebenaceae', '76.2', '', '', '24.2', '78.2', '26', '460.1', '4.12']
Word Table 2, Row 038: ['Funtumia elastica', 'Apocyanaceae', '129.8', '', '', '21.6', '134.5', '22.4', '366.5', '3.28']
Word Table 2, Row 039: ['Garcinia kola', 'Guttiferae', '105.6', '', '', '26.4', '109.1', '27.2', '547.6', '4.90']
Word Table 2, Row 041: ['Lecaniodiscus cupaniodes', 'Sapindaceae', '54', '', '', '18', '54.8', '18.2', '254.5', '2.28']
Word Table 2, Row 042: ['Maesobotrya barteri', 'Euphorbiaceae', '11.1', '', '', '11.1', '24.4', '24.4', '96.8', '0.86']
Word Table 2, Row 044: ['Mesobotyra barteri', 'Euphorbiaceae', '202', '', '', '22.4', '210', '23.3', '394.2', '3.53']
Word Table 2, Row 046: ['Nesorgodonia papaverifera', 'Sterculiaceae', '392', '', '', '32.7', '409.7', '34.1', '840.1', '7.52']
Word Table 2, Row 047: ['Pterocarpus osun', 'Papillionoides', '124.5', '', '', '41.5', '128', '42.6', '1353.', '12.12']
Word Table 2, Row 048: ['Pycnantus angolensis', 'Myristiaceae', '88.4', '', '', '22.1', '98.3', '24.5', '383.7', '3.43']
Word Table 2, Row 049: ['Ricinodendron heudeloti', 'Euporbiaceae', '82.6', '', '', '27.5', '85.7', '28.5', '594.2', '5.32']
Word Table 2, Row 056: ['', '', '5254.2', '', '', '', '5480.6', '', '11159', '100']
Word Table 2, Row 059: ['4.4 Tree girth and height in buffer major rivers', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 062: ['Alstonia boonei', 'Apocynaceae', '133.7', '', '', '44.5', '130.8', '43.6', '1555.', '5.43']
Word Table 2, Row 063: ['Blighia sapida', 'sapindaceae', '190.6', '', '', '27.2', '169.7', '24.2', '581.3', '2.03']
Word Table 2, Row 064: ['Bombax buonopozene', 'Bombaceae', '258.5', '', '', '36.9', '239.9', '34.2', '1069.', '3.73']
Word Table 2, Row 065: ['Bosqueia angolensis', 'Moraaceae', '107.4', '', '', '26.8', '118', '29.5', '564.3', '1.97']
Word Table 2, Row 066: ['Celtis zenkeri', 'Ulmaceae', '252.5', '', '', '42', '252.6', '42.1', '1386', '4.84']
Word Table 2, Row 067: ['Cleistopholis patens', 'Annonaceae', '303', '', '', '27.5', '328.9', '29.9', '594.2', '2.07']
Word Table 2, Row 068: ['Diallium guineense', 'Fabaceae', '51.6', '', '', '25.8', '41.9', '24.5', '523', '1.82']
Word Table 2, Row 081: ['Pycnanthus angolensis', 'Myristicaceae', '159.6', '', '', '26.6', '146.1', '24.3', '555.9', '1.94']
Word Table 2, Row 083: ['Sterculia rhinopetala', 'Sterculiaceae', '176', '', '', '29.3', '160.5', '26.7', '674.5', '2.35']
Word Table 2, Row 084: ['Sterculia tragacantha', 'Sterculiaceae', '24.8', '', '', '24.8', '15.8', '15.8', '483.2', '1.68']
Word Table 2, Row 085: ['Strombosia pustulata', 'Olacaceae', '176.2', '', '', '29.3', '156.4', '26', '674.5', '2.35']
Word Table 2, Row 088: ['4.5 Tree girth and height in buffer stream', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 092: ['Alstonia boonei', 'Apocynaceae', '79.7', '', '', '15.9', '71.7', '14.3', '198.6', '0.76']
Word Table 2, Row 099: ['Cleistopholis patens', 'Annnaceae', '406.6', '', '', '31.2', '434.3', '33.4', '764.8', '2.94']
Word Table 2, Row 101: ['Diospyrous melistoformis', 'Ebenaceae', '39.5', '', '', '19.7', '38.7', '19.3', '304.9', '1.17']
Word Table 2, Row 104: ['Funtumia elastica', 'Apocynaceae', '172.3', '', '', '24.6', '169.6', '28.2', '475.4', '1.82']
Word Table 2, Row 105: ['Gmelina arborea', 'Verbenacea', '264.8', '', '', '24', '269.6', '24.5', '452.5', '1.74']
Word Table 2, Row 109: ['Macaranga barteri', 'Euphorbiaeae', '601.9', '', '', '40.1', '595.6', '39.7', '1263', '4.85']
Word Table 2, Row 110: ['Melacantha alnifolia', 'Sapotaceae', '173.8', '', '', '43.4', '179.9', '44.9', '1479', '5.69']
Word Table 2, Row 119: ['Spondia mombin', 'Anacardiaceae', '50.88', '', '', '16.9', '62.6', '20.8', '224.4', '0.86']
Word Table 2, Row 122: ['Strombosia pustulata', 'Olacaceae', '159', '', '', '39.7', '135.7', '33.9', '1238', '4.76']
Word Table 2, Row 123: ['Terminalia superba', 'Combretaceae', '115.5', '', '', '38.5', '119.3', '39.7', '1164', '4.47']
Word Table 2, Row 128: ['4.6 Tree girth and height of buffer upland', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 136: ['Blighia unijigata', 'Sapindaceae', '112.9', '', '', '22.5', '120.7', '24.1', '397.7', '2.06']
Word Table 2, Row 139: ['Diallium guineense', 'Fabaceae', '332', '', '', '47.4', '312.9', '44.7', '1765', '9.16']
Word Table 2, Row 146: ['Holarrhena floribunda', 'Apocyanaceae', '144.7', '', '', '38.2', '223.2', '37.2', '1146', '5.95']
Word Table 2, Row 147: ['Lecaniodiscus cupaniodes', 'Sapindaceae', '96.8', '', '', '32.2', '99.6', '33.2', '814.6', '4.22']
Word Table 2, Row 148: ['Milicia excelsa', 'Moraceae', '27.4', '', '', '13.7', '29.7', '14.8', '147.4', '0.76']
Word Table 2, Row 151: ['Nesodogornia papaverifera', 'Sterculiaceae', '361.1', '', '', '32.8', '354.1', '32.1', '845.3', '4.38']
Word Table 2, Row 153: ['Ricinidendron heudelotii', 'Euphorbiaceae', '101.5', '', '', '33.8', '100.5', '33.5', '897.6', '4.66']
Word Table 2, Row 155: ['Sterculia rhinopetala', 'Sterculiarceae', '75.6', '', '', '12.6', '77.9', '12.9', '124.7', '0.64']
Word Table 2, Row 162: ['4.7 Tree girth and height in transition major rivers', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 166: ['Albizia ferruginea', 'Mimosoideae', '254.1', '', '', '21.1', '251.5', '20.9', '349.8', '0.60']
Word Table 2, Row 173: ['Cola nitida', 'Bombacaceae', '107', '', '', '21.4', '104.4', '20.8', '359.8', '0.61']
Word Table 2, Row 174: ['Corynante pachycercus', 'Rubiaceae', '320.6', '', '', '35.6', '311.8', '34.6', '995.7', '1.71']
Word Table 2, Row 176: ['Elaeis guineensis', 'Palmae', '184.5', '', '', '46.1', '144.6', '36.1', '1669', '2.87']
Word Table 2, Row 178: ['Holarrhena floribunda', 'Apocynaceae', '35.5', '', '', '17.7', '28.6', '14.3', '246.1', '0.42']
Word Table 2, Row 179: ['Lonchocarpus cayensis', 'Fabaceae', '16.5', '', '', '16.5', '14.3', '14.3', '213.9', '0.36']
Word Table 2, Row 184: ['Musanga cecropoides', 'Moraceae', '64.9', '', '', '16.2', '49.9', '12.4', '206.2', '0.35']
Word Table 2, Row 188: ['Ricinodendron heudelotii', 'Euphorbiaceae', '54.6', '', '', '18.2', '67.8', '22.6', '260.2', '0.44']
Word Table 2, Row 189: ['Spondia mombin', 'Anacardiaceae', '103.2', '', '', '34.4', '95.3', '31.7', '929.7', '1.59']
Word Table 2, Row 193: ['Trichilia monadelpha', 'Meliaceae', '104.3', '', '', '30.8', '371.4', '28.5', '745.3', '1.28']
Word Table 2, Row 198: ['4.8 Tree girth and height in transition stream', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 201: ['Albizia zygia', 'leguminoceae', '44', '', '', '22', '41.9', '24.5', '380.2', '3.35']
Word Table 2, Row 203: ['Anthocliesta vogelii', 'Loganiaceae', '1249.7', '', '', '24', '1314.8', '25.2', '452.5', '3.9']
Word Table 2, Row 206: ['Cleistoformis patens', 'Annonaceae', '1134.9', '', '', '23.1', '1185.1', '24.1', '419.2', '3.69']
Word Table 2, Row 209: ['Gmelina arborea', 'Verbenacee', '316.5', '', '', '35.1', '344.3', '38.2', '968.0', '8.53']
Word Table 2, Row 213: ['Terminalia superba', 'Combretaceae', '496', '', '', '45', '490.2', '44.5', '1591.', '14.03']
Word Table 2, Row 214: ['Theobroma cacao', 'Malvaceae', '50.8', '', '', '16.9', '40.5', '13.5', '224.4', '1.97']
Word Table 2, Row 219: ['4.9 Tree girth and height in transition upland', '', '', '', '', '', '', '', '', '']
Word Table 2, Row 221: ['Artocarpus communis', 'Moraceae', '154.4', '', '', '22', '158.2', '22.6', '380.2', '4.72']
Word Table 2, Row 222: ['Bambusa vulgaris', 'Poaceae', '12.6', '', '', '12.6', '17.8', '17.8', '124.7', '1.55']
Word Table 2, Row 224: ['Carica papaya', 'Caricaceae', '44.3', '', '', '14.7', '54.1', '18', '169.7', '2.11']
Word Table 2, Row 226: ['Chrysophyllum albidum', 'Sapotaceae', '12.1', '', '', '12.1', '14.7', '14.7', '115.0', '1.43']
Word Table 2, Row 227: ['Citrus sinenses', 'Rutaceae', '24.5', '', '', '24.5', '22.2', '22.2', '471.6', '5.86']
Word Table 2, Row 228: ['Cola nitida', 'Bombacaceae', '84.9', '', '', '16.9', '89.9', '17.9', '224.4', '2.79']
Word Table 2, Row 230: ['Elaeis guineensis', 'Palmae', '869.1', '', '', '34.7', '855.9', '34.2', '946.0', '116']
Word Table 2, Row 234: ['Raulvolfia vomitoria', 'Apocynaceae', '34.3', '', '', '11.4', '41.9', '13.9', '102.1', '1.26']
Word Table 2, Row 235: ['Ricinodendron heudeloti', 'Euphorbiaceae', '104.8', '', '', '26.2', '115.8', '28.9', '539.3', '6.70']
Word Table 2, Row 237: ['Trema orientalis', 'Ulmaceae', '64.7', '', '', '21.5', '71.6', '23.8', '363.2', '4.51']
Word Table 2, Row 239: ['', '', '2489.6', '', '', '', '2574.3', '', '8040.9', '100']

In [13]:
# =============================================================================
# 07A.4.4 — Define Historical Structural Source Blocks
# =============================================================================

structural_blocks = [
    {
        "Source_Table": "4.1",
        "Word_Table": 1,
        "Start_Row": 2,
        "End_Row": 26,
        "Management_Zone": "Core",
        "Habitat": "Stream",
        "Source_Page": 1,
    },
    {
        "Source_Table": "4.2",
        "Word_Table": 2,
        "Start_Row": 1,
        "End_Row": 26,
        "Management_Zone": "Core",
        "Habitat": "Major River",
        "Source_Page": 2,
    },
    {
        "Source_Table": "4.3",
        "Word_Table": 2,
        "Start_Row": 32,
        "End_Row": 55,
        "Management_Zone": "Core",
        "Habitat": "Upland",
        "Source_Page": 3,
    },
    {
        "Source_Table": "4.4",
        "Word_Table": 2,
        "Start_Row": 62,
        "End_Row": 86,
        "Management_Zone": "Buffer",
        "Habitat": "Major River",
        "Source_Page": 4,
    },
    {
        "Source_Table": "4.5",
        "Word_Table": 2,
        "Start_Row": 91,
        "End_Row": 124,
        "Management_Zone": "Buffer",
        "Habitat": "Stream",
        "Source_Page": 5,
    },
    {
        "Source_Table": "4.6",
        "Word_Table": 2,
        "Start_Row": 132,
        "End_Row": 159,
        "Management_Zone": "Buffer",
        "Habitat": "Upland",
        "Source_Page": 6,
    },
    {
        "Source_Table": "4.7",
        "Word_Table": 2,
        "Start_Row": 166,
        "End_Row": 194,
        "Management_Zone": "Transition",
        "Habitat": "Major River",
        "Source_Page": 7,
    },
    {
        "Source_Table": "4.8",
        "Word_Table": 2,
        "Start_Row": 201,
        "End_Row": 214,
        "Management_Zone": "Transition",
        "Habitat": "Stream",
        "Source_Page": 8,
    },
    {
        "Source_Table": "4.9",
        "Word_Table": 2,
        "Start_Row": 221,
        "End_Row": 238,
        "Management_Zone": "Transition",
        "Habitat": "Upland",
        "Source_Page": 9,
    },
]

structural_blocks = pd.DataFrame(structural_blocks)

display(structural_blocks)

,Source_Table,Word_Table,Start_Row,End_Row,Management_Zone,Habitat,Source_Page
0,4.1,1,2,26,Core,Stream,1
1,4.2,2,1,26,Core,Major River,2
2,4.3,2,32,55,Core,Upland,3
3,4.4,2,62,86,Buffer,Major River,4
4,4.5,2,91,124,Buffer,Stream,5
5,4.6,2,132,159,Buffer,Upland,6
6,4.7,2,166,194,Transition,Major River,7
7,4.8,2,201,214,Transition,Stream,8
8,4.9,2,221,238,Transition,Upland,9

In [14]:
# =============================================================================
# 07A.4.5 — Validate Structural Block Definitions
# =============================================================================

# Corrected historical structural source blocks
# Note:
# Table 4.5 ends at row 123.
# Row 124 is the table-total row and must not be treated as a species record.

structural_blocks = pd.DataFrame(
    [
        {
            "Source_Table": "4.1",
            "Word_Table": 1,
            "Start_Row": 2,
            "End_Row": 26,
            "Management_Zone": "Core",
            "Habitat": "Stream",
            "Source_Page": 1,
        },
        {
            "Source_Table": "4.2",
            "Word_Table": 2,
            "Start_Row": 1,
            "End_Row": 26,
            "Management_Zone": "Core",
            "Habitat": "Major River",
            "Source_Page": 2,
        },
        {
            "Source_Table": "4.3",
            "Word_Table": 2,
            "Start_Row": 32,
            "End_Row": 55,
            "Management_Zone": "Core",
            "Habitat": "Upland",
            "Source_Page": 3,
        },
        {
            "Source_Table": "4.4",
            "Word_Table": 2,
            "Start_Row": 62,
            "End_Row": 86,
            "Management_Zone": "Buffer",
            "Habitat": "Major River",
            "Source_Page": 4,
        },
        {
            "Source_Table": "4.5",
            "Word_Table": 2,
            "Start_Row": 91,
            "End_Row": 123,
            "Management_Zone": "Buffer",
            "Habitat": "Stream",
            "Source_Page": 5,
        },
        {
            "Source_Table": "4.6",
            "Word_Table": 2,
            "Start_Row": 132,
            "End_Row": 159,
            "Management_Zone": "Buffer",
            "Habitat": "Upland",
            "Source_Page": 6,
        },
        {
            "Source_Table": "4.7",
            "Word_Table": 2,
            "Start_Row": 166,
            "End_Row": 194,
            "Management_Zone": "Transition",
            "Habitat": "Major River",
            "Source_Page": 7,
        },
        {
            "Source_Table": "4.8",
            "Word_Table": 2,
            "Start_Row": 201,
            "End_Row": 214,
            "Management_Zone": "Transition",
            "Habitat": "Stream",
            "Source_Page": 8,
        },
        {
            "Source_Table": "4.9",
            "Word_Table": 2,
            "Start_Row": 221,
            "End_Row": 238,
            "Management_Zone": "Transition",
            "Habitat": "Upland",
            "Source_Page": 9,
        },
    ]
)


# -----------------------------------------------------------------------------
# Calculate expected species-record counts
# -----------------------------------------------------------------------------

structural_blocks["Expected_Records"] = (
    structural_blocks["End_Row"]
    - structural_blocks["Start_Row"]
    + 1
)


print("Historical structural block validation")
print("=" * 72)

display(
    structural_blocks[
        [
            "Source_Table",
            "Word_Table",
            "Start_Row",
            "End_Row",
            "Management_Zone",
            "Habitat",
            "Source_Page",
            "Expected_Records",
        ]
    ]
)


# -----------------------------------------------------------------------------
# Basic block validation
# -----------------------------------------------------------------------------

print(
    "\nExpected total structural records:",
    structural_blocks["Expected_Records"].sum(),
)


assert len(structural_blocks) == 9, (
    "Exactly nine structural source blocks are required."
)

assert structural_blocks["Expected_Records"].gt(0).all(), (
    "At least one structural block has an invalid row range."
)

assert structural_blocks["Source_Table"].is_unique, (
    "Duplicate Source_Table identifiers detected."
)


# -----------------------------------------------------------------------------
# Validate expected Management Zone × Habitat design
# -----------------------------------------------------------------------------

expected_zones = {
    "Core",
    "Buffer",
    "Transition",
}

expected_habitats = {
    "Major River",
    "Stream",
    "Upland",
}

expected_combinations = {
    (zone, habitat)
    for zone in expected_zones
    for habitat in expected_habitats
}

observed_combinations = set(
    zip(
        structural_blocks["Management_Zone"],
        structural_blocks["Habitat"],
    )
)


assert observed_combinations == expected_combinations, (
    "The expected 3 × 3 Management Zone × Habitat design is incomplete."
)


# -----------------------------------------------------------------------------
# Locked expected record count
# -----------------------------------------------------------------------------

EXPECTED_STRUCTURAL_RECORDS = 222

assert structural_blocks["Expected_Records"].sum() == EXPECTED_STRUCTURAL_RECORDS, (
    "Structural block definitions do not produce the expected "
    "222 species-level records."
)


print("\nStructural block definitions: PASSED")
print(
    f"Validated species-level structural records: "
    f"{EXPECTED_STRUCTURAL_RECORDS}"
)

Historical structural block validation
========================================================================

,Source_Table,Word_Table,Start_Row,End_Row,Management_Zone,Habitat,Source_Page,Expected_Records
0,4.1,1,2,26,Core,Stream,1,25
1,4.2,2,1,26,Core,Major River,2,26
2,4.3,2,32,55,Core,Upland,3,24
3,4.4,2,62,86,Buffer,Major River,4,25
4,4.5,2,91,123,Buffer,Stream,5,33
5,4.6,2,132,159,Buffer,Upland,6,28
6,4.7,2,166,194,Transition,Major River,7,29
7,4.8,2,201,214,Transition,Stream,8,14
8,4.9,2,221,238,Transition,Upland,9,18

Expected total structural records: 222

Structural block definitions: PASSED
Validated species-level structural records: 222

In [15]:
# =============================================================================
# 07A.4.6 — Faithful Extraction of Structural Records
# =============================================================================

raw_records = []


for _, block in structural_blocks.iterrows():

    word_table_number = int(block["Word_Table"])

    # Python indexing is zero-based.
    table = document.tables[word_table_number - 1]

    for source_row in range(
        int(block["Start_Row"]),
        int(block["End_Row"]) + 1,
    ):

        row = table.rows[source_row]

        # Preserve Word cell contents with only outer whitespace removed.
        values = [
            cell.text.strip()
            for cell in row.cells
        ]


        # -----------------------------------------------------------------
        # Table 4.1 uses the 9-column Word layout.
        # -----------------------------------------------------------------

        if word_table_number == 1:

            source_species = values[0]
            source_family = values[1]
            total_dbh = values[2]
            mean_dbh = values[4]
            total_height = values[5]
            mean_height = values[6]
            basal_area = values[7]
            ba_percent = values[8]


        # -----------------------------------------------------------------
        # Tables 4.2–4.9 use the 10-column Word layout.
        # -----------------------------------------------------------------

        else:

            source_species = values[0]
            source_family = values[1]
            total_dbh = values[2]
            mean_dbh = values[5]
            total_height = values[6]
            mean_height = values[7]
            basal_area = values[8]
            ba_percent = values[9]


        raw_records.append(
            {
                "Source_Species": source_species,
                "Source_Family": source_family,
                "Management_Zone": block["Management_Zone"],
                "Habitat": block["Habitat"],
                "Total_DBH": total_dbh,
                "Mean_DBH": mean_dbh,
                "Total_Height": total_height,
                "Mean_Height": mean_height,
                "Basal_Area": basal_area,
                "BA_Percent": ba_percent,
                "Source_Table": block["Source_Table"],
                "Source_Page": int(block["Source_Page"]),
                "Source_Row": source_row,
                "QC_Flag": "",
            }
        )


structure_raw = pd.DataFrame(raw_records)


# -------------------------------------------------------------------------
# Stable record identifier
# -------------------------------------------------------------------------

structure_raw.insert(
    0,
    "Raw_Record_ID",
    [
        f"OMO_STR_{i:04d}"
        for i in range(1, len(structure_raw) + 1)
    ],
)


print("Historical structural reconstruction")
print("=" * 72)

print(f"Records extracted : {len(structure_raw)}")
print(
    f"Source tables     : "
    f"{structure_raw['Source_Table'].nunique()}"
)

print(
    f"Source taxa       : "
    f"{structure_raw['Source_Species'].nunique()}"
)

display(structure_raw.head(10))

Historical structural reconstruction
========================================================================
Records extracted : 222
Source tables     : 9
Source taxa       : 137

,Raw_Record_ID,Source_Species,Source_Family,Management_Zone,Habitat,Total_DBH,Mean_DBH,Total_Height,Mean_Height,Basal_Area,BA_Percent,Source_Table,Source_Page,Source_Row,QC_Flag
0,OMO_STR_0001,Alstonia boonei,Apocynaceae,Core,Stream,181.7,36.34,177.9,35.58,1037.6,2.64,4.1,1,2,
1,OMO_STR_0002,Blighia sapida,Sapindaceae,Core,Stream,233.8,33.4,246.4,35.2,876.51,2.23,4.1,1,3,
2,OMO_STR_0003,Bombax buonopozene,Bombacaceae,Core,Stream,126.1,31.5,126.2,31.5,779.63,1.98,4.1,1,4,
3,OMO_STR_0004,Bosquei angolensis,Moraceae,Core,Stream,86.2,28.7,34.3,28.1,647.19,1.65,4.1,1,5,
4,OMO_STR_0005,Celtis zenkeri,Ulmaceae,Core,Stream,235.8,29.4,235,31,679.14,1.73,4.1,1,6,
5,OMO_STR_0006,Cleistopholis Patens,Annonaceae,Core,Stream,248.5,31,263.4,34.9,755.07,1.92,4.1,1,7,
6,OMO_STR_0007,Dialium guinensis,Caesalpiniodeae,Core,Stream,66.2,33.1,65.2,32.6,860.84,2.19,4.1,1,8,
7,OMO_STR_0008,Diospyros dendo,Ebenaceae,Core,Stream,653.2,21.5,649.4,24.9,363.2,0.92,4.1,1,9,
8,OMO_STR_0009,Drypetes,Euphorbiaceae,Core,Stream,680.2,25.1,696.8,25.8,495.01,1.26,4.1,1,10,
9,OMO_STR_0010,Ficus exasperata,Moraceae,Core,Stream,225.6,56.4,217.6,54.4,2499.3,6.37,4.1,1,11,

In [16]:
# =============================================================================
# 07A.4.7 — Initial Reconstruction Integrity Check
# =============================================================================

print("Raw reconstruction integrity check")
print("=" * 72)


# -------------------------------------------------------------------------
# Record count
# -------------------------------------------------------------------------

expected_records = int(
    structural_blocks["Expected_Records"].sum()
)

print(f"Expected records : {expected_records}")
print(f"Extracted records: {len(structure_raw)}")


assert len(structure_raw) == expected_records, (
    "Extracted record count does not match structural block definitions."
)


# -------------------------------------------------------------------------
# Source-table counts
# -------------------------------------------------------------------------

table_counts = (
    structure_raw
    .groupby(
        [
            "Source_Table",
            "Management_Zone",
            "Habitat",
        ],
        as_index=False,
    )
    .size()
    .rename(columns={"size": "Records"})
)

display(table_counts)


assert structure_raw["Source_Table"].nunique() == 9, (
    "Raw reconstruction does not contain all nine source tables."
)


# -------------------------------------------------------------------------
# Essential source fields
# -------------------------------------------------------------------------

essential_fields = [
    "Source_Species",
    "Source_Family",
    "Total_DBH",
    "Mean_DBH",
    "Total_Height",
    "Mean_Height",
    "Basal_Area",
    "BA_Percent",
]

empty_counts = {}

for field in essential_fields:

    empty_counts[field] = (
        structure_raw[field]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )


print("\nEmpty source fields")
print("-" * 72)

for field, count in empty_counts.items():
    print(f"{field:<20}: {count}")


print("\nInitial raw reconstruction: PASSED")

Raw reconstruction integrity check
========================================================================
Expected records : 222
Extracted records: 222

  Source_Table Management_Zone      Habitat  Records
0          4.1            Core       Stream       25
1          4.2            Core  Major River       26
2          4.3            Core       Upland       24
3          4.4          Buffer  Major River       25
4          4.5          Buffer       Stream       33
5          4.6          Buffer       Upland       28
6          4.7      Transition  Major River       29
7          4.8      Transition       Stream       14
8          4.9      Transition       Upland       18

Empty source fields
------------------------------------------------------------------------
Source_Species      : 0
Source_Family       : 0
Total_DBH           : 0
Mean_DBH            : 0
Total_Height        : 0
Mean_Height         : 0
Basal_Area          : 0
BA_Percent          : 0

Initial raw reconstruction: PASSED

## 07A.4.8 — Final Raw Reconstruction Validation and Export

This section performs the final integrity checks on the faithful historical
reconstruction before export.

The raw reconstruction must:

- contain exactly 222 species-level records;
- contain all nine source tables;
- contain no blank essential source fields;
- preserve duplicate historical records;
- preserve original species and family spellings;
- preserve historical numerical representations;
- contain unique stable record identifiers; and
- exclude table-total and separator rows.

No taxonomic harmonization or numerical correction is performed here.

The validated reconstruction is exported as:

`omo_tree_structure_raw.csv`

In [17]:
# =============================================================================
# 07A.4.8 — Final Raw Reconstruction Validation
# =============================================================================

print("Final raw reconstruction validation")
print("=" * 72)


# -----------------------------------------------------------------------------
# 1. Record-count validation
# -----------------------------------------------------------------------------

assert len(structure_raw) == EXPECTED_STRUCTURAL_RECORDS, (
    f"Expected {EXPECTED_STRUCTURAL_RECORDS} structural records, "
    f"found {len(structure_raw)}."
)

print(f"Structural records       : {len(structure_raw)}")


# -----------------------------------------------------------------------------
# 2. Source-table validation
# -----------------------------------------------------------------------------

n_source_tables = structure_raw["Source_Table"].nunique()

assert n_source_tables == 9, (
    "Expected exactly nine historical source tables."
)

print(f"Source tables            : {n_source_tables}")


# -----------------------------------------------------------------------------
# 3. Stable record-ID validation
# -----------------------------------------------------------------------------

assert structure_raw["Raw_Record_ID"].notna().all(), (
    "Missing Raw_Record_ID values detected."
)

assert structure_raw["Raw_Record_ID"].is_unique, (
    "Raw_Record_ID values are not unique."
)

print(
    f"Unique record IDs        : "
    f"{structure_raw['Raw_Record_ID'].nunique()}"
)


# -----------------------------------------------------------------------------
# 4. Essential-field validation
# -----------------------------------------------------------------------------

essential_fields = [
    "Source_Species",
    "Source_Family",
    "Management_Zone",
    "Habitat",
    "Total_DBH",
    "Mean_DBH",
    "Total_Height",
    "Mean_Height",
    "Basal_Area",
    "BA_Percent",
    "Source_Table",
    "Source_Page",
    "Source_Row",
]

empty_field_counts = {}

for field in essential_fields:

    empty_count = (
        structure_raw[field]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    empty_field_counts[field] = empty_count


print("\nEmpty essential fields")
print("-" * 72)

for field, count in empty_field_counts.items():
    print(f"{field:<20}: {count}")


assert all(
    count == 0
    for count in empty_field_counts.values()
), (
    "Blank essential source fields remain in the raw reconstruction."
)


# -----------------------------------------------------------------------------
# 5. Validate Management Zone × Habitat coverage
# -----------------------------------------------------------------------------

observed_combinations = set(
    zip(
        structure_raw["Management_Zone"],
        structure_raw["Habitat"],
    )
)

expected_combinations = {
    (zone, habitat)
    for zone in {
        "Core",
        "Buffer",
        "Transition",
    }
    for habitat in {
        "Major River",
        "Stream",
        "Upland",
    }
}


assert observed_combinations == expected_combinations, (
    "The raw reconstruction does not contain all nine "
    "Management Zone × Habitat combinations."
)

print("\nManagement Zone × Habitat coverage: PASSED")


# -----------------------------------------------------------------------------
# 6. Identify duplicate historical source records
#
# Important:
# Duplicates are identified but NOT removed.
# -----------------------------------------------------------------------------

duplicate_source_mask = structure_raw.duplicated(
    subset=[
        "Source_Species",
        "Management_Zone",
        "Habitat",
    ],
    keep=False,
)

duplicate_source_records = (
    structure_raw
    .loc[duplicate_source_mask]
    .copy()
)


# Calculate duplicate-group count separately.
# This avoids placing a multiline groupby expression inside an f-string.

if len(duplicate_source_records) > 0:

    duplicate_group_count = (
        duplicate_source_records
        .groupby(
            [
                "Source_Species",
                "Management_Zone",
                "Habitat",
            ]
        )
        .ngroups
    )

else:

    duplicate_group_count = 0


print("\nHistorical duplicate-source check")
print("-" * 72)

print(
    f"Records participating in duplicates : "
    f"{len(duplicate_source_records)}"
)

print(
    f"Duplicate taxon-context groups       : "
    f"{duplicate_group_count}"
)


if len(duplicate_source_records) > 0:

    display(
        duplicate_source_records[
            [
                "Raw_Record_ID",
                "Source_Species",
                "Management_Zone",
                "Habitat",
                "Total_DBH",
                "Mean_DBH",
                "Total_Height",
                "Mean_Height",
                "Basal_Area",
                "BA_Percent",
                "Source_Table",
                "Source_Row",
            ]
        ].sort_values(
            [
                "Management_Zone",
                "Habitat",
                "Source_Species",
            ]
        )
    )


# -----------------------------------------------------------------------------
# 7. Verify no table-total or separator rows remain
# -----------------------------------------------------------------------------

blank_species_rows = (
    structure_raw["Source_Species"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

assert blank_species_rows == 0, (
    "Possible total/separator rows remain in the reconstruction."
)


# -----------------------------------------------------------------------------
# 8. Validate source-table record counts
# -----------------------------------------------------------------------------

observed_table_counts = (
    structure_raw
    .groupby("Source_Table")
    .size()
    .to_dict()
)

expected_table_counts = {
    "4.1": 25,
    "4.2": 26,
    "4.3": 24,
    "4.4": 25,
    "4.5": 33,
    "4.6": 28,
    "4.7": 29,
    "4.8": 14,
    "4.9": 18,
}

assert observed_table_counts == expected_table_counts, (
    "Observed source-table record counts do not match "
    "the validated historical table boundaries."
)

print("\nSource-table record counts: PASSED")


# -----------------------------------------------------------------------------
# 9. Summary
# -----------------------------------------------------------------------------

n_unique_source_taxa = (
    structure_raw["Source_Species"]
    .nunique()
)


print("\nRaw reconstruction summary")
print("-" * 72)

print(
    f"Structural records        : {len(structure_raw)}"
)

print(
    f"Unique source taxa        : {n_unique_source_taxa}"
)

print(
    f"Source tables             : {n_source_tables}"
)

print(
    f"Zone × Habitat contexts   : "
    f"{len(observed_combinations)}"
)

print(
    f"Duplicate groups retained : "
    f"{duplicate_group_count}"
)


print("\nFinal raw reconstruction validation: PASSED")

Final raw reconstruction validation
========================================================================
Structural records       : 222
Source tables            : 9
Unique record IDs        : 222

Empty essential fields
------------------------------------------------------------------------
Source_Species      : 0
Source_Family       : 0
Management_Zone     : 0
Habitat             : 0
Total_DBH           : 0
Mean_DBH            : 0
Total_Height        : 0
Mean_Height         : 0
Basal_Area          : 0
BA_Percent          : 0
Source_Table        : 0
Source_Page         : 0
Source_Row          : 0

Management Zone × Habitat coverage: PASSED

Historical duplicate-source check
------------------------------------------------------------------------
Records participating in duplicates : 2
Duplicate taxon-context groups       : 1

,Raw_Record_ID,Source_Species,Management_Zone,Habitat,Total_DBH,Mean_DBH,Total_Height,Mean_Height,Basal_Area,BA_Percent,Source_Table,Source_Row
17,OMO_STR_0018,Picralima nitida,Core,Stream,232.7,46.5,239.4,47.8,1698.9,4.33,4.1,19
18,OMO_STR_0019,Picralima nitida,Core,Stream,221.2,55.3,226.9,56.7,2402.8,6.13,4.1,20

Source-table record counts: PASSED

Raw reconstruction summary
------------------------------------------------------------------------
Structural records        : 222
Unique source taxa        : 137
Source tables             : 9
Zone × Habitat contexts   : 9
Duplicate groups retained : 1

Final raw reconstruction validation: PASSED

In [18]:
# =============================================================================
# 07A.4.9 — Assign Reconstruction-Level QC Flags
# =============================================================================

structure_raw["QC_Flag"] = ""


# Flag duplicate Species × Zone × Habitat source records.
duplicate_source_mask = structure_raw.duplicated(
    subset=[
        "Source_Species",
        "Management_Zone",
        "Habitat",
    ],
    keep=False,
)


structure_raw.loc[
    duplicate_source_mask,
    "QC_Flag"
] = "DUPLICATE_SOURCE_RECORD"


print("Reconstruction-level QC flags")
print("=" * 72)

qc_counts = (
    structure_raw["QC_Flag"]
    .replace("", "OK")
    .value_counts()
)

display(
    qc_counts.rename_axis("QC_Status").reset_index(
        name="Records"
    )
)

Reconstruction-level QC flags
========================================================================

                 QC_Status  Records
0                       OK      220
1  DUPLICATE_SOURCE_RECORD        2

In [19]:
# =============================================================================
# 07A.4.10 — Export Faithful Historical Reconstruction
# =============================================================================

structure_raw.to_csv(
    STRUCTURE_RAW_FILE,
    index=False,
    encoding="utf-8",
)


assert STRUCTURE_RAW_FILE.exists(), (
    "omo_tree_structure_raw.csv was not created."
)


print("Raw structural reconstruction exported successfully.")
print("=" * 72)

print(f"Output file : {STRUCTURE_RAW_FILE}")
print(f"Records     : {len(structure_raw)}")
print(f"Columns     : {structure_raw.shape[1]}")

print("\nQC summary")
print("-" * 72)

display(
    structure_raw["QC_Flag"]
    .replace("", "OK")
    .value_counts()
    .rename_axis("QC_Status")
    .reset_index(name="Records")
)

Raw structural reconstruction exported successfully.
========================================================================
Output file : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\notebook_07a\omo_tree_structure_raw.csv
Records     : 222
Columns     : 15

QC summary
------------------------------------------------------------------------

                 QC_Status  Records
0                       OK      220
1  DUPLICATE_SOURCE_RECORD        2

## 07A.5 — Taxonomic Reconciliation of Structural Source Names

This section reconciles historical species names in the structural source with
the validated 127-species canonical inventory inherited from Notebook 05.

Taxonomic reconciliation follows a conservative hierarchy:

1. exact canonical match;
2. normalized canonical match;
3. matching supported by existing Notebook 05 taxonomic audit resources;
4. unresolved candidate identification;
5. manual review where necessary.

No ambiguous taxon will be silently assigned to a canonical species.

The historical `Source_Species` field is preserved throughout the workflow.

The principal output of this section will be:

`structure_taxonomic_matching.csv`

In [20]:
# =============================================================================
# 07A.5.1 — Build Unique Structural Species Inventory
# =============================================================================

# One taxonomic reconciliation record per historical source-species name.
# Family information is retained as provenance but does not define the taxon.

structure_taxa = (
    structure_raw[
        [
            "Source_Species",
            "Source_Family",
        ]
    ]
    .groupby(
        "Source_Species",
        as_index=False,
        sort=True,
    )
    .agg(
        Source_Families=(
            "Source_Family",
            lambda x: "; ".join(
                sorted(
                    set(
                        str(v).strip()
                        for v in x
                        if str(v).strip()
                    )
                )
            ),
        ),
        Family_Variants=(
            "Source_Family",
            lambda x: len(
                set(
                    str(v).strip()
                    for v in x
                    if str(v).strip()
                )
            ),
        ),
    )
)


print("Historical structural species inventory")
print("=" * 72)

print(f"Structural records          : {len(structure_raw)}")
print(f"Unique source species       : {len(structure_taxa)}")

print(
    f"Species with >1 family label: "
    f"{(structure_taxa['Family_Variants'] > 1).sum()}"
)

display(structure_taxa.head(20))

Historical structural species inventory
========================================================================
Structural records          : 222
Unique source species       : 137
Species with >1 family label: 25

              Source_Species              Source_Families  Family_Variants
0          Albizia auxillary                     Fabaceae                1
1         Albizia ferruginea                  Mimosoideae                1
2              Albizia zygia  Mimosoideceae; leguminoceae                2
3            Alstonei boonei                 Apocyanaceae                1
4           Alstonia  boonei                  Apocynaceae                1
5            Alstonia boonei                  Apocynaceae                1
6       Amphimas tetracoides               Papilionoideae                1
7          Aningeria robusta                   Sapotaceae                1
8           Annonidium manni     Annonacaceae; Annonaceae                2
9   Anthocleista djalonensis                  Loganiaceae                1
10     Anthocliesta  vogelii                  Loganiaceae                1
11       Anthocliesta vogeli                 Longaniaceae                1
12    Anthonotha macrophylla              Caesalpinoideae                1
13       Artocarpus communis                     Moraceae                1
14          Bambusa vulgaris            Poaceae; Pocaceae                2
15             Baphia nitida                  Sapindaceae                1
16             Blghia sapida                  Sapindaceae                1
17            Blighia Sapida                  Sapindaceae                1
18            Blighia sapida     Sapindaceae; sapindaceae                2
19         Blighia unijigata                  Sapindaceae                1

In [21]:
# =============================================================================
# 07A.5.1A — Taxonomic Matching Utilities
# =============================================================================

import re
import unicodedata
from difflib import SequenceMatcher


def normalize_taxon_for_matching(name):
    """
    Normalize a taxonomic name for comparison only.

    Historical source names are never modified by this function.

    Normalization:
    - handles missing values;
    - converts to string;
    - applies Unicode normalization;
    - removes leading/trailing whitespace;
    - collapses repeated internal whitespace;
    - converts to lowercase.
    """

    if pd.isna(name):
        return ""

    name = str(name)

    name = unicodedata.normalize(
        "NFKC",
        name,
    )

    name = name.strip()

    name = re.sub(
        r"\s+",
        " ",
        name,
    )

    name = name.lower()

    return name


def taxon_similarity(a, b):
    """
    Calculate similarity between two taxonomic names after
    matching-only normalization.
    """

    return SequenceMatcher(
        None,
        normalize_taxon_for_matching(a),
        normalize_taxon_for_matching(b),
    ).ratio()


# -----------------------------------------------------------------------------
# Basic utility validation
# -----------------------------------------------------------------------------

assert (
    normalize_taxon_for_matching("Alstonia  boonei")
    ==
    normalize_taxon_for_matching("Alstonia boonei")
)

assert (
    normalize_taxon_for_matching("Blighia Sapida")
    ==
    normalize_taxon_for_matching("Blighia sapida")
)

assert (
    normalize_taxon_for_matching("  Celtis zenkeri  ")
    ==
    "celtis zenkeri"
)


print("Taxonomic matching utilities initialized: PASSED")

Taxonomic matching utilities initialized: PASSED

In [22]:
# =============================================================================
# 07A.5.2 — Exact Canonical Matching
# =============================================================================

canonical_species_set = set(
    canonical_species_metadata
)


structure_taxa["Canonical_Species"] = pd.NA
structure_taxa["Match_Status"] = "UNRESOLVED"
structure_taxa["Match_Method"] = pd.NA


# -----------------------------------------------------------------------------
# Exact source-name → canonical-name matching
# -----------------------------------------------------------------------------

exact_match_mask = (
    structure_taxa["Source_Species"]
    .isin(canonical_species_set)
)


structure_taxa.loc[
    exact_match_mask,
    "Canonical_Species"
] = structure_taxa.loc[
    exact_match_mask,
    "Source_Species"
]


structure_taxa.loc[
    exact_match_mask,
    "Match_Status"
] = "EXACT_CANONICAL_MATCH"


structure_taxa.loc[
    exact_match_mask,
    "Match_Method"
] = "Exact string match"


# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

n_exact = int(exact_match_mask.sum())

n_unresolved = int(
    structure_taxa["Match_Status"]
    .eq("UNRESOLVED")
    .sum()
)


print("Exact canonical taxonomic matching")
print("=" * 72)

print(f"Source species examined : {len(structure_taxa)}")
print(f"Exact canonical matches : {n_exact}")
print(f"Remaining unresolved    : {n_unresolved}")


display(
    structure_taxa.loc[
        structure_taxa["Match_Status"] == "UNRESOLVED",
        [
            "Source_Species",
            "Source_Families",
        ],
    ]
)

Exact canonical taxonomic matching
========================================================================
Source species examined : 137
Exact canonical matches : 105
Remaining unresolved    : 32

                Source_Species         Source_Families
0            Albizia auxillary                Fabaceae
3              Alstonei boonei            Apocyanaceae
4             Alstonia  boonei             Apocynaceae
10       Anthocliesta  vogelii             Loganiaceae
11         Anthocliesta vogeli            Longaniaceae
16               Blghia sapida             Sapindaceae
17              Blighia Sapida             Sapindaceae
20          Bombax buonopozene  Bombacaceae; Bombaceae
22          Bosquei angolensis                Moraceae
26        Bridellia ferruginea           euphorbiaceae
35        Cleistoformis patent              Annonaceae
36        Cleistopholis Patens              Annonaceae
45     Diospyros mespiliformis               Ebenaceae
54           Elaeis guinenesis                  Palmae
64       Hildergardia baarteri               Malvaceae
66           Homalium  aylmeri          Flacourtiaceae
71       Lonchocarpus cayensis                Fabaceae
72        Lonchocarpus ciliata                Fabaceae
77       Magaritaria discoidea           Euphorbiaceae
80          Mesobotyra barteri           Euphorbiaceae
81            Micranga barteri           Euphorbiaceae
85         Monodora lenuifolia             Monimiaceae
90        Nauclea  diderrichii               Rubiaceae
95   Nesorgodonia papaverifera           Sterculiaceae
98         Pavetta  corymbosia               Rubiaceae
99           Pavetta crassipes               Rubiaceae
103  Pterocarpus santpxyloides         Papillionoideae
106       Pycnantus angolensis            Myristiaceae
109   Ricinidendron heudelotii           Euphorbiaceae
115          Scotelia coriacea          Flacourtiaceae
122      Strombosia  pustulata               Olacaceae
136         irvinga gabonensis             Irvingaceae

In [23]:
# =============================================================================
# 07A.5.3 — Normalized Exact Canonical Matching
# =============================================================================

# IMPORTANT:
# This section resolves ONLY harmless formatting differences:
# - capitalization
# - leading/trailing whitespace
# - repeated internal whitespace
#
# No spelling correction is performed here.


# -----------------------------------------------------------------------------
# 1. Build normalized canonical lookup
# -----------------------------------------------------------------------------

canonical_normalized_lookup = {}

for canonical_name in canonical_species_metadata:

    normalized_name = normalize_taxon_for_matching(
        canonical_name
    )

    # Protect against accidental collisions in the canonical inventory.
    if normalized_name in canonical_normalized_lookup:

        existing_name = canonical_normalized_lookup[
            normalized_name
        ]

        assert existing_name == canonical_name, (
            "Normalization collision detected in canonical taxonomy: "
            f"{existing_name!r} and {canonical_name!r}"
        )

    canonical_normalized_lookup[
        normalized_name
    ] = canonical_name


print("Normalized canonical lookup")
print("=" * 72)

print(
    f"Canonical species supplied : "
    f"{len(canonical_species_metadata)}"
)

print(
    f"Normalized lookup entries  : "
    f"{len(canonical_normalized_lookup)}"
)


assert len(canonical_normalized_lookup) == 127, (
    "Expected 127 unique normalized canonical species names."
)


# -----------------------------------------------------------------------------
# 2. Apply normalized exact matching only to unresolved source taxa
# -----------------------------------------------------------------------------

normalized_matches_applied = []


for idx in structure_taxa.index:

    if structure_taxa.at[
        idx,
        "Match_Status"
    ] != "UNRESOLVED":
        continue

    source_name = structure_taxa.at[
        idx,
        "Source_Species"
    ]

    normalized_source = normalize_taxon_for_matching(
        source_name
    )

    if normalized_source in canonical_normalized_lookup:

        canonical_name = canonical_normalized_lookup[
            normalized_source
        ]

        structure_taxa.at[
            idx,
            "Canonical_Species"
        ] = canonical_name

        structure_taxa.at[
            idx,
            "Match_Status"
        ] = "NORMALIZED_CANONICAL_MATCH"

        structure_taxa.at[
            idx,
            "Match_Method"
        ] = (
            "Case/whitespace-normalized exact match"
        )

        normalized_matches_applied.append(
            {
                "Source_Species": source_name,
                "Canonical_Species": canonical_name,
            }
        )


normalized_matches_applied = pd.DataFrame(
    normalized_matches_applied
)


# -----------------------------------------------------------------------------
# 3. Summary
# -----------------------------------------------------------------------------

n_normalized_matches = int(
    structure_taxa["Match_Status"]
    .eq("NORMALIZED_CANONICAL_MATCH")
    .sum()
)

n_unresolved = int(
    structure_taxa["Match_Status"]
    .eq("UNRESOLVED")
    .sum()
)


print("\nNormalized canonical taxonomic matching")
print("=" * 72)

print(
    f"Normalized matches applied : "
    f"{n_normalized_matches}"
)

print(
    f"Remaining unresolved       : "
    f"{n_unresolved}"
)


print("\nNormalized matches")
print("-" * 72)

display(normalized_matches_applied)


print("\nCurrent matching status")
print("-" * 72)

display(
    structure_taxa["Match_Status"]
    .value_counts()
    .rename_axis("Match_Status")
    .reset_index(name="Taxa")
)


# -----------------------------------------------------------------------------
# 4. Remaining unresolved taxa
# -----------------------------------------------------------------------------

remaining_unresolved = (
    structure_taxa.loc[
        structure_taxa["Match_Status"] == "UNRESOLVED",
        [
            "Source_Species",
            "Source_Families",
        ],
    ]
    .copy()
    .sort_values("Source_Species")
    .reset_index(drop=True)
)


print("\nRemaining unresolved taxa")
print("-" * 72)

display(remaining_unresolved)


# -----------------------------------------------------------------------------
# 5. Locked validation
#
# The validated source state established earlier showed exactly 8 harmless
# case/whitespace variants.
# -----------------------------------------------------------------------------

expected_normalized_source_taxa = {
    "Alstonia  boonei",
    "Blighia Sapida",
    "Cleistopholis Patens",
    "Homalium  aylmeri",
    "Nauclea  diderrichii",
    "Pavetta  corymbosia",
    "Strombosia  pustulata",
    "irvinga gabonensis",
}


observed_normalized_source_taxa = set(
    normalized_matches_applied[
        "Source_Species"
    ]
)


assert n_normalized_matches == 8, (
    "Expected exactly 8 normalized canonical matches."
)

assert observed_normalized_source_taxa == expected_normalized_source_taxa, (
    "Normalized matching did not resolve the expected eight "
    "case/whitespace variants."
)

assert n_unresolved == 24, (
    "Expected exactly 24 taxa to remain unresolved after "
    "normalized exact matching."
)


print("\nNormalized canonical matching validation: PASSED")

Normalized canonical lookup
========================================================================
Canonical species supplied : 127
Normalized lookup entries  : 127

Normalized canonical taxonomic matching
========================================================================
Normalized matches applied : 8
Remaining unresolved       : 24

Normalized matches
------------------------------------------------------------------------

          Source_Species     Canonical_Species
0       Alstonia  boonei       Alstonia boonei
1         Blighia Sapida        Blighia sapida
2   Cleistopholis Patens  Cleistopholis patens
3      Homalium  aylmeri      Homalium aylmeri
4   Nauclea  diderrichii   Nauclea diderrichii
5    Pavetta  corymbosia    Pavetta corymbosia
6  Strombosia  pustulata  Strombosia pustulata
7     irvinga gabonensis    Irvinga gabonensis

Current matching status
------------------------------------------------------------------------

                 Match_Status  Taxa
0       EXACT_CANONICAL_MATCH   105
1                  UNRESOLVED    24
2  NORMALIZED_CANONICAL_MATCH     8

Remaining unresolved taxa
------------------------------------------------------------------------

               Source_Species         Source_Families
0           Albizia auxillary                Fabaceae
1             Alstonei boonei            Apocyanaceae
2       Anthocliesta  vogelii             Loganiaceae
3         Anthocliesta vogeli            Longaniaceae
4               Blghia sapida             Sapindaceae
5          Bombax buonopozene  Bombacaceae; Bombaceae
6          Bosquei angolensis                Moraceae
7        Bridellia ferruginea           euphorbiaceae
8        Cleistoformis patent              Annonaceae
9     Diospyros mespiliformis               Ebenaceae
10          Elaeis guinenesis                  Palmae
11      Hildergardia baarteri               Malvaceae
12      Lonchocarpus cayensis                Fabaceae
13       Lonchocarpus ciliata                Fabaceae
14      Magaritaria discoidea           Euphorbiaceae
15         Mesobotyra barteri           Euphorbiaceae
16           Micranga barteri           Euphorbiaceae
17        Monodora lenuifolia             Monimiaceae
18  Nesorgodonia papaverifera           Sterculiaceae
19          Pavetta crassipes               Rubiaceae
20  Pterocarpus santpxyloides         Papillionoideae
21       Pycnantus angolensis            Myristiaceae
22   Ricinidendron heudelotii           Euphorbiaceae
23          Scotelia coriacea          Flacourtiaceae

Normalized canonical matching validation: PASSED

In [24]:
# =============================================================================
# 07A.5.4 — Generate Controlled Candidate Matches for Unresolved Taxa
# =============================================================================

from difflib import SequenceMatcher


# -----------------------------------------------------------------------------
# Unresolved source taxa
# -----------------------------------------------------------------------------

unresolved_taxa = (
    structure_taxa.loc[
        structure_taxa["Match_Status"] == "UNRESOLVED"
    ]
    .copy()
)


# -----------------------------------------------------------------------------
# Similarity helper
#
# Candidate generation only.
# Similarity scores MUST NOT be treated as automatic taxonomic decisions.
# -----------------------------------------------------------------------------

def taxon_similarity(a, b):
    return SequenceMatcher(
        None,
        normalize_taxon_for_matching(a),
        normalize_taxon_for_matching(b),
    ).ratio()


candidate_records = []


for _, row in unresolved_taxa.iterrows():

    source_name = row["Source_Species"]

    candidates = []

    for canonical_name in canonical_species_metadata:

        score = taxon_similarity(
            source_name,
            canonical_name,
        )

        candidates.append(
            (
                canonical_name,
                score,
            )
        )

    candidates = sorted(
        candidates,
        key=lambda x: x[1],
        reverse=True,
    )[:3]


    candidate_records.append(
        {
            "Source_Species": source_name,
            "Source_Families": row["Source_Families"],
            "Candidate_1": candidates[0][0],
            "Similarity_1": round(candidates[0][1], 3),
            "Candidate_2": candidates[1][0],
            "Similarity_2": round(candidates[1][1], 3),
            "Candidate_3": candidates[2][0],
            "Similarity_3": round(candidates[2][1], 3),
        }
    )


candidate_review = pd.DataFrame(candidate_records)


print("Candidate review for unresolved structural taxa")
print("=" * 72)

print(
    f"Unresolved source taxa : {len(candidate_review)}"
)

display(candidate_review)

Candidate review for unresolved structural taxa
========================================================================
Unresolved source taxa : 24

,Source_Species,Source_Families,Candidate_1,Similarity_1,Candidate_2,Similarity_2,Candidate_3,Similarity_3
0,Albizia auxillary,Fabaceae,Albizia auxilary,0.970,Albizia zygia,0.600,Blighia sapida,0.516
1,Alstonei boonei,Apocyanaceae,Alstonia boonei,0.933,Spondia mombin,0.483,Anthocleista vogelii,0.457
2,Anthocliesta vogelii,Loganiaceae,Anthocleista vogelii,0.950,Anthocleista djalonensis,0.682,Alstonia boonei,0.514
3,Anthocliesta vogeli,Longaniaceae,Anthocleista vogelii,0.923,Anthocleista djalonensis,0.698,Alstonia boonei,0.529
4,Blghia sapida,Sapindaceae,Blighia sapida,0.963,Baphia nitida,0.615,Rothmania hispida,0.600
5,Bombax buonopozene,Bombacaceae; Bombaceae,Bombax buonopozense,0.973,Elaeis guineense,0.412,Cola species,0.400
6,Bosquei angolensis,Moraceae,Bosqueia angolensis,0.973,Pycanthus angolensis,0.632,Pycnanthus angolensis,0.615
7,Bridellia ferruginea,euphorbiaceae,Bridelia ferruginea,0.974,Albizia ferruginea,0.789,Afzelia africana,0.556
8,Cleistoformis patent,Annonaceae,Cleistoformis patens,0.950,Cleistopholis patens,0.800,Diospyrous melistoformis,0.500
9,Diospyros mespiliformis,Ebenaceae,Diospyrous mespiliformis,0.979,Diospyrous melistoformis,0.851,Diospyros dendo,0.632
10,Elaeis guinenesis,Palmae,Elaeis guinensis,0.970,Elaeis guineensis,0.941,Elaeis guineense,0.848
11,Hildergardia baarteri,Malvaceae,Hildegardia barteri,0.950,Macaranga barteri,0.579,Macranga bateri,0.556
12,Lonchocarpus cayensis,Fabaceae,Lonchocarpus cyanescens,0.818,Lonchocarpus cilliata,0.714,Artocarpus communis,0.600
13,Lonchocarpus ciliata,Fabaceae,Lonchocarpus cilliata,0.976,Lonchocarpus cyanescens,0.698,Mitragyna cilliata,0.526
14,Magaritaria discoidea,Euphorbiaceae,Margaritaria discoidea,0.977,Margartaria discoidea,0.952,Garcinia kola,0.529
15,Mesobotyra barteri,Euphorbiaceae,Maesobotrya barteri,0.919,Macaranga barteri,0.629,Macranga bateri,0.606
16,Micranga barteri,Euphorbiaceae,Macaranga barteri,0.909,Macranga bateri,0.903,Hildegardia barteri,0.629
17,Monodora lenuifolia,Monimiaceae,Monodora tenuifolia,0.947,Melacantha alnifolia,0.615,Rinorea dentata,0.471
18,Nesorgodonia papaverifera,Sterculiaceae,Nesogordonia papaverifera,0.960,Nesodogornia papaverifera,0.880,Nesodogornia papaverivera,0.840
19,Pavetta crassipes,Rubiaceae,Pavetta corymbosia,0.686,Pavetta corymbosa,0.647,Amphimas tetracoides,0.486
20,Pterocarpus santpxyloides,Papillionoideae,Pterocarpus santoxyloides,0.960,Pterocarpus osun,0.683,Lecaniodiscus cupanioides,0.520
21,Pycnantus angolensis,Myristiaceae,Pycnanthus angolensis,0.976,Pycanthus angolensis,0.950,Bosqueia angolensis,0.615
22,Ricinidendron heudelotii,Euphorbiaceae,Ricinidendron heudeloti,0.979,Ricinodendron heudelotii,0.958,Ricinodendron heudeloti,0.936
23,Scotelia coriacea,Flacourtiaceae,Scotellia coriacea,0.971,Scotellia coriaceae,0.944,Scotellia coricea,0.941

In [25]:
# =============================================================================
# 07A.5.5 — Apply Controlled Historical-Name Harmonizations
# =============================================================================

# These mappings are conservative reconciliations with the validated
# 127-species canonical inventory.
#
# Important:
# - Source_Species values are NEVER modified.
# - Matching uses normalized source strings only.
# - Canonical targets must already exist in the validated canonical inventory.
# - This cell is designed to be safe to rerun.

controlled_harmonizations = {
    "Albizia auxillary": "Albizia auxilary",
    "Alstonei boonei": "Alstonia boonei",
    "Anthocliesta vogelii": "Anthocleista vogelii",
    "Anthocliesta vogeli": "Anthocleista vogelii",
    "Blghia sapida": "Blighia sapida",
    "Bombax buonopozene": "Bombax buonopozense",
    "Bosquei angolensis": "Bosqueia angolensis",
    "Bridellia ferruginea": "Bridelia ferruginea",
    "Cleistoformis patent": "Cleistoformis patens",
    "Diospyros mespiliformis": "Diospyrous mespiliformis",
    "Hildergardia baarteri": "Hildegardia barteri",
    "Lonchocarpus ciliata": "Lonchocarpus cilliata",
    "Magaritaria discoidea": "Margaritaria discoidea",
    "Mesobotyra barteri": "Maesobotrya barteri",
    "Monodora lenuifolia": "Monodora tenuifolia",
    "Nesorgodonia papaverifera": "Nesogordonia papaverifera",
    "Pterocarpus santpxyloides": "Pterocarpus santoxyloides",
    "Pycnantus angolensis": "Pycnanthus angolensis",
    "Scotelia coriacea": "Scotellia coriacea",
}


# -----------------------------------------------------------------------------
# 1. Validate canonical targets
# -----------------------------------------------------------------------------

invalid_targets = sorted(
    set(controlled_harmonizations.values())
    - canonical_species_set
)

assert not invalid_targets, (
    "One or more controlled harmonization targets are not present "
    f"in the canonical 127 inventory: {invalid_targets}"
)


# -----------------------------------------------------------------------------
# 2. Normalized lookup for the 19 controlled mappings
# -----------------------------------------------------------------------------

controlled_harmonizations_normalized = {
    normalize_taxon_for_matching(source_name): canonical_name
    for source_name, canonical_name
    in controlled_harmonizations.items()
}


# -----------------------------------------------------------------------------
# 3. Apply mappings
#
# Apply only where the taxon has not already received a downstream
# individual-review classification.
# -----------------------------------------------------------------------------

protected_review_statuses = {
    "AMBIGUOUS",
    "NOT_IN_CANONICAL_127",
}


for idx in structure_taxa.index:

    source_name = structure_taxa.at[
        idx,
        "Source_Species"
    ]

    normalized_source = normalize_taxon_for_matching(
        source_name
    )

    current_status = structure_taxa.at[
        idx,
        "Match_Status"
    ]

    # Do not overwrite later individual-review decisions.
    if current_status in protected_review_statuses:
        continue

    if normalized_source in controlled_harmonizations_normalized:

        canonical_name = (
            controlled_harmonizations_normalized[
                normalized_source
            ]
        )

        structure_taxa.at[
            idx,
            "Canonical_Species"
        ] = canonical_name

        structure_taxa.at[
            idx,
            "Match_Status"
        ] = "HARMONIZED_MATCH"

        structure_taxa.at[
            idx,
            "Match_Method"
        ] = (
            "Controlled historical-name harmonization"
        )


# -----------------------------------------------------------------------------
# 4. Validate the 19 controlled harmonizations directly
# -----------------------------------------------------------------------------

controlled_source_normalized = set(
    controlled_harmonizations_normalized.keys()
)


controlled_mask = (
    structure_taxa["Source_Species"]
    .apply(normalize_taxon_for_matching)
    .isin(controlled_source_normalized)
)


controlled_results = (
    structure_taxa.loc[
        controlled_mask,
        [
            "Source_Species",
            "Canonical_Species",
            "Match_Status",
            "Match_Method",
        ],
    ]
    .copy()
    .sort_values("Source_Species")
    .reset_index(drop=True)
)


n_controlled_records = len(controlled_results)

n_harmonized = int(
    controlled_results["Match_Status"]
    .eq("HARMONIZED_MATCH")
    .sum()
)


print("Controlled historical-name harmonization")
print("=" * 72)

print(
    f"Controlled mappings defined : "
    f"{len(controlled_harmonizations)}"
)

print(
    f"Controlled source taxa found: "
    f"{n_controlled_records}"
)

print(
    f"HARMONIZED_MATCH taxa       : "
    f"{n_harmonized}"
)


display(controlled_results)


assert n_controlled_records == 19, (
    "Expected exactly 19 controlled source taxa in structure_taxa."
)

assert n_harmonized == 19, (
    "Expected exactly 19 controlled taxa to have HARMONIZED_MATCH status."
)


# -----------------------------------------------------------------------------
# 5. Identify taxa still requiring individual review
# -----------------------------------------------------------------------------

expected_review_taxa = {
    "Elaeis guinenesis",
    "Lonchocarpus cayensis",
    "Micranga barteri",
    "Pavetta crassipes",
    "Ricinidendron heudelotii",
}


review_taxa_state = (
    structure_taxa.loc[
        structure_taxa["Source_Species"].isin(
            expected_review_taxa
        ),
        [
            "Source_Species",
            "Canonical_Species",
            "Match_Status",
            "Match_Method",
        ],
    ]
    .copy()
    .sort_values("Source_Species")
    .reset_index(drop=True)
)


assert len(review_taxa_state) == 5, (
    "Expected all five individual-review taxa to exist in structure_taxa."
)


print("\nFive taxa reserved for individual review")
print("-" * 72)

display(review_taxa_state)


# -----------------------------------------------------------------------------
# 6. Current complete matching-status summary
# -----------------------------------------------------------------------------

print("\nCurrent matching status")
print("-" * 72)

status_summary = (
    structure_taxa["Match_Status"]
    .value_counts(dropna=False)
    .rename_axis("Match_Status")
    .reset_index(name="Taxa")
)

display(status_summary)


# -----------------------------------------------------------------------------
# 7. Check for unexpected unresolved taxa
#
# Only the five predefined individual-review taxa are allowed to remain
# unresolved at this stage.
# -----------------------------------------------------------------------------

remaining_unresolved = (
    structure_taxa.loc[
        structure_taxa["Match_Status"] == "UNRESOLVED",
        [
            "Source_Species",
            "Source_Families",
        ],
    ]
    .copy()
    .sort_values("Source_Species")
    .reset_index(drop=True)
)


unexpected_unresolved = set(
    remaining_unresolved["Source_Species"]
) - expected_review_taxa


assert not unexpected_unresolved, (
    "Unexpected unresolved taxa remain after controlled harmonization: "
    f"{sorted(unexpected_unresolved)}"
)


print(
    f"\nCurrently UNRESOLVED taxa : "
    f"{len(remaining_unresolved)}"
)

if len(remaining_unresolved) > 0:
    display(remaining_unresolved)


print("\nControlled harmonization validation: PASSED")

Controlled historical-name harmonization
========================================================================
Controlled mappings defined : 19
Controlled source taxa found: 19
HARMONIZED_MATCH taxa       : 19

,Source_Species,Canonical_Species,Match_Status,Match_Method
0,Albizia auxillary,Albizia auxilary,HARMONIZED_MATCH,Controlled historical-name harmonization
1,Alstonei boonei,Alstonia boonei,HARMONIZED_MATCH,Controlled historical-name harmonization
2,Anthocliesta vogelii,Anthocleista vogelii,HARMONIZED_MATCH,Controlled historical-name harmonization
3,Anthocliesta vogeli,Anthocleista vogelii,HARMONIZED_MATCH,Controlled historical-name harmonization
4,Blghia sapida,Blighia sapida,HARMONIZED_MATCH,Controlled historical-name harmonization
5,Bombax buonopozene,Bombax buonopozense,HARMONIZED_MATCH,Controlled historical-name harmonization
6,Bosquei angolensis,Bosqueia angolensis,HARMONIZED_MATCH,Controlled historical-name harmonization
7,Bridellia ferruginea,Bridelia ferruginea,HARMONIZED_MATCH,Controlled historical-name harmonization
8,Cleistoformis patent,Cleistoformis patens,HARMONIZED_MATCH,Controlled historical-name harmonization
9,Diospyros mespiliformis,Diospyrous mespiliformis,HARMONIZED_MATCH,Controlled historical-name harmonization
10,Hildergardia baarteri,Hildegardia barteri,HARMONIZED_MATCH,Controlled historical-name harmonization
11,Lonchocarpus ciliata,Lonchocarpus cilliata,HARMONIZED_MATCH,Controlled historical-name harmonization
12,Magaritaria discoidea,Margaritaria discoidea,HARMONIZED_MATCH,Controlled historical-name harmonization
13,Mesobotyra barteri,Maesobotrya barteri,HARMONIZED_MATCH,Controlled historical-name harmonization
14,Monodora lenuifolia,Monodora tenuifolia,HARMONIZED_MATCH,Controlled historical-name harmonization
15,Nesorgodonia papaverifera,Nesogordonia papaverifera,HARMONIZED_MATCH,Controlled historical-name harmonization
16,Pterocarpus santpxyloides,Pterocarpus santoxyloides,HARMONIZED_MATCH,Controlled historical-name harmonization
17,Pycnantus angolensis,Pycnanthus angolensis,HARMONIZED_MATCH,Controlled historical-name harmonization
18,Scotelia coriacea,Scotellia coriacea,HARMONIZED_MATCH,Controlled historical-name harmonization

Five taxa reserved for individual review
------------------------------------------------------------------------

             Source_Species Canonical_Species Match_Status Match_Method
0         Elaeis guinenesis              <NA>   UNRESOLVED         <NA>
1     Lonchocarpus cayensis              <NA>   UNRESOLVED         <NA>
2          Micranga barteri              <NA>   UNRESOLVED         <NA>
3         Pavetta crassipes              <NA>   UNRESOLVED         <NA>
4  Ricinidendron heudelotii              <NA>   UNRESOLVED         <NA>

Current matching status
------------------------------------------------------------------------

                 Match_Status  Taxa
0       EXACT_CANONICAL_MATCH   105
1            HARMONIZED_MATCH    19
2  NORMALIZED_CANONICAL_MATCH     8
3                  UNRESOLVED     5

Currently UNRESOLVED taxa : 5

             Source_Species Source_Families
0         Elaeis guinenesis          Palmae
1     Lonchocarpus cayensis        Fabaceae
2          Micranga barteri   Euphorbiaceae
3         Pavetta crassipes       Rubiaceae
4  Ricinidendron heudelotii   Euphorbiaceae

Controlled harmonization validation: PASSED

## 07A.5.6 — Individual Review of Remaining Structural Taxa

Five historical structural taxa remain unresolved after exact, normalized,
and controlled historical-name matching.

These taxa are reviewed individually against the validated 127-species
canonical inventory and the historical structural context.

No taxon is forced into the canonical inventory where:

- multiple competing canonical variants exist;
- the historical source distinguishes the taxon from a similar species; or
- no sufficiently supported canonical equivalent is available.

Such taxa are retained either as `AMBIGUOUS` or `NOT_IN_CANONICAL_127`.

In [26]:
# =============================================================================
# 07A.5.6 — Individual Review of Remaining Structural Taxa
# =============================================================================

individual_taxon_decisions = {
    "Elaeis guinenesis": {
        "Canonical_Species": pd.NA,
        "Match_Status": "AMBIGUOUS",
        "Match_Method": "Individual review",
        "Taxonomic_Notes": (
            "Multiple competing Elaeis forms remain in the canonical "
            "127 inventory: Elaeis guineensis, Elaeis guinensis, and "
            "Elaeis guineense. No silent assignment made."
        ),
    },

    "Lonchocarpus cayensis": {
        "Canonical_Species": pd.NA,
        "Match_Status": "NOT_IN_CANONICAL_127",
        "Match_Method": "Individual review",
        "Taxonomic_Notes": (
            "No exact canonical equivalent. Historical source contains "
            "other Lonchocarpus taxa separately, so similarity to "
            "Lonchocarpus cyanescens is insufficient for consolidation."
        ),
    },

    "Micranga barteri": {
        "Canonical_Species": pd.NA,
        "Match_Status": "AMBIGUOUS",
        "Match_Method": "Individual review",
        "Taxonomic_Notes": (
            "Macaranga barteri exists in the canonical inventory, but "
            "Macaranga barteri and Micranga barteri occur as separate "
            "historical structural records. Automatic consolidation "
            "would therefore be unsafe."
        ),
    },

    "Pavetta crassipes": {
        "Canonical_Species": pd.NA,
        "Match_Status": "NOT_IN_CANONICAL_127",
        "Match_Method": "Individual review",
        "Taxonomic_Notes": (
            "No supported canonical equivalent identified. Similarity "
            "to Pavetta corymbosa/corymbosia is insufficient for "
            "taxonomic consolidation."
        ),
    },

    "Ricinidendron heudelotii": {
        "Canonical_Species": pd.NA,
        "Match_Status": "AMBIGUOUS",
        "Match_Method": "Individual review",
        "Taxonomic_Notes": (
            "Multiple competing Ricinodendron/Ricinidendron variants "
            "remain in the canonical 127 inventory. No silent assignment made."
        ),
    },
}


# -----------------------------------------------------------------------------
# Apply individual decisions
# -----------------------------------------------------------------------------

for source_name, decision in individual_taxon_decisions.items():

    mask = (
        structure_taxa["Source_Species"].eq(source_name)
        & structure_taxa["Match_Status"].eq("UNRESOLVED")
    )

    assert mask.sum() == 1, (
        f"Expected exactly one unresolved record for {source_name}, "
        f"found {mask.sum()}."
    )

    structure_taxa.loc[
        mask,
        "Canonical_Species"
    ] = decision["Canonical_Species"]

    structure_taxa.loc[
        mask,
        "Match_Status"
    ] = decision["Match_Status"]

    structure_taxa.loc[
        mask,
        "Match_Method"
    ] = decision["Match_Method"]


# -----------------------------------------------------------------------------
# Add taxonomic notes if not already present
# -----------------------------------------------------------------------------

if "Taxonomic_Notes" not in structure_taxa.columns:
    structure_taxa["Taxonomic_Notes"] = pd.NA


for source_name, decision in individual_taxon_decisions.items():

    mask = structure_taxa["Source_Species"].eq(
        source_name
    )

    structure_taxa.loc[
        mask,
        "Taxonomic_Notes"
    ] = decision["Taxonomic_Notes"]


# -----------------------------------------------------------------------------
# Final taxonomic status summary
# -----------------------------------------------------------------------------

status_summary = (
    structure_taxa["Match_Status"]
    .value_counts()
    .rename_axis("Match_Status")
    .reset_index(name="Taxa")
)


print("Individual taxonomic review")
print("=" * 72)

display(status_summary)


remaining_unresolved = (
    structure_taxa["Match_Status"]
    .eq("UNRESOLVED")
    .sum()
)

print(
    f"\nRemaining UNRESOLVED taxa: "
    f"{remaining_unresolved}"
)


# -----------------------------------------------------------------------------
# Display individually reviewed taxa
# -----------------------------------------------------------------------------

display(
    structure_taxa.loc[
        structure_taxa["Source_Species"].isin(
            individual_taxon_decisions.keys()
        ),
        [
            "Source_Species",
            "Source_Families",
            "Canonical_Species",
            "Match_Status",
            "Match_Method",
            "Taxonomic_Notes",
        ],
    ]
    .sort_values("Source_Species")
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------

assert remaining_unresolved == 0, (
    "Unclassified structural taxa remain."
)

assert (
    structure_taxa["Match_Status"]
    .eq("AMBIGUOUS")
    .sum()
    == 3
), (
    "Expected exactly 3 ambiguous taxa."
)

assert (
    structure_taxa["Match_Status"]
    .eq("NOT_IN_CANONICAL_127")
    .sum()
    == 2
), (
    "Expected exactly 2 taxa outside the canonical 127."
)


print("\nIndividual taxonomic review: PASSED")

Individual taxonomic review
========================================================================

                 Match_Status  Taxa
0       EXACT_CANONICAL_MATCH   105
1            HARMONIZED_MATCH    19
2  NORMALIZED_CANONICAL_MATCH     8
3                   AMBIGUOUS     3
4        NOT_IN_CANONICAL_127     2

Remaining UNRESOLVED taxa: 0

,Source_Species,Source_Families,Canonical_Species,Match_Status,Match_Method,Taxonomic_Notes
0,Elaeis guinenesis,Palmae,<NA>,AMBIGUOUS,Individual review,Multiple competing Elaeis forms remain in the ...
1,Lonchocarpus cayensis,Fabaceae,<NA>,NOT_IN_CANONICAL_127,Individual review,No exact canonical equivalent. Historical sour...
2,Micranga barteri,Euphorbiaceae,<NA>,AMBIGUOUS,Individual review,Macaranga barteri exists in the canonical inve...
3,Pavetta crassipes,Rubiaceae,<NA>,NOT_IN_CANONICAL_127,Individual review,No supported canonical equivalent identified. ...
4,Ricinidendron heudelotii,Euphorbiaceae,<NA>,AMBIGUOUS,Individual review,Multiple competing Ricinodendron/Ricinidendron...

Individual taxonomic review: PASSED

## 07A.5.7 — Export Structural Taxonomic Matching Audit

This section creates the permanent taxonomic reconciliation audit linking
historical structural species names to the validated Notebook 05 canonical
inventory.

The matching audit preserves:

- the historical source name;
- historical family labels;
- canonical species where a defensible mapping exists;
- matching status;
- matching method; and
- taxonomic review notes.

Ambiguous taxa and taxa outside the canonical 127 remain explicitly unmapped.

No historical source names are overwritten.

In [27]:
# =============================================================================
# 07A.5.7 — Build Structural Taxonomic Matching Audit
# =============================================================================

structure_taxonomic_matching = (
    structure_taxa[
        [
            "Source_Species",
            "Source_Families",
            "Family_Variants",
            "Canonical_Species",
            "Match_Status",
            "Match_Method",
            "Taxonomic_Notes",
        ]
    ]
    .copy()
    .sort_values("Source_Species")
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Add canonical-membership indicator
# -----------------------------------------------------------------------------

structure_taxonomic_matching["Canonical_Present"] = (
    structure_taxonomic_matching["Canonical_Species"]
    .isin(canonical_species_set)
)


# -----------------------------------------------------------------------------
# Add review indicator
# -----------------------------------------------------------------------------

structure_taxonomic_matching["Review_Required"] = (
    structure_taxonomic_matching["Match_Status"]
    .isin(
        [
            "AMBIGUOUS",
            "NOT_IN_CANONICAL_127",
        ]
    )
)


# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------

assert len(structure_taxonomic_matching) == 137, (
    "Taxonomic matching audit must contain exactly 137 source taxa."
)

assert structure_taxonomic_matching["Source_Species"].is_unique, (
    "Source_Species is not unique in the taxonomic matching audit."
)


# Every assigned canonical species must belong to canonical 127.
assigned_mask = (
    structure_taxonomic_matching["Canonical_Species"]
    .notna()
)

invalid_assigned_taxa = (
    structure_taxonomic_matching.loc[
        assigned_mask
        & ~structure_taxonomic_matching["Canonical_Present"],
        [
            "Source_Species",
            "Canonical_Species",
        ],
    ]
)

assert invalid_assigned_taxa.empty, (
    "One or more assigned canonical species are not present "
    "in the validated 127-species inventory."
)


# No unresolved taxa should remain.
assert not (
    structure_taxonomic_matching["Match_Status"]
    .eq("UNRESOLVED")
    .any()
), (
    "UNRESOLVED taxa remain in the taxonomic matching audit."
)


print("Structural taxonomic matching audit")
print("=" * 72)

print(
    f"Source taxa             : "
    f"{len(structure_taxonomic_matching)}"
)

print(
    f"Mapped canonical taxa   : "
    f"{assigned_mask.sum()}"
)

print(
    f"Unmapped source taxa    : "
    f"{(~assigned_mask).sum()}"
)

print(
    f"Require review          : "
    f"{structure_taxonomic_matching['Review_Required'].sum()}"
)


print("\nMatching-status summary")
print("-" * 72)

display(
    structure_taxonomic_matching["Match_Status"]
    .value_counts()
    .rename_axis("Match_Status")
    .reset_index(name="Taxa")
)


print("\nTaxa requiring review")
print("-" * 72)

display(
    structure_taxonomic_matching.loc[
        structure_taxonomic_matching["Review_Required"],
        [
            "Source_Species",
            "Source_Families",
            "Canonical_Species",
            "Match_Status",
            "Taxonomic_Notes",
        ],
    ]
)

Structural taxonomic matching audit
========================================================================
Source taxa             : 137
Mapped canonical taxa   : 132
Unmapped source taxa    : 5
Require review          : 5

Matching-status summary
------------------------------------------------------------------------

                 Match_Status  Taxa
0       EXACT_CANONICAL_MATCH   105
1            HARMONIZED_MATCH    19
2  NORMALIZED_CANONICAL_MATCH     8
3                   AMBIGUOUS     3
4        NOT_IN_CANONICAL_127     2

Taxa requiring review
------------------------------------------------------------------------

,Source_Species,Source_Families,Canonical_Species,Match_Status,Taxonomic_Notes
54,Elaeis guinenesis,Palmae,<NA>,AMBIGUOUS,Multiple competing Elaeis forms remain in the ...
71,Lonchocarpus cayensis,Fabaceae,<NA>,NOT_IN_CANONICAL_127,No exact canonical equivalent. Historical sour...
81,Micranga barteri,Euphorbiaceae,<NA>,AMBIGUOUS,Macaranga barteri exists in the canonical inve...
99,Pavetta crassipes,Rubiaceae,<NA>,NOT_IN_CANONICAL_127,No supported canonical equivalent identified. ...
109,Ricinidendron heudelotii,Euphorbiaceae,<NA>,AMBIGUOUS,Multiple competing Ricinodendron/Ricinidendron...

In [28]:
# =============================================================================
# 07A.5.8 — Export Structural Taxonomic Matching Audit
# =============================================================================

structure_taxonomic_matching.to_csv(
    STRUCTURE_TAXONOMIC_MATCHING_FILE,
    index=False,
    encoding="utf-8",
)


assert STRUCTURE_TAXONOMIC_MATCHING_FILE.exists(), (
    "structure_taxonomic_matching.csv was not created."
)


print("Taxonomic matching audit exported successfully.")
print("=" * 72)

print(
    f"Output file : "
    f"{STRUCTURE_TAXONOMIC_MATCHING_FILE}"
)

print(
    f"Source taxa : "
    f"{len(structure_taxonomic_matching)}"
)

Taxonomic matching audit exported successfully.
========================================================================
Output file : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\notebook_07a\structure_taxonomic_matching.csv
Source taxa : 137

In [29]:
# =============================================================================
# 07A.5.9 — Build Harmonized Structural Dataset
# =============================================================================

structure_harmonized = (
    structure_raw
    .merge(
        structure_taxonomic_matching[
            [
                "Source_Species",
                "Canonical_Species",
                "Match_Status",
                "Match_Method",
                "Taxonomic_Notes",
                "Canonical_Present",
                "Review_Required",
            ]
        ],
        on="Source_Species",
        how="left",
        validate="many_to_one",
    )
)


print("Harmonized structural dataset")
print("=" * 72)

print(f"Raw structural records        : {len(structure_raw)}")
print(f"Harmonized structural records : {len(structure_harmonized)}")


assert len(structure_harmonized) == len(structure_raw), (
    "Taxonomic harmonization changed the number of structural records."
)

assert len(structure_harmonized) == 222, (
    "Expected exactly 222 harmonized structural records."
)


# -----------------------------------------------------------------------------
# Confirm every source taxon received a matching decision
# -----------------------------------------------------------------------------

missing_decisions = (
    structure_harmonized["Match_Status"]
    .isna()
    .sum()
)

assert missing_decisions == 0, (
    "One or more structural records have no taxonomic matching decision."
)


print(
    f"Records without matching decision : "
    f"{missing_decisions}"
)


# -----------------------------------------------------------------------------
# Display sample
# -----------------------------------------------------------------------------

display(
    structure_harmonized[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Canonical_Species",
            "Match_Status",
            "Management_Zone",
            "Habitat",
            "Mean_DBH",
            "Mean_Height",
            "Basal_Area",
            "QC_Flag",
        ]
    ].head(15)
)


print("\nHarmonized structural join: PASSED")

Harmonized structural dataset
========================================================================
Raw structural records        : 222
Harmonized structural records : 222
Records without matching decision : 0

,Raw_Record_ID,Source_Species,Canonical_Species,Match_Status,Management_Zone,Habitat,Mean_DBH,Mean_Height,Basal_Area,QC_Flag
0,OMO_STR_0001,Alstonia boonei,Alstonia boonei,NORMALIZED_CANONICAL_MATCH,Core,Stream,36.34,35.58,1037.6,
1,OMO_STR_0002,Blighia sapida,Blighia sapida,EXACT_CANONICAL_MATCH,Core,Stream,33.4,35.2,876.51,
2,OMO_STR_0003,Bombax buonopozene,Bombax buonopozense,HARMONIZED_MATCH,Core,Stream,31.5,31.5,779.63,
3,OMO_STR_0004,Bosquei angolensis,Bosqueia angolensis,HARMONIZED_MATCH,Core,Stream,28.7,28.1,647.19,
4,OMO_STR_0005,Celtis zenkeri,Celtis zenkeri,EXACT_CANONICAL_MATCH,Core,Stream,29.4,31,679.14,
5,OMO_STR_0006,Cleistopholis Patens,Cleistopholis patens,NORMALIZED_CANONICAL_MATCH,Core,Stream,31,34.9,755.07,
6,OMO_STR_0007,Dialium guinensis,Dialium guinensis,EXACT_CANONICAL_MATCH,Core,Stream,33.1,32.6,860.84,
7,OMO_STR_0008,Diospyros dendo,Diospyros dendo,EXACT_CANONICAL_MATCH,Core,Stream,21.5,24.9,363.2,
8,OMO_STR_0009,Drypetes,Drypetes,EXACT_CANONICAL_MATCH,Core,Stream,25.1,25.8,495.01,
9,OMO_STR_0010,Ficus exasperata,Ficus exasperata,EXACT_CANONICAL_MATCH,Core,Stream,56.4,54.4,2499.3,
10,OMO_STR_0011,Grewia pubescens,Grewia pubescens,EXACT_CANONICAL_MATCH,Core,Stream,31.5,32.6,779.63,
11,OMO_STR_0012,Homalium alymeri,Homalium alymeri,EXACT_CANONICAL_MATCH,Core,Stream,52.1,50.45,2132.8,
12,OMO_STR_0013,Lecaniodiscus cupanioides,Lecaniodiscus cupanioides,EXACT_CANONICAL_MATCH,Core,Stream,23.7,26,441.33,
13,OMO_STR_0014,Margaritaria discoidea,Margaritaria discoidea,EXACT_CANONICAL_MATCH,Core,Stream,24.9,26.4,487.15,
14,OMO_STR_0015,Musanga cecropoides,Musanga cecropoides,EXACT_CANONICAL_MATCH,Core,Stream,26.9,21.6,568.55,

Harmonized structural join: PASSED

In [30]:
# =============================================================================
# 07A.5.10 — Validate Preservation of Historical Source Values
# =============================================================================

source_preservation_columns = [
    "Raw_Record_ID",
    "Source_Species",
    "Source_Family",
    "Management_Zone",
    "Habitat",
    "Total_DBH",
    "Mean_DBH",
    "Total_Height",
    "Mean_Height",
    "Basal_Area",
    "BA_Percent",
    "Source_Table",
    "Source_Page",
    "Source_Row",
    "QC_Flag",
]


raw_check = (
    structure_raw[
        source_preservation_columns
    ]
    .sort_values("Raw_Record_ID")
    .reset_index(drop=True)
)


harmonized_check = (
    structure_harmonized[
        source_preservation_columns
    ]
    .sort_values("Raw_Record_ID")
    .reset_index(drop=True)
)


assert raw_check.equals(harmonized_check), (
    "One or more historical source values changed during taxonomic harmonization."
)


print("Historical source-value preservation")
print("=" * 72)

print("Raw and harmonized source fields are identical: PASSED")

Historical source-value preservation
========================================================================
Raw and harmonized source fields are identical: PASSED

In [31]:
# =============================================================================
# 07A.5.11 — Add Taxonomic QC Flags to Harmonized Records
# =============================================================================

def append_qc_flag(existing_flag, new_flag):
    """
    Append a QC flag without removing existing flags.
    """

    existing_flag = (
        ""
        if pd.isna(existing_flag)
        else str(existing_flag).strip()
    )

    if not existing_flag:
        return new_flag

    flags = [
        flag.strip()
        for flag in existing_flag.split(";")
        if flag.strip()
    ]

    if new_flag not in flags:
        flags.append(new_flag)

    return ";".join(flags)


# -----------------------------------------------------------------------------
# Harmonized-name flags
# -----------------------------------------------------------------------------

harmonized_mask = structure_harmonized["Match_Status"].isin(
    [
        "NORMALIZED_CANONICAL_MATCH",
        "HARMONIZED_MATCH",
    ]
)

structure_harmonized.loc[
    harmonized_mask,
    "QC_Flag"
] = structure_harmonized.loc[
    harmonized_mask,
    "QC_Flag"
].apply(
    lambda x: append_qc_flag(
        x,
        "NAME_HARMONIZED",
    )
)


# -----------------------------------------------------------------------------
# Ambiguous taxa
# -----------------------------------------------------------------------------

ambiguous_mask = (
    structure_harmonized["Match_Status"]
    .eq("AMBIGUOUS")
)

structure_harmonized.loc[
    ambiguous_mask,
    "QC_Flag"
] = structure_harmonized.loc[
    ambiguous_mask,
    "QC_Flag"
].apply(
    lambda x: append_qc_flag(
        x,
        "AMBIGUOUS_TAXON",
    )
)


# -----------------------------------------------------------------------------
# Taxa outside canonical 127
# -----------------------------------------------------------------------------

outside_mask = (
    structure_harmonized["Match_Status"]
    .eq("NOT_IN_CANONICAL_127")
)

structure_harmonized.loc[
    outside_mask,
    "QC_Flag"
] = structure_harmonized.loc[
    outside_mask,
    "QC_Flag"
].apply(
    lambda x: append_qc_flag(
        x,
        "NOT_IN_CANONICAL_127",
    )
)


print("Taxonomic QC propagation")
print("=" * 72)

print(
    f"Records with harmonized names : "
    f"{harmonized_mask.sum()}"
)

print(
    f"Records with ambiguous taxa   : "
    f"{ambiguous_mask.sum()}"
)

print(
    f"Records outside canonical 127 : "
    f"{outside_mask.sum()}"
)


print("\nCurrent record-level QC flags")
print("-" * 72)

display(
    structure_harmonized["QC_Flag"]
    .replace("", "OK")
    .value_counts()
    .rename_axis("QC_Flag")
    .reset_index(name="Records")
)

Taxonomic QC propagation
========================================================================
Records with harmonized names : 31
Records with ambiguous taxa   : 3
Records outside canonical 127 : 2

Current record-level QC flags
------------------------------------------------------------------------

                   QC_Flag  Records
0                       OK      184
1          NAME_HARMONIZED       31
2          AMBIGUOUS_TAXON        3
3     NOT_IN_CANONICAL_127        2
4  DUPLICATE_SOURCE_RECORD        2

In [32]:
# =============================================================================
# 07A.5.12 — Export Harmonized Structural Dataset
# =============================================================================

structure_harmonized.to_csv(
    STRUCTURE_HARMONIZED_FILE,
    index=False,
    encoding="utf-8",
)


assert STRUCTURE_HARMONIZED_FILE.exists(), (
    "omo_tree_structure_harmonized.csv was not created."
)


print("Harmonized structural dataset exported successfully.")
print("=" * 72)

print(f"Output file : {STRUCTURE_HARMONIZED_FILE}")
print(f"Records     : {len(structure_harmonized)}")
print(f"Columns     : {structure_harmonized.shape[1]}")

Harmonized structural dataset exported successfully.
========================================================================
Output file : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\notebook_07a\omo_tree_structure_harmonized.csv
Records     : 222
Columns     : 21

## 07A.6 — Structural Measurement Validation

This section evaluates the internal mathematical consistency of the historical
Omo structural measurements.

The objectives are to investigate:

- whether reported totals and means imply coherent individual counts;
- whether DBH and height imply the same number of individuals;
- whether reported basal area is mathematically consistent with mean DBH;
- whether the source variable labelled `dbh` behaves as diameter or girth;
- likely measurement units; and
- records requiring structural QC flags.

Historical source values are never overwritten.

Separate numeric working columns are created solely for validation.

In [33]:
# =============================================================================
# 07A.6.1 — Create Numeric Working Copy
# =============================================================================

structure_validation = structure_harmonized.copy()

numeric_source_columns = [
    "Total_DBH",
    "Mean_DBH",
    "Total_Height",
    "Mean_Height",
    "Basal_Area",
    "BA_Percent",
]


print("Numeric structural validation layer")
print("=" * 72)

print(f"Records : {len(structure_validation)}")


# -----------------------------------------------------------------------------
# Helper: normalize numeric formatting for ANALYSIS ONLY
#
# This does NOT modify historical source values.
# It only removes whitespace occurring inside numeric strings.
#
# Example:
#     "805. 6" -> "805.6"
# -----------------------------------------------------------------------------

def normalize_numeric_string(value):

    if pd.isna(value):
        return value

    return "".join(
        str(value).split()
    )


# -----------------------------------------------------------------------------
# Convert historical source values to separate numeric working columns
# -----------------------------------------------------------------------------

for column in numeric_source_columns:

    numeric_column = f"{column}_Num"

    normalized_values = (
        structure_validation[column]
        .apply(normalize_numeric_string)
    )

    structure_validation[numeric_column] = pd.to_numeric(
        normalized_values,
        errors="coerce",
    )


# -----------------------------------------------------------------------------
# Check conversion failures
# -----------------------------------------------------------------------------

print("\nNumeric conversion failures")
print("-" * 72)

conversion_failure_counts = {}

for column in numeric_source_columns:

    numeric_column = f"{column}_Num"

    failures = int(
        structure_validation[numeric_column]
        .isna()
        .sum()
    )

    conversion_failure_counts[column] = failures

    print(
        f"{numeric_column:<25}: "
        f"{failures}"
    )


assert all(
    count == 0
    for count in conversion_failure_counts.values()
), (
    "One or more structural source values still cannot be "
    "converted to numeric."
)


# -----------------------------------------------------------------------------
# Explicitly document known source-format normalization
# -----------------------------------------------------------------------------

format_normalization_mask = (
    structure_validation[numeric_source_columns]
    .astype(str)
    .apply(
        lambda column:
        column.str.contains(
            r"\.\s+\d",
            regex=True,
            na=False,
        )
    )
    .any(axis=1)
)


format_normalization_records = (
    structure_validation.loc[
        format_normalization_mask,
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Source_Row",
            "Total_Height",
            "Total_Height_Num",
        ],
    ]
    .copy()
)


print("\nSource-format normalization records")
print("-" * 72)

print(
    f"Records requiring numeric-format normalization : "
    f"{len(format_normalization_records)}"
)

display(format_normalization_records)


# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------

assert len(format_normalization_records) == 1, (
    "Expected exactly one known source numeric-format artifact."
)

assert (
    format_normalization_records.iloc[0]["Raw_Record_ID"]
    == "OMO_STR_0198"
), (
    "Unexpected record identified for numeric-format normalization."
)

assert np.isclose(
    format_normalization_records.iloc[0]["Total_Height_Num"],
    805.6,
), (
    "The historical value '805. 6' was not interpreted as 805.6."
)


print("\nNumeric conversion: PASSED")
print(
    "Historical source values remain unchanged; "
    "format normalization applies only to numeric working columns."
)

Numeric structural validation layer
========================================================================
Records : 222

Numeric conversion failures
------------------------------------------------------------------------
Total_DBH_Num            : 0
Mean_DBH_Num             : 0
Total_Height_Num         : 0
Mean_Height_Num          : 0
Basal_Area_Num           : 0
BA_Percent_Num           : 0

Source-format normalization records
------------------------------------------------------------------------
Records requiring numeric-format normalization : 1

,Raw_Record_ID,Source_Species,Source_Table,Source_Row,Total_Height,Total_Height_Num
197,OMO_STR_0198,Ficus mucosa,4.8,208,805. 6,805.6

Numeric conversion: PASSED
Historical source values remain unchanged; format normalization applies only to numeric working columns.

In [34]:
# =============================================================================
# 07A.6.2 — Infer Individual Counts from Totals and Means
# =============================================================================

structure_validation["Inferred_N_DBH"] = (
    structure_validation["Total_DBH_Num"]
    / structure_validation["Mean_DBH_Num"]
)

structure_validation["Inferred_N_Height"] = (
    structure_validation["Total_Height_Num"]
    / structure_validation["Mean_Height_Num"]
)

structure_validation["Rounded_N_DBH"] = (
    structure_validation["Inferred_N_DBH"].round()
)

structure_validation["Rounded_N_Height"] = (
    structure_validation["Inferred_N_Height"].round()
)

structure_validation["DBH_N_Integer_Error"] = (
    structure_validation["Inferred_N_DBH"]
    - structure_validation["Rounded_N_DBH"]
).abs()

structure_validation["Height_N_Integer_Error"] = (
    structure_validation["Inferred_N_Height"]
    - structure_validation["Rounded_N_Height"]
).abs()


print("Inferred individual counts")
print("=" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Management_Zone",
            "Habitat",
            "Total_DBH_Num",
            "Mean_DBH_Num",
            "Inferred_N_DBH",
            "Total_Height_Num",
            "Mean_Height_Num",
            "Inferred_N_Height",
        ]
    ].head(15)
)

Inferred individual counts
========================================================================

,Raw_Record_ID,Source_Species,Management_Zone,Habitat,Total_DBH_Num,Mean_DBH_Num,Inferred_N_DBH,Total_Height_Num,Mean_Height_Num,Inferred_N_Height
0,OMO_STR_0001,Alstonia boonei,Core,Stream,181.7,36.34,5.000000,177.9,35.58,5.000000
1,OMO_STR_0002,Blighia sapida,Core,Stream,233.8,33.40,7.000000,246.4,35.20,7.000000
2,OMO_STR_0003,Bombax buonopozene,Core,Stream,126.1,31.50,4.003175,126.2,31.50,4.006349
3,OMO_STR_0004,Bosquei angolensis,Core,Stream,86.2,28.70,3.003484,34.3,28.10,1.220641
4,OMO_STR_0005,Celtis zenkeri,Core,Stream,235.8,29.40,8.020408,235.0,31.00,7.580645
5,OMO_STR_0006,Cleistopholis Patens,Core,Stream,248.5,31.00,8.016129,263.4,34.90,7.547278
6,OMO_STR_0007,Dialium guinensis,Core,Stream,66.2,33.10,2.000000,65.2,32.60,2.000000
7,OMO_STR_0008,Diospyros dendo,Core,Stream,653.2,21.50,30.381395,649.4,24.90,26.080321
8,OMO_STR_0009,Drypetes,Core,Stream,680.2,25.10,27.099602,696.8,25.80,27.007752
9,OMO_STR_0010,Ficus exasperata,Core,Stream,225.6,56.40,4.000000,217.6,54.40,4.000000
10,OMO_STR_0011,Grewia pubescens,Core,Stream,409.5,31.50,13.000000,425.0,32.60,13.036810
11,OMO_STR_0012,Homalium alymeri,Core,Stream,312.8,52.10,6.003839,30.7,50.45,0.608523
12,OMO_STR_0013,Lecaniodiscus cupanioides,Core,Stream,48.0,23.70,2.025316,52.0,26.00,2.000000
13,OMO_STR_0014,Margaritaria discoidea,Core,Stream,199.2,24.90,8.000000,210.8,26.40,7.984848
14,OMO_STR_0015,Musanga cecropoides,Core,Stream,350.0,26.90,13.011152,280.9,21.60,13.004630

In [35]:
# =============================================================================
# 07A.6.3 — Evaluate Total/Mean Internal Consistency
# =============================================================================

COUNT_INTEGER_TOLERANCE = 0.15


structure_validation["DBH_Count_Consistent"] = (
    structure_validation["DBH_N_Integer_Error"]
    <= COUNT_INTEGER_TOLERANCE
)

structure_validation["Height_Count_Consistent"] = (
    structure_validation["Height_N_Integer_Error"]
    <= COUNT_INTEGER_TOLERANCE
)

structure_validation["DBH_Height_Count_Agree"] = (
    structure_validation["Rounded_N_DBH"]
    == structure_validation["Rounded_N_Height"]
)

structure_validation["Total_Mean_Consistent"] = (
    structure_validation["DBH_Count_Consistent"]
    & structure_validation["Height_Count_Consistent"]
    & structure_validation["DBH_Height_Count_Agree"]
)


n_records = len(structure_validation)

print("Total/mean consistency assessment")
print("=" * 72)

print(
    f"DBH internally consistent       : "
    f"{structure_validation['DBH_Count_Consistent'].sum()} / {n_records}"
)

print(
    f"Height internally consistent    : "
    f"{structure_validation['Height_Count_Consistent'].sum()} / {n_records}"
)

print(
    f"DBH–height inferred counts agree: "
    f"{structure_validation['DBH_Height_Count_Agree'].sum()} / {n_records}"
)

print(
    f"Fully total/mean consistent     : "
    f"{structure_validation['Total_Mean_Consistent'].sum()} / {n_records}"
)

Total/mean consistency assessment
========================================================================
DBH internally consistent       : 215 / 222
Height internally consistent    : 209 / 222
DBH–height inferred counts agree: 207 / 222
Fully total/mean consistent     : 196 / 222

In [36]:
# =============================================================================
# 07A.6.4 — Inspect Total/Mean Inconsistencies
# =============================================================================

total_mean_inconsistent = (
    structure_validation.loc[
        ~structure_validation["Total_Mean_Consistent"]
    ]
    .copy()
)


print("Records with total/mean inconsistencies")
print("=" * 72)

print(
    f"Inconsistent records : "
    f"{len(total_mean_inconsistent)}"
)


display(
    total_mean_inconsistent[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Management_Zone",
            "Habitat",
            "Total_DBH_Num",
            "Mean_DBH_Num",
            "Inferred_N_DBH",
            "Rounded_N_DBH",
            "DBH_N_Integer_Error",
            "Total_Height_Num",
            "Mean_Height_Num",
            "Inferred_N_Height",
            "Rounded_N_Height",
            "Height_N_Integer_Error",
            "DBH_Count_Consistent",
            "Height_Count_Consistent",
            "DBH_Height_Count_Agree",
        ]
    ]
    .sort_values(
        [
            "Management_Zone",
            "Habitat",
            "Source_Species",
        ]
    )
)

Records with total/mean inconsistencies
========================================================================
Inconsistent records : 26

,Raw_Record_ID,Source_Species,Management_Zone,Habitat,Total_DBH_Num,Mean_DBH_Num,Inferred_N_DBH,Rounded_N_DBH,DBH_N_Integer_Error,Total_Height_Num,Mean_Height_Num,Inferred_N_Height,Rounded_N_Height,Height_N_Integer_Error,DBH_Count_Consistent,Height_Count_Consistent,DBH_Height_Count_Agree
81,OMO_STR_0082,Diallium guineense,Buffer,Major River,51.6,25.8,2.000000,2.0,0.000000,41.9,24.50,1.710204,2.0,2.897959e-01,True,False,True
84,OMO_STR_0085,Drypetes,Buffer,Major River,955.6,25.0,38.224000,38.0,0.224000,900.7,23.70,38.004219,38.0,4.219409e-03,False,True,True
86,OMO_STR_0087,Grewia pubescens,Buffer,Major River,310.3,22.0,14.104545,14.0,0.104545,303.6,20.20,15.029703,15.0,2.970297e-02,True,True,False
88,OMO_STR_0089,Lecaniodiscus cupanioides,Buffer,Major River,26.1,10.8,2.416667,2.0,0.416667,19.6,9.80,2.000000,2.0,0.000000e+00,False,True,True
90,OMO_STR_0091,Musanga cecropioides,Buffer,Major River,307.3,25.0,12.292000,12.0,0.292000,257.0,21.40,12.009346,12.0,9.345794e-03,False,True,True
104,OMO_STR_0105,Brachystegia eurycoma,Buffer,Stream,355.5,22.2,16.013514,16.0,0.013514,337.2,24.00,14.050000,14.0,5.000000e-02,True,True,False
113,OMO_STR_0114,Funtumia elastica,Buffer,Stream,172.3,24.6,7.004065,7.0,0.004065,169.6,28.20,6.014184,6.0,1.418440e-02,True,True,False
135,OMO_STR_0136,Annonidium manni,Buffer,Upland,235.7,23.2,10.159483,10.0,0.159483,336.3,24.00,14.012500,14.0,1.250000e-02,False,True,False
141,OMO_STR_0142,Diospyros dendo,Buffer,Upland,270.3,19.4,13.932990,14.0,0.067010,750.0,20.20,37.128713,37.0,1.287129e-01,True,True,False
144,OMO_STR_0145,Drypetes species,Buffer,Upland,1372.4,25.4,54.031496,54.0,0.031496,1382.1,25.50,54.200000,54.0,2.000000e-01,True,False,True
147,OMO_STR_0148,Holarrhena floribunda,Buffer,Upland,144.7,38.2,3.787958,4.0,0.212042,223.2,37.20,6.000000,6.0,8.881784e-16,False,True,False
157,OMO_STR_0158,Strombosia putulata,Buffer,Upland,521.5,27.4,19.032847,19.0,0.032847,528.8,30.60,17.281046,17.0,2.810458e-01,True,False,False
32,OMO_STR_0033,Drypetes,Core,Major River,595.0,13.8,43.115942,43.0,0.115942,95.3,22.10,4.312217,4.0,3.122172e-01,True,False,False
35,OMO_STR_0036,irvinga gabonensis,Core,Major River,118.3,23.6,5.012712,5.0,0.012712,13.8,22.70,0.607930,1.0,3.920705e-01,True,False,False
3,OMO_STR_0004,Bosquei angolensis,Core,Stream,86.2,28.7,3.003484,3.0,0.003484,34.3,28.10,1.220641,1.0,2.206406e-01,True,False,False
4,OMO_STR_0005,Celtis zenkeri,Core,Stream,235.8,29.4,8.020408,8.0,0.020408,235.0,31.00,7.580645,8.0,4.193548e-01,True,False,True
5,OMO_STR_0006,Cleistopholis Patens,Core,Stream,248.5,31.0,8.016129,8.0,0.016129,263.4,34.90,7.547278,8.0,4.527221e-01,True,False,True
7,OMO_STR_0008,Diospyros dendo,Core,Stream,653.2,21.5,30.381395,30.0,0.381395,649.4,24.90,26.080321,26.0,8.032129e-02,False,True,False
11,OMO_STR_0012,Homalium alymeri,Core,Stream,312.8,52.1,6.003839,6.0,0.003839,30.7,50.45,0.608523,1.0,3.914767e-01,True,False,False
55,OMO_STR_0056,Diospyrous dendo,Core,Upland,1785.0,20.5,87.073171,87.0,0.073171,1874.9,21.50,87.204651,87.0,2.046512e-01,True,False,True
188,OMO_STR_0189,Trichilia monadelpha,Transition,Major River,104.3,30.8,3.386364,3.0,0.386364,371.4,28.50,13.031579,13.0,3.157895e-02,False,True,False
190,OMO_STR_0191,Albizia zygia,Transition,Stream,44.0,22.0,2.000000,2.0,0.000000,41.9,24.50,1.710204,2.0,2.897959e-01,True,False,True
192,OMO_STR_0193,Anthocliesta vogelii,Transition,Stream,1249.7,24.0,52.070833,52.0,0.070833,1314.8,25.20,52.174603,52.0,1.746032e-01,True,False,True
195,OMO_STR_0196,Cleistoformis patens,Transition,Stream,1134.9,23.1,49.129870,49.0,0.129870,1185.1,24.10,49.174274,49.0,1.742739e-01,True,False,True
196,OMO_STR_0197,Elaeis guinenesis,Transition,Stream,895.0,68.4,13.084795,13.0,0.084795,672.3,48.00,14.006250,14.0,6.250000e-03,True,True,False
197,OMO_STR_0198,Ficus mucosa,Transition,Stream,726.4,31.7,22.914826,23.0,0.085174,805.6,33.50,24.047761,24.0,4.776119e-02,True,True,False

In [37]:
# =============================================================================
# 07A.6.5 — Classify Total/Mean Consistency Failures
# =============================================================================

def classify_count_consistency(row):
    """
    Classify the reason a structural record fails the
    total/mean consistency assessment.
    """

    failures = []

    if not row["DBH_Count_Consistent"]:
        failures.append("DBH_NONINTEGER")

    if not row["Height_Count_Consistent"]:
        failures.append("HEIGHT_NONINTEGER")

    if not row["DBH_Height_Count_Agree"]:
        failures.append("DBH_HEIGHT_COUNT_DISAGREE")

    if not failures:
        return "CONSISTENT"

    return ";".join(failures)


structure_validation["Count_Consistency_Class"] = (
    structure_validation.apply(
        classify_count_consistency,
        axis=1,
    )
)


# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

consistency_class_summary = (
    structure_validation["Count_Consistency_Class"]
    .value_counts()
    .rename_axis("Consistency_Class")
    .reset_index(name="Records")
)


print("Total/mean inconsistency classification")
print("=" * 72)

display(consistency_class_summary)


# -----------------------------------------------------------------------------
# Inspect the 26 problematic records in diagnostic order
# -----------------------------------------------------------------------------

diagnostic_columns = [
    "Raw_Record_ID",
    "Source_Species",
    "Source_Table",
    "Management_Zone",
    "Habitat",
    "Total_DBH_Num",
    "Mean_DBH_Num",
    "Inferred_N_DBH",
    "DBH_N_Integer_Error",
    "Total_Height_Num",
    "Mean_Height_Num",
    "Inferred_N_Height",
    "Height_N_Integer_Error",
    "Rounded_N_DBH",
    "Rounded_N_Height",
    "Count_Consistency_Class",
]


inconsistency_diagnostics = (
    structure_validation.loc[
        ~structure_validation["Total_Mean_Consistent"],
        diagnostic_columns,
    ]
    .copy()
    .sort_values(
        [
            "Count_Consistency_Class",
            "Source_Table",
            "Source_Species",
        ]
    )
    .reset_index(drop=True)
)


print(
    f"\nRecords requiring inspection: "
    f"{len(inconsistency_diagnostics)}"
)

display(inconsistency_diagnostics)

Total/mean inconsistency classification
========================================================================

                             Consistency_Class  Records
0                                   CONSISTENT      196
1                            HEIGHT_NONINTEGER        8
2                    DBH_HEIGHT_COUNT_DISAGREE        6
3  HEIGHT_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE        5
4     DBH_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE        4
5                               DBH_NONINTEGER        3

Records requiring inspection: 26

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Total_DBH_Num,Mean_DBH_Num,Inferred_N_DBH,DBH_N_Integer_Error,Total_Height_Num,Mean_Height_Num,Inferred_N_Height,Height_N_Integer_Error,Rounded_N_DBH,Rounded_N_Height,Count_Consistency_Class
0,OMO_STR_0087,Grewia pubescens,4.4,Buffer,Major River,310.3,22.0,14.104545,0.104545,303.6,20.20,15.029703,2.970297e-02,14.0,15.0,DBH_HEIGHT_COUNT_DISAGREE
1,OMO_STR_0105,Brachystegia eurycoma,4.5,Buffer,Stream,355.5,22.2,16.013514,0.013514,337.2,24.00,14.050000,5.000000e-02,16.0,14.0,DBH_HEIGHT_COUNT_DISAGREE
2,OMO_STR_0114,Funtumia elastica,4.5,Buffer,Stream,172.3,24.6,7.004065,0.004065,169.6,28.20,6.014184,1.418440e-02,7.0,6.0,DBH_HEIGHT_COUNT_DISAGREE
3,OMO_STR_0142,Diospyros dendo,4.6,Buffer,Upland,270.3,19.4,13.932990,0.067010,750.0,20.20,37.128713,1.287129e-01,14.0,37.0,DBH_HEIGHT_COUNT_DISAGREE
4,OMO_STR_0197,Elaeis guinenesis,4.8,Transition,Stream,895.0,68.4,13.084795,0.084795,672.3,48.00,14.006250,6.250000e-03,13.0,14.0,DBH_HEIGHT_COUNT_DISAGREE
5,OMO_STR_0198,Ficus mucosa,4.8,Transition,Stream,726.4,31.7,22.914826,0.085174,805.6,33.50,24.047761,4.776119e-02,23.0,24.0,DBH_HEIGHT_COUNT_DISAGREE
6,OMO_STR_0085,Drypetes,4.4,Buffer,Major River,955.6,25.0,38.224000,0.224000,900.7,23.70,38.004219,4.219409e-03,38.0,38.0,DBH_NONINTEGER
7,OMO_STR_0089,Lecaniodiscus cupanioides,4.4,Buffer,Major River,26.1,10.8,2.416667,0.416667,19.6,9.80,2.000000,0.000000e+00,2.0,2.0,DBH_NONINTEGER
8,OMO_STR_0091,Musanga cecropioides,4.4,Buffer,Major River,307.3,25.0,12.292000,0.292000,257.0,21.40,12.009346,9.345794e-03,12.0,12.0,DBH_NONINTEGER
9,OMO_STR_0008,Diospyros dendo,4.1,Core,Stream,653.2,21.5,30.381395,0.381395,649.4,24.90,26.080321,8.032129e-02,30.0,26.0,DBH_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
10,OMO_STR_0136,Annonidium manni,4.6,Buffer,Upland,235.7,23.2,10.159483,0.159483,336.3,24.00,14.012500,1.250000e-02,10.0,14.0,DBH_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
11,OMO_STR_0148,Holarrhena floribunda,4.6,Buffer,Upland,144.7,38.2,3.787958,0.212042,223.2,37.20,6.000000,8.881784e-16,4.0,6.0,DBH_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
12,OMO_STR_0189,Trichilia monadelpha,4.7,Transition,Major River,104.3,30.8,3.386364,0.386364,371.4,28.50,13.031579,3.157895e-02,3.0,13.0,DBH_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
13,OMO_STR_0005,Celtis zenkeri,4.1,Core,Stream,235.8,29.4,8.020408,0.020408,235.0,31.00,7.580645,4.193548e-01,8.0,8.0,HEIGHT_NONINTEGER
14,OMO_STR_0006,Cleistopholis Patens,4.1,Core,Stream,248.5,31.0,8.016129,0.016129,263.4,34.90,7.547278,4.527221e-01,8.0,8.0,HEIGHT_NONINTEGER
15,OMO_STR_0056,Diospyrous dendo,4.3,Core,Upland,1785.0,20.5,87.073171,0.073171,1874.9,21.50,87.204651,2.046512e-01,87.0,87.0,HEIGHT_NONINTEGER
16,OMO_STR_0082,Diallium guineense,4.4,Buffer,Major River,51.6,25.8,2.000000,0.000000,41.9,24.50,1.710204,2.897959e-01,2.0,2.0,HEIGHT_NONINTEGER
17,OMO_STR_0145,Drypetes species,4.6,Buffer,Upland,1372.4,25.4,54.031496,0.031496,1382.1,25.50,54.200000,2.000000e-01,54.0,54.0,HEIGHT_NONINTEGER
18,OMO_STR_0191,Albizia zygia,4.8,Transition,Stream,44.0,22.0,2.000000,0.000000,41.9,24.50,1.710204,2.897959e-01,2.0,2.0,HEIGHT_NONINTEGER
19,OMO_STR_0193,Anthocliesta vogelii,4.8,Transition,Stream,1249.7,24.0,52.070833,0.070833,1314.8,25.20,52.174603,1.746032e-01,52.0,52.0,HEIGHT_NONINTEGER
20,OMO_STR_0196,Cleistoformis patens,4.8,Transition,Stream,1134.9,23.1,49.129870,0.129870,1185.1,24.10,49.174274,1.742739e-01,49.0,49.0,HEIGHT_NONINTEGER
21,OMO_STR_0004,Bosquei angolensis,4.1,Core,Stream,86.2,28.7,3.003484,0.003484,34.3,28.10,1.220641,2.206406e-01,3.0,1.0,HEIGHT_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
22,OMO_STR_0012,Homalium alymeri,4.1,Core,Stream,312.8,52.1,6.003839,0.003839,30.7,50.45,0.608523,3.914767e-01,6.0,1.0,HEIGHT_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
23,OMO_STR_0033,Drypetes,4.2,Core,Major River,595.0,13.8,43.115942,0.115942,95.3,22.10,4.312217,3.122172e-01,43.0,4.0,HEIGHT_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
24,OMO_STR_0036,irvinga gabonensis,4.2,Core,Major River,118.3,23.6,5.012712,0.012712,13.8,22.70,0.607930,3.920705e-01,5.0,1.0,HEIGHT_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE
25,OMO_STR_0158,Strombosia putulata,4.6,Buffer,Upland,521.5,27.4,19.032847,0.032847,528.8,30.60,17.281046,2.810458e-01,19.0,17.0,HEIGHT_NONINTEGER;DBH_HEIGHT_COUNT_DISAGREE

In [38]:
# =============================================================================
# 07A.6.6 — Quantify Magnitude of Count Inconsistencies
# =============================================================================

print("Magnitude of inferred-count inconsistencies")
print("=" * 72)


print("\nDBH integer-error distribution")
print("-" * 72)

display(
    structure_validation["DBH_N_Integer_Error"]
    .describe()
    .to_frame("DBH_N_Integer_Error")
)


print("\nHeight integer-error distribution")
print("-" * 72)

display(
    structure_validation["Height_N_Integer_Error"]
    .describe()
    .to_frame("Height_N_Integer_Error")
)


# -----------------------------------------------------------------------------
# Largest discrepancies
# -----------------------------------------------------------------------------

print("\nLargest DBH count discrepancies")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Total_DBH_Num",
            "Mean_DBH_Num",
            "Inferred_N_DBH",
            "Rounded_N_DBH",
            "DBH_N_Integer_Error",
        ]
    ]
    .sort_values(
        "DBH_N_Integer_Error",
        ascending=False,
    )
    .head(10)
)


print("\nLargest height count discrepancies")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Total_Height_Num",
            "Mean_Height_Num",
            "Inferred_N_Height",
            "Rounded_N_Height",
            "Height_N_Integer_Error",
        ]
    ]
    .sort_values(
        "Height_N_Integer_Error",
        ascending=False,
    )
    .head(10)
)

Magnitude of inferred-count inconsistencies
========================================================================

DBH integer-error distribution
------------------------------------------------------------------------

       DBH_N_Integer_Error
count           222.000000
mean              0.022026
std               0.057510
min               0.000000
25%               0.000000
50%               0.005495
75%               0.015083
max               0.416667

Height integer-error distribution
------------------------------------------------------------------------

       Height_N_Integer_Error
count              222.000000
mean                 0.028978
std                  0.072859
min                  0.000000
25%                  0.000000
50%                  0.006623
75%                  0.015965
max                  0.452722

Largest DBH count discrepancies
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Total_DBH_Num,Mean_DBH_Num,Inferred_N_DBH,Rounded_N_DBH,DBH_N_Integer_Error
88,OMO_STR_0089,Lecaniodiscus cupanioides,4.4,26.1,10.8,2.416667,2.0,0.416667
188,OMO_STR_0189,Trichilia monadelpha,4.7,104.3,30.8,3.386364,3.0,0.386364
7,OMO_STR_0008,Diospyros dendo,4.1,653.2,21.5,30.381395,30.0,0.381395
90,OMO_STR_0091,Musanga cecropioides,4.4,307.3,25.0,12.292000,12.0,0.292000
84,OMO_STR_0085,Drypetes,4.4,955.6,25.0,38.224000,38.0,0.224000
147,OMO_STR_0148,Holarrhena floribunda,4.6,144.7,38.2,3.787958,4.0,0.212042
135,OMO_STR_0136,Annonidium manni,4.6,235.7,23.2,10.159483,10.0,0.159483
56,OMO_STR_0057,Diospyros mespiliformis,4.3,76.2,24.2,3.148760,3.0,0.148760
195,OMO_STR_0196,Cleistoformis patens,4.8,1134.9,23.1,49.129870,49.0,0.129870
219,OMO_STR_0220,Theobroma cacao,4.9,587.9,18.3,32.125683,32.0,0.125683

Largest height count discrepancies
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Total_Height_Num,Mean_Height_Num,Inferred_N_Height,Rounded_N_Height,Height_N_Integer_Error
5,OMO_STR_0006,Cleistopholis Patens,4.1,263.4,34.90,7.547278,8.0,0.452722
4,OMO_STR_0005,Celtis zenkeri,4.1,235.0,31.00,7.580645,8.0,0.419355
35,OMO_STR_0036,irvinga gabonensis,4.2,13.8,22.70,0.607930,1.0,0.392070
11,OMO_STR_0012,Homalium alymeri,4.1,30.7,50.45,0.608523,1.0,0.391477
32,OMO_STR_0033,Drypetes,4.2,95.3,22.10,4.312217,4.0,0.312217
81,OMO_STR_0082,Diallium guineense,4.4,41.9,24.50,1.710204,2.0,0.289796
190,OMO_STR_0191,Albizia zygia,4.8,41.9,24.50,1.710204,2.0,0.289796
157,OMO_STR_0158,Strombosia putulata,4.6,528.8,30.60,17.281046,17.0,0.281046
3,OMO_STR_0004,Bosquei angolensis,4.1,34.3,28.10,1.220641,1.0,0.220641
55,OMO_STR_0056,Diospyrous dendo,4.3,1874.9,21.50,87.204651,87.0,0.204651

In [39]:
# =============================================================================
# 07A.6.7 — Assign Total/Mean Consistency QC Flag
# =============================================================================

total_mean_flag_mask = (
    ~structure_validation["Total_Mean_Consistent"]
)


structure_validation.loc[
    total_mean_flag_mask,
    "QC_Flag"
] = structure_validation.loc[
    total_mean_flag_mask,
    "QC_Flag"
].apply(
    lambda x: append_qc_flag(
        x,
        "TOTAL_MEAN_INCONSISTENT",
    )
)


print("Total/mean consistency QC")
print("=" * 72)

print(
    f"Records assessed                    : "
    f"{len(structure_validation)}"
)

print(
    f"Fully internally consistent         : "
    f"{structure_validation['Total_Mean_Consistent'].sum()}"
)

print(
    f"TOTAL_MEAN_INCONSISTENT records     : "
    f"{total_mean_flag_mask.sum()}"
)


assert total_mean_flag_mask.sum() == 26, (
    "Expected exactly 26 records failing the current "
    "total/mean consistency criteria."
)


print("\nTotal/mean QC assignment: PASSED")

Total/mean consistency QC
========================================================================
Records assessed                    : 222
Fully internally consistent         : 196
TOTAL_MEAN_INCONSISTENT records     : 26

Total/mean QC assignment: PASSED

In [40]:
# =============================================================================
# 07A.6.8 — Summarize Inferred Individual Counts
# =============================================================================

# Use only records for which DBH and height both support the same
# integer count.

reliable_count_mask = (
    structure_validation["Total_Mean_Consistent"]
)


reliable_counts = (
    structure_validation.loc[
        reliable_count_mask,
        [
            "Raw_Record_ID",
            "Source_Species",
            "Management_Zone",
            "Habitat",
            "Rounded_N_DBH",
        ],
    ]
    .copy()
    .rename(
        columns={
            "Rounded_N_DBH": "Inferred_N"
        }
    )
)


print("Reliable inferred individual-count evidence")
print("=" * 72)

print(
    f"Records with reliable inferred N : "
    f"{len(reliable_counts)}"
)

print(
    f"Minimum inferred N               : "
    f"{int(reliable_counts['Inferred_N'].min())}"
)

print(
    f"Maximum inferred N               : "
    f"{int(reliable_counts['Inferred_N'].max())}"
)

print(
    f"Median inferred N                : "
    f"{reliable_counts['Inferred_N'].median():.1f}"
)


print("\nInferred-N distribution")
print("-" * 72)

display(
    reliable_counts["Inferred_N"]
    .value_counts()
    .sort_index()
    .rename_axis("Inferred_N")
    .reset_index(name="Species_Context_Records")
)

Reliable inferred individual-count evidence
========================================================================
Records with reliable inferred N : 196
Minimum inferred N               : 1
Maximum inferred N               : 58
Median inferred N                : 4.0

Inferred-N distribution
------------------------------------------------------------------------

    Inferred_N  Species_Context_Records
0          1.0                       16
1          2.0                       25
2          3.0                       40
3          4.0                       23
4          5.0                       21
5          6.0                       11
6          7.0                       16
7          8.0                        6
8          9.0                        6
9         10.0                        4
10        11.0                        7
11        12.0                        3
12        13.0                        3
13        14.0                        2
14        15.0                        1
15        17.0                        1
16        18.0                        1
17        22.0                        1
18        25.0                        2
19        26.0                        1
20        27.0                        2
21        30.0                        1
22        32.0                        1
23        40.0                        1
24        58.0                        1

### 07A.6.9 — Basal-Area Formula and DBH Interpretation

The historical tables label the structural variable as `dbh`, while the
surrounding source text refers to tree girth. The basal-area column is labelled
`BA m2`.

Rather than assuming these definitions or units, this section tests whether
the reported basal-area values are mathematically consistent with the reported
mean DBH values.

For a circular stem of diameter \(d\):

\[
BA = \frac{\pi d^2}{4}
\]

The reported basal area is compared directly with the value predicted from
`Mean_DBH`. This test is initially unit-neutral: it evaluates numerical
consistency before assigning physical units.

In [41]:
# =============================================================================
# 07A.6.9 — Test Basal Area Against Mean DBH
# =============================================================================

import numpy as np


# -----------------------------------------------------------------------------
# Predicted basal area from reported Mean_DBH
# -----------------------------------------------------------------------------

structure_validation["BA_From_Mean_DBH"] = (
    np.pi
    * structure_validation["Mean_DBH_Num"] ** 2
    / 4
)


# -----------------------------------------------------------------------------
# Absolute and relative discrepancies
# -----------------------------------------------------------------------------

structure_validation["BA_Absolute_Error"] = (
    structure_validation["Basal_Area_Num"]
    - structure_validation["BA_From_Mean_DBH"]
).abs()


structure_validation["BA_Relative_Error"] = (
    structure_validation["BA_Absolute_Error"]
    / structure_validation["Basal_Area_Num"]
)


structure_validation["BA_Percent_Error"] = (
    structure_validation["BA_Relative_Error"]
    * 100
)


# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

print("Basal-area formula validation")
print("=" * 72)

print("\nReported BA")
print("-" * 72)

display(
    structure_validation["Basal_Area_Num"]
    .describe()
    .to_frame("Reported_BA")
)


print("\nPredicted BA from Mean DBH")
print("-" * 72)

display(
    structure_validation["BA_From_Mean_DBH"]
    .describe()
    .to_frame("Predicted_BA")
)


print("\nPercentage-error distribution")
print("-" * 72)

display(
    structure_validation["BA_Percent_Error"]
    .describe()
    .to_frame("BA_Percent_Error")
)

Basal-area formula validation
========================================================================

Reported BA
------------------------------------------------------------------------

        Reported_BA
count    222.000000
mean     986.944595
std     2828.602189
min       78.570000
25%      334.200000
50%      551.700000
75%      894.950000
max    40737.000000

Predicted BA from Mean DBH
------------------------------------------------------------------------

       Predicted_BA
count    222.000000
mean     986.641701
std     2827.482481
min       78.539816
25%      334.102488
50%      551.545860
75%      894.623486
max    40720.766343

Percentage-error distribution
------------------------------------------------------------------------

       BA_Percent_Error
count        222.000000
mean           0.030191
std            0.010415
min            0.000262
25%            0.025128
50%            0.032871
75%            0.038882
max            0.042727

In [42]:
# =============================================================================
# 07A.6.10 — Evaluate Basal-Area Mathematical Agreement
# =============================================================================

ba_correlation = (
    structure_validation[
        [
            "Basal_Area_Num",
            "BA_From_Mean_DBH",
        ]
    ]
    .corr()
    .iloc[0, 1]
)


ba_ratio = (
    structure_validation["Basal_Area_Num"]
    / structure_validation["BA_From_Mean_DBH"]
)


structure_validation["BA_Reported_Predicted_Ratio"] = ba_ratio


print("Basal-area mathematical agreement")
print("=" * 72)

print(
    f"Correlation reported vs predicted BA : "
    f"{ba_correlation:.6f}"
)


print("\nReported / predicted BA ratio")
print("-" * 72)

display(
    ba_ratio
    .describe()
    .to_frame("Reported_Predicted_Ratio")
)

Basal-area mathematical agreement
========================================================================
Correlation reported vs predicted BA : 1.000000

Reported / predicted BA ratio
------------------------------------------------------------------------

       Reported_Predicted_Ratio
count                222.000000
mean                   1.000281
std                    0.000152
min                    0.999620
25%                    1.000247
50%                    1.000328
75%                    1.000389
max                    1.000427

In [43]:
# =============================================================================
# 07A.6.11 — Classify Basal-Area Formula Agreement
# =============================================================================

BA_RELATIVE_TOLERANCE = 0.05


structure_validation["BA_Formula_Consistent"] = (
    structure_validation["BA_Relative_Error"]
    <= BA_RELATIVE_TOLERANCE
)


n_ba_consistent = int(
    structure_validation["BA_Formula_Consistent"]
    .sum()
)

n_ba_inconsistent = int(
    (~structure_validation["BA_Formula_Consistent"])
    .sum()
)


print("Basal-area formula consistency")
print("=" * 72)

print(
    f"Within 5% of π × Mean_DBH² / 4 : "
    f"{n_ba_consistent} / {len(structure_validation)}"
)

print(
    f"Outside 5% tolerance           : "
    f"{n_ba_inconsistent} / {len(structure_validation)}"
)


# -----------------------------------------------------------------------------
# Largest discrepancies
# -----------------------------------------------------------------------------

print("\nLargest basal-area discrepancies")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Mean_DBH_Num",
            "Basal_Area_Num",
            "BA_From_Mean_DBH",
            "BA_Reported_Predicted_Ratio",
            "BA_Percent_Error",
        ]
    ]
    .sort_values(
        "BA_Percent_Error",
        ascending=False,
    )
    .head(20)
)

Basal-area formula consistency
========================================================================
Within 5% of π × Mean_DBH² / 4 : 222 / 222
Outside 5% tolerance           : 0 / 222

Largest basal-area discrepancies
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Mean_DBH_Num,Basal_Area_Num,BA_From_Mean_DBH,BA_Reported_Predicted_Ratio,BA_Percent_Error
54,OMO_STR_0055,Cola species,4.3,13.5,143.20,143.138815,1.000427,0.042727
182,OMO_STR_0183,Rauvolvia vomitoria,4.7,13.5,143.20,143.138815,1.000427,0.042727
162,OMO_STR_0163,Aningeria robusta,4.7,13.5,143.20,143.138815,1.000427,0.042727
11,OMO_STR_0012,Homalium alymeri,4.1,52.1,2132.80,2131.892629,1.000426,0.042544
23,OMO_STR_0024,Strombosia pustulata,4.1,42.6,1425.90,1425.309171,1.000415,0.041436
55,OMO_STR_0056,Diospyrous dendo,4.3,20.5,330.20,330.063578,1.000413,0.041315
7,OMO_STR_0008,Diospyros dendo,4.1,21.5,363.20,363.050301,1.000412,0.041217
220,OMO_STR_0221,Trema orientalis,4.9,21.5,363.20,363.050301,1.000412,0.041217
215,OMO_STR_0216,Ficus mucosa,4.9,48.3,1833.00,1832.247521,1.000411,0.041052
3,OMO_STR_0004,Bosquei angolensis,4.1,28.7,647.19,646.924613,1.000410,0.041006
2,OMO_STR_0003,Bombax buonopozene,4.1,31.5,779.63,779.311328,1.000409,0.040875
10,OMO_STR_0011,Grewia pubescens,4.1,31.5,779.63,779.311328,1.000409,0.040875
18,OMO_STR_0019,Picralima nitida,4.1,55.3,2402.80,2401.818270,1.000409,0.040858
45,OMO_STR_0046,Scotellia coricea,4.2,27.5,594.20,593.957361,1.000409,0.040835
68,OMO_STR_0069,Ricinodendron heudeloti,4.3,27.5,594.20,593.957361,1.000409,0.040835
80,OMO_STR_0081,Cleistopholis patens,4.4,27.5,594.20,593.957361,1.000409,0.040835
100,OMO_STR_0101,Albizia zygia,4.5,28.5,638.20,637.939658,1.000408,0.040793
20,OMO_STR_0021,Ricinodendron heudeloti,4.1,102.2,8206.70,8203.358153,1.000407,0.040721
12,OMO_STR_0013,Lecaniodiscus cupanioides,4.1,23.7,441.33,441.150294,1.000407,0.040719
8,OMO_STR_0009,Drypetes,4.1,25.1,495.01,494.808697,1.000407,0.040666

In [44]:
# =============================================================================
# 07A.6.12 — Formalize Basal-Area and DBH Interpretation
# =============================================================================

# Very strict diagnostic threshold because the observed agreement
# is substantially stronger than the initial 5% screening tolerance.
BA_STRICT_RELATIVE_TOLERANCE = 0.001   # 0.1%


structure_validation["BA_Strictly_Consistent"] = (
    structure_validation["BA_Relative_Error"]
    <= BA_STRICT_RELATIVE_TOLERANCE
)


n_strict_consistent = int(
    structure_validation["BA_Strictly_Consistent"].sum()
)


print("Structural measurement interpretation")
print("=" * 72)

print(
    f"BA records within 0.1% of π × Mean_DBH² / 4 : "
    f"{n_strict_consistent} / {len(structure_validation)}"
)

print(
    f"Maximum observed BA percentage error          : "
    f"{structure_validation['BA_Percent_Error'].max():.4f}%"
)

print(
    f"Median reported/predicted BA ratio            : "
    f"{structure_validation['BA_Reported_Predicted_Ratio'].median():.6f}"
)


assert n_strict_consistent == len(structure_validation), (
    "Not all basal-area records satisfy the strict mathematical "
    "consistency criterion."
)


# -----------------------------------------------------------------------------
# Dataset-level interpretation
# -----------------------------------------------------------------------------

DBH_MEASUREMENT_INTERPRETATION = (
    "Diameter-based measurement"
)

DBH_UNIT_STATUS = (
    "Likely centimetres; strongly supported by magnitude and BA relationship, "
    "but not independently documented in the historical source."
)

BASAL_AREA_INTERPRETATION = (
    "Derived from Mean_DBH using pi*d^2/4; represents area associated "
    "with mean diameter rather than aggregate species-context basal area."
)

BASAL_AREA_UNIT_STATUS = (
    "Reported source heading states m2, but numerical values behave as "
    "squared DBH units. If DBH is centimetres, reported BA values are cm2."
)

BASAL_AREA_VALIDATION_STATUS = (
    "Mathematically validated for all 222 records."
)


print("\nInterpretation")
print("-" * 72)

print(f"DBH interpretation : {DBH_MEASUREMENT_INTERPRETATION}")
print(f"DBH unit status    : {DBH_UNIT_STATUS}")
print(f"BA interpretation  : {BASAL_AREA_INTERPRETATION}")
print(f"BA unit status     : {BASAL_AREA_UNIT_STATUS}")
print(f"BA validation      : {BASAL_AREA_VALIDATION_STATUS}")

print("\nBasal-area structural interpretation: PASSED")

Structural measurement interpretation
========================================================================
BA records within 0.1% of π × Mean_DBH² / 4 : 222 / 222
Maximum observed BA percentage error          : 0.0427%
Median reported/predicted BA ratio            : 1.000328

Interpretation
------------------------------------------------------------------------
DBH interpretation : Diameter-based measurement
DBH unit status    : Likely centimetres; strongly supported by magnitude and BA relationship, but not independently documented in the historical source.
BA interpretation  : Derived from Mean_DBH using pi*d^2/4; represents area associated with mean diameter rather than aggregate species-context basal area.
BA unit status     : Reported source heading states m2, but numerical values behave as squared DBH units. If DBH is centimetres, reported BA values are cm2.
BA validation      : Mathematically validated for all 222 records.

Basal-area structural interpretation: PASSED

### 07A.6.13 — Height Range and Unit Plausibility Assessment

The historical source reports total and mean tree height but does not provide
sufficient independent metadata to establish the measurement unit with
certainty.

This section therefore evaluates:

- the distribution of reported mean heights;
- minimum and maximum values;
- unusually low or high observations;
- consistency across management zones and habitats; and
- whether the observed magnitudes are biologically plausible if interpreted
  as metres.

This is a plausibility assessment rather than a unit conversion. Historical
height values remain unchanged.

In [45]:
# =============================================================================
# 07A.6.13 — Height Range and Unit Plausibility Assessment
# =============================================================================

height_values = structure_validation["Mean_Height_Num"]


print("Mean-height plausibility assessment")
print("=" * 72)

print("\nOverall mean-height distribution")
print("-" * 72)

display(
    height_values
    .describe(
        percentiles=[
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
        ]
    )
    .to_frame("Mean_Height")
)


# -----------------------------------------------------------------------------
# Lowest reported mean heights
# -----------------------------------------------------------------------------

print("\nLowest reported mean heights")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Management_Zone",
            "Habitat",
            "Total_Height_Num",
            "Mean_Height_Num",
            "Inferred_N_Height",
            "Total_Mean_Consistent",
        ]
    ]
    .sort_values("Mean_Height_Num")
    .head(15)
)


# -----------------------------------------------------------------------------
# Highest reported mean heights
# -----------------------------------------------------------------------------

print("\nHighest reported mean heights")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Management_Zone",
            "Habitat",
            "Total_Height_Num",
            "Mean_Height_Num",
            "Inferred_N_Height",
            "Total_Mean_Consistent",
        ]
    ]
    .sort_values(
        "Mean_Height_Num",
        ascending=False,
    )
    .head(15)
)


# -----------------------------------------------------------------------------
# Height distribution by management zone
# -----------------------------------------------------------------------------

height_by_zone = (
    structure_validation
    .groupby(
        "Management_Zone",
        observed=True,
    )["Mean_Height_Num"]
    .agg(
        Records="count",
        Minimum="min",
        Median="median",
        Mean="mean",
        Maximum="max",
    )
    .reset_index()
)


print("\nMean height by management zone")
print("-" * 72)

display(height_by_zone)


# -----------------------------------------------------------------------------
# Height distribution by habitat
# -----------------------------------------------------------------------------

height_by_habitat = (
    structure_validation
    .groupby(
        "Habitat",
        observed=True,
    )["Mean_Height_Num"]
    .agg(
        Records="count",
        Minimum="min",
        Median="median",
        Mean="mean",
        Maximum="max",
    )
    .reset_index()
)


print("\nMean height by habitat")
print("-" * 72)

display(height_by_habitat)

Mean-height plausibility assessment
========================================================================

Overall mean-height distribution
------------------------------------------------------------------------

       Mean_Height
count   222.000000
mean     29.102162
std      11.842427
min       9.800000
1%       12.463000
5%       14.110000
10%      15.910000
25%      21.170000
50%      26.950000
75%      34.175000
90%      44.680000
95%      54.895000
99%      65.639000
max      82.100000

Lowest reported mean heights
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Total_Height_Num,Mean_Height_Num,Inferred_N_Height,Total_Mean_Consistent
88,OMO_STR_0089,Lecaniodiscus cupanioides,4.4,Buffer,Major River,19.6,9.8,2.000000,False
176,OMO_STR_0177,Lonchocarpus cyanescens,4.7,Transition,Major River,10.4,10.4,1.000000,True
179,OMO_STR_0180,Musanga cecropoides,4.7,Transition,Major River,49.9,12.4,4.024194,True
103,OMO_STR_0104,Anthocliesta vogeli,4.5,Buffer,Stream,25.4,12.7,2.000000,True
182,OMO_STR_0183,Rauvolvia vomitoria,4.7,Transition,Major River,63.8,12.7,5.023622,True
156,OMO_STR_0157,Sterculia rhinopetala,4.6,Buffer,Upland,77.9,12.9,6.038760,True
200,OMO_STR_0201,Macranga bateri,4.8,Transition,Stream,26.0,13.0,2.000000,True
203,OMO_STR_0204,Theobroma cacao,4.8,Transition,Stream,40.5,13.5,3.000000,True
125,OMO_STR_0126,Pterocarpus osun,4.5,Buffer,Stream,13.8,13.8,1.000000,True
162,OMO_STR_0163,Aningeria robusta,4.7,Transition,Major River,27.9,13.9,2.007194,True
217,OMO_STR_0218,Raulvolfia vomitoria,4.9,Transition,Upland,41.9,13.9,3.014388,True
54,OMO_STR_0055,Cola species,4.3,Core,Upland,42.4,14.1,3.007092,True
101,OMO_STR_0102,Alstonia boonei,4.5,Buffer,Stream,71.7,14.3,5.013986,True
174,OMO_STR_0175,Lonchocarpus cayensis,4.7,Transition,Major River,14.3,14.3,1.000000,True
173,OMO_STR_0174,Holarrhena floribunda,4.7,Transition,Major River,28.6,14.3,2.000000,True

Highest reported mean heights
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Total_Height_Num,Mean_Height_Num,Inferred_N_Height,Total_Mean_Consistent
20,OMO_STR_0021,Ricinodendron heudeloti,4.1,Core,Stream,410.5,82.1,5.000000,True
19,OMO_STR_0020,Pycnanthus angolensis,4.1,Core,Stream,268.0,67.5,3.970370,True
44,OMO_STR_0045,Ricinodendron heudeloti,4.2,Core,Major River,332.2,66.5,4.995489,True
91,OMO_STR_0092,Nesogordonia papaverifera,4.4,Buffer,Major River,62.4,62.4,1.000000,True
164,OMO_STR_0165,Bambusa vulgaris,4.7,Transition,Major River,292.2,58.4,5.003425,True
189,OMO_STR_0190,Uapaca heudelotii,4.7,Transition,Major River,116.8,58.4,2.000000,True
92,OMO_STR_0093,Pavetta corymbosia,4.4,Buffer,Major River,58.1,58.1,1.000000,True
18,OMO_STR_0019,Picralima nitida,4.1,Core,Stream,226.9,56.7,4.001764,True
87,OMO_STR_0088,Homalium aylmeri,4.4,Buffer,Major River,283.0,56.6,5.000000,True
95,OMO_STR_0096,Ricinodendron heudeotii,4.4,Buffer,Major River,111.9,55.9,2.001789,True
136,OMO_STR_0137,Blighia sapida,4.6,Buffer,Upland,55.2,55.2,1.000000,True
50,OMO_STR_0051,Uapaca heudelotii,4.2,Core,Major River,164.8,54.9,3.001821,True
41,OMO_STR_0042,Nesodogornia papaverifera,4.2,Core,Major River,274.4,54.8,5.007299,True
9,OMO_STR_0010,Ficus exasperata,4.1,Core,Stream,217.6,54.4,4.000000,True
215,OMO_STR_0216,Ficus mucosa,4.9,Transition,Upland,102.0,51.0,2.000000,True

Mean height by management zone
------------------------------------------------------------------------

  Management_Zone  Records  Minimum  Median       Mean  Maximum
0          Buffer       86      9.8   28.25  30.290698     62.4
1            Core       75     14.1   26.50  30.717067     82.1
2      Transition       61     10.4   23.80  25.440984     58.4

Mean height by habitat
------------------------------------------------------------------------

       Habitat  Records  Minimum  Median       Mean  Maximum
0  Major River       80      9.8   25.95  28.381750     66.5
1       Stream       72     12.7   30.70  32.354583     82.1
2       Upland       70     12.9   24.25  26.580143     55.2

In [46]:
# =============================================================================
# 07A.6.14 — Data-Driven Height Outlier Screening
# =============================================================================

height_q1 = height_values.quantile(0.25)
height_q3 = height_values.quantile(0.75)

height_iqr = height_q3 - height_q1

height_lower_fence = (
    height_q1 - 1.5 * height_iqr
)

height_upper_fence = (
    height_q3 + 1.5 * height_iqr
)


structure_validation["Height_IQR_Outlier"] = (
    (height_values < height_lower_fence)
    | (height_values > height_upper_fence)
)


height_outliers = (
    structure_validation.loc[
        structure_validation["Height_IQR_Outlier"],
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Management_Zone",
            "Habitat",
            "Total_Height_Num",
            "Mean_Height_Num",
            "Inferred_N_Height",
            "Rounded_N_Height",
            "Height_N_Integer_Error",
            "Total_Mean_Consistent",
            "Count_Consistency_Class",
        ],
    ]
    .copy()
    .sort_values("Mean_Height_Num")
    .reset_index(drop=True)
)


print("Data-driven height outlier screening")
print("=" * 72)

print(f"Q1                 : {height_q1:.2f}")
print(f"Q3                 : {height_q3:.2f}")
print(f"IQR                : {height_iqr:.2f}")
print(f"Lower IQR fence    : {height_lower_fence:.2f}")
print(f"Upper IQR fence    : {height_upper_fence:.2f}")

print(
    f"\nHeight IQR outliers : "
    f"{len(height_outliers)} / {len(structure_validation)}"
)


print("\nPotential height outliers")
print("-" * 72)

display(height_outliers)

Data-driven height outlier screening
========================================================================
Q1                 : 21.17
Q3                 : 34.18
IQR                : 13.01
Lower IQR fence    : 1.66
Upper IQR fence    : 53.68

Height IQR outliers : 14 / 222

Potential height outliers
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Total_Height_Num,Mean_Height_Num,Inferred_N_Height,Rounded_N_Height,Height_N_Integer_Error,Total_Mean_Consistent,Count_Consistency_Class
0,OMO_STR_0010,Ficus exasperata,4.1,Core,Stream,217.6,54.4,4.000000,4.0,0.000000,True,CONSISTENT
1,OMO_STR_0042,Nesodogornia papaverifera,4.2,Core,Major River,274.4,54.8,5.007299,5.0,0.007299,True,CONSISTENT
2,OMO_STR_0051,Uapaca heudelotii,4.2,Core,Major River,164.8,54.9,3.001821,3.0,0.001821,True,CONSISTENT
3,OMO_STR_0137,Blighia sapida,4.6,Buffer,Upland,55.2,55.2,1.000000,1.0,0.000000,True,CONSISTENT
4,OMO_STR_0096,Ricinodendron heudeotii,4.4,Buffer,Major River,111.9,55.9,2.001789,2.0,0.001789,True,CONSISTENT
5,OMO_STR_0088,Homalium aylmeri,4.4,Buffer,Major River,283.0,56.6,5.000000,5.0,0.000000,True,CONSISTENT
6,OMO_STR_0019,Picralima nitida,4.1,Core,Stream,226.9,56.7,4.001764,4.0,0.001764,True,CONSISTENT
7,OMO_STR_0093,Pavetta corymbosia,4.4,Buffer,Major River,58.1,58.1,1.000000,1.0,0.000000,True,CONSISTENT
8,OMO_STR_0190,Uapaca heudelotii,4.7,Transition,Major River,116.8,58.4,2.000000,2.0,0.000000,True,CONSISTENT
9,OMO_STR_0165,Bambusa vulgaris,4.7,Transition,Major River,292.2,58.4,5.003425,5.0,0.003425,True,CONSISTENT
10,OMO_STR_0092,Nesogordonia papaverifera,4.4,Buffer,Major River,62.4,62.4,1.000000,1.0,0.000000,True,CONSISTENT
11,OMO_STR_0045,Ricinodendron heudeloti,4.2,Core,Major River,332.2,66.5,4.995489,5.0,0.004511,True,CONSISTENT
12,OMO_STR_0020,Pycnanthus angolensis,4.1,Core,Stream,268.0,67.5,3.970370,4.0,0.029630,True,CONSISTENT
13,OMO_STR_0021,Ricinodendron heudeloti,4.1,Core,Stream,410.5,82.1,5.000000,5.0,0.000000,True,CONSISTENT

In [47]:
# =============================================================================
# 07A.6.15 — Formalize Height Validation and Unit Interpretation
# =============================================================================

n_height_iqr_outliers = int(
    structure_validation["Height_IQR_Outlier"].sum()
)

n_high_height_outliers = int(
    (
        structure_validation["Mean_Height_Num"]
        > height_upper_fence
    ).sum()
)

n_low_height_outliers = int(
    (
        structure_validation["Mean_Height_Num"]
        < height_lower_fence
    ).sum()
)


# -----------------------------------------------------------------------------
# Determine whether statistical outliers also show internal arithmetic problems
# -----------------------------------------------------------------------------

height_outlier_inconsistent = int(
    (
        structure_validation["Height_IQR_Outlier"]
        & ~structure_validation["Total_Mean_Consistent"]
    ).sum()
)


print("Height validation interpretation")
print("=" * 72)

print(
    f"Observed mean-height range       : "
    f"{height_values.min():.1f} – {height_values.max():.1f}"
)

print(
    f"Median mean height               : "
    f"{height_values.median():.2f}"
)

print(
    f"IQR statistical outliers        : "
    f"{n_height_iqr_outliers}"
)

print(
    f"Low IQR outliers                : "
    f"{n_low_height_outliers}"
)

print(
    f"High IQR outliers               : "
    f"{n_high_height_outliers}"
)

print(
    f"IQR outliers failing total/mean : "
    f"{height_outlier_inconsistent}"
)


# -----------------------------------------------------------------------------
# Dataset-level interpretation
# -----------------------------------------------------------------------------

HEIGHT_UNIT_STATUS = (
    "Likely metres based on biological magnitude and internal consistency; "
    "unit not independently documented in the historical source."
)

HEIGHT_OUTLIER_STATUS = (
    "No HEIGHT_OUTLIER QC flags assigned. The 14 upper-IQR observations "
    "are internally coherent and are retained as plausible high structural "
    "values rather than classified as measurement errors."
)


print("\nInterpretation")
print("-" * 72)

print(f"Height unit status    : {HEIGHT_UNIT_STATUS}")
print(f"Height outlier status : {HEIGHT_OUTLIER_STATUS}")


# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------

assert n_height_iqr_outliers == 14, (
    "Expected 14 statistical height outliers."
)

assert n_low_height_outliers == 0, (
    "Unexpected low-height IQR outliers detected."
)

assert n_high_height_outliers == 14, (
    "Expected all 14 height IQR outliers to be upper-tail observations."
)

assert height_outlier_inconsistent == 0, (
    "One or more height IQR outliers also fail the total/mean "
    "consistency assessment and require individual review."
)


print("\nHeight validation interpretation: PASSED")

Height validation interpretation
========================================================================
Observed mean-height range       : 9.8 – 82.1
Median mean height               : 26.95
IQR statistical outliers        : 14
Low IQR outliers                : 0
High IQR outliers               : 14
IQR outliers failing total/mean : 0

Interpretation
------------------------------------------------------------------------
Height unit status    : Likely metres based on biological magnitude and internal consistency; unit not independently documented in the historical source.
Height outlier status : No HEIGHT_OUTLIER QC flags assigned. The 14 upper-IQR observations are internally coherent and are retained as plausible high structural values rather than classified as measurement errors.

Height validation interpretation: PASSED

In [48]:
# =============================================================================
# 07A.6.16 — DBH Range and Data-Driven Outlier Screening
# =============================================================================

dbh_values = structure_validation["Mean_DBH_Num"]

dbh_q1 = dbh_values.quantile(0.25)
dbh_q3 = dbh_values.quantile(0.75)
dbh_iqr = dbh_q3 - dbh_q1

dbh_lower_fence = dbh_q1 - 1.5 * dbh_iqr
dbh_upper_fence = dbh_q3 + 1.5 * dbh_iqr


structure_validation["DBH_IQR_Outlier"] = (
    (dbh_values < dbh_lower_fence)
    | (dbh_values > dbh_upper_fence)
)


dbh_outliers = (
    structure_validation.loc[
        structure_validation["DBH_IQR_Outlier"],
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Management_Zone",
            "Habitat",
            "Total_DBH_Num",
            "Mean_DBH_Num",
            "Inferred_N_DBH",
            "Rounded_N_DBH",
            "DBH_N_Integer_Error",
            "Basal_Area_Num",
            "BA_From_Mean_DBH",
            "BA_Percent_Error",
            "Total_Mean_Consistent",
        ],
    ]
    .copy()
    .sort_values("Mean_DBH_Num")
    .reset_index(drop=True)
)


print("DBH range and outlier assessment")
print("=" * 72)

print("\nOverall Mean DBH distribution")
print("-" * 72)

display(
    dbh_values.describe(
        percentiles=[
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
        ]
    ).to_frame("Mean_DBH")
)


print("\nIQR screening")
print("-" * 72)

print(f"Q1              : {dbh_q1:.2f}")
print(f"Q3              : {dbh_q3:.2f}")
print(f"IQR             : {dbh_iqr:.2f}")
print(f"Lower IQR fence : {dbh_lower_fence:.2f}")
print(f"Upper IQR fence : {dbh_upper_fence:.2f}")

print(
    f"\nDBH IQR outliers : "
    f"{len(dbh_outliers)} / {len(structure_validation)}"
)


print("\nPotential DBH outliers")
print("-" * 72)

display(dbh_outliers)

DBH range and outlier assessment
========================================================================

Overall Mean DBH distribution
------------------------------------------------------------------------

         Mean_DBH
count  222.000000
mean    30.054054
std     18.830355
min     10.000000
1%      11.021000
5%      13.500000
10%     16.610000
25%     20.625000
50%     26.500000
75%     33.750000
90%     46.460000
95%     53.500000
99%     82.677000
max    227.700000

IQR screening
------------------------------------------------------------------------
Q1              : 20.62
Q3              : 33.75
IQR             : 13.12
Lower IQR fence : 0.94
Upper IQR fence : 53.44

DBH IQR outliers : 13 / 222

Potential DBH outliers
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Total_DBH_Num,Mean_DBH_Num,Inferred_N_DBH,Rounded_N_DBH,DBH_N_Integer_Error,Basal_Area_Num,BA_From_Mean_DBH,BA_Percent_Error,Total_Mean_Consistent
0,OMO_STR_0190,Uapaca heudelotii,4.7,Transition,Major River,107.0,53.5,2.000000,2.0,0.000000,2248.0,2248.005893,0.000262,True
1,OMO_STR_0130,Sterculia oblonga,4.5,Buffer,Stream,107.0,53.5,2.000000,2.0,0.000000,2248.0,2248.005893,0.000262,True
2,OMO_STR_0019,Picralima nitida,4.1,Core,Stream,221.2,55.3,4.000000,4.0,0.000000,2402.8,2401.818270,0.040858,True
3,OMO_STR_0010,Ficus exasperata,4.1,Core,Stream,225.6,56.4,4.000000,4.0,0.000000,2499.3,2498.320142,0.039205,True
4,OMO_STR_0042,Nesodogornia papaverifera,4.2,Core,Major River,283.0,56.6,5.000000,5.0,0.000000,2517.0,2516.070140,0.036943,True
5,OMO_STR_0088,Homalium aylmeri,4.4,Buffer,Major River,310.0,62.0,5.000000,5.0,0.000000,3020.0,3019.070540,0.030777,True
6,OMO_STR_0045,Ricinodendron heudeloti,4.2,Core,Major River,324.9,64.8,5.013889,5.0,0.013889,3299.0,3297.918304,0.032789,True
7,OMO_STR_0093,Pavetta corymbosia,4.4,Buffer,Major River,66.8,66.8,1.000000,1.0,0.000000,3506.0,3504.635101,0.038930,True
8,OMO_STR_0197,Elaeis guinenesis,4.8,Transition,Stream,895.0,68.4,13.084795,13.0,0.084795,3676.0,3674.532431,0.039923,False
9,OMO_STR_0020,Pycnanthus angolensis,4.1,Core,Stream,310.9,77.7,4.001287,4.0,0.001287,4743.6,4741.676478,0.040550,True
10,OMO_STR_0092,Nesogordonia papaverifera,4.4,Buffer,Major River,84.0,84.0,1.000000,1.0,0.000000,5544.0,5541.769441,0.040234,True
11,OMO_STR_0021,Ricinodendron heudeloti,4.1,Core,Stream,510.1,102.2,4.991194,5.0,0.008806,8206.7,8203.358153,0.040721,True
12,OMO_STR_0165,Bambusa vulgaris,4.7,Transition,Major River,1138.8,227.7,5.001318,5.0,0.001318,40737.0,40720.766343,0.039850,True

In [49]:
# =============================================================================
# 07A.6.17 — Formalize DBH Range and Outlier Interpretation
# =============================================================================

n_dbh_iqr_outliers = int(
    structure_validation["DBH_IQR_Outlier"].sum()
)

n_high_dbh_outliers = int(
    (
        structure_validation["Mean_DBH_Num"]
        > dbh_upper_fence
    ).sum()
)

n_low_dbh_outliers = int(
    (
        structure_validation["Mean_DBH_Num"]
        < dbh_lower_fence
    ).sum()
)

n_dbh_outlier_ba_consistent = int(
    (
        structure_validation["DBH_IQR_Outlier"]
        & structure_validation["BA_Strictly_Consistent"]
    ).sum()
)

n_dbh_outlier_total_mean_inconsistent = int(
    (
        structure_validation["DBH_IQR_Outlier"]
        & ~structure_validation["Total_Mean_Consistent"]
    ).sum()
)


print("DBH validation interpretation")
print("=" * 72)

print(
    f"Observed Mean DBH range             : "
    f"{dbh_values.min():.1f} – {dbh_values.max():.1f}"
)

print(
    f"Median Mean DBH                     : "
    f"{dbh_values.median():.2f}"
)

print(
    f"IQR statistical outliers            : "
    f"{n_dbh_iqr_outliers}"
)

print(
    f"Low IQR outliers                    : "
    f"{n_low_dbh_outliers}"
)

print(
    f"High IQR outliers                   : "
    f"{n_high_dbh_outliers}"
)

print(
    f"IQR outliers with strict BA support : "
    f"{n_dbh_outlier_ba_consistent}"
)

print(
    f"IQR outliers failing total/mean QC  : "
    f"{n_dbh_outlier_total_mean_inconsistent}"
)


# -----------------------------------------------------------------------------
# Dataset-level interpretation
# -----------------------------------------------------------------------------

DBH_OUTLIER_STATUS = (
    "No DBH_OUTLIER QC flags assigned solely from IQR screening. "
    "All 13 upper-tail observations are independently reproduced by "
    "their reported basal-area values. One upper-tail record also fails "
    "the total/mean consistency assessment and is already flagged "
    "TOTAL_MEAN_INCONSISTENT."
)


print("\nInterpretation")
print("-" * 72)

print(f"DBH outlier status : {DBH_OUTLIER_STATUS}")


# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------

assert n_dbh_iqr_outliers == 13, (
    "Expected exactly 13 DBH IQR outliers."
)

assert n_low_dbh_outliers == 0, (
    "Unexpected low DBH IQR outliers detected."
)

assert n_high_dbh_outliers == 13, (
    "Expected all DBH IQR outliers to be upper-tail observations."
)

assert n_dbh_outlier_ba_consistent == 13, (
    "One or more DBH IQR outliers are not supported by the "
    "strict basal-area consistency test."
)

assert n_dbh_outlier_total_mean_inconsistent == 1, (
    "Expected exactly one DBH IQR outlier to fail the "
    "total/mean consistency assessment."
)


print("\nDBH validation interpretation: PASSED")

DBH validation interpretation
========================================================================
Observed Mean DBH range             : 10.0 – 227.7
Median Mean DBH                     : 26.50
IQR statistical outliers            : 13
Low IQR outliers                    : 0
High IQR outliers                   : 13
IQR outliers with strict BA support : 13
IQR outliers failing total/mean QC  : 1

Interpretation
------------------------------------------------------------------------
DBH outlier status : No DBH_OUTLIER QC flags assigned solely from IQR screening. All 13 upper-tail observations are independently reproduced by their reported basal-area values. One upper-tail record also fails the total/mean consistency assessment and is already flagged TOTAL_MEAN_INCONSISTENT.

DBH validation interpretation: PASSED

### 07A.6.18 — Basal-Area Percentage Validation

The historical structural tables report both basal area (`BA`) and
basal-area percentage (`BA %`).

This section evaluates whether:

- reported BA percentages sum approximately to 100% within each source table;
- reported BA percentages can be reproduced from the reported BA values;
- the percentage denominator is the sum of reported species-level BA values
  within each Management Zone × Habitat table; and
- any source tables or records contain percentage inconsistencies.

No historical values are modified.

In [50]:
# =============================================================================
# 07A.6.18 — Validate BA Percentage Totals by Source Table
# =============================================================================

ba_percent_table_summary = (
    structure_validation
    .groupby(
        [
            "Source_Table",
            "Management_Zone",
            "Habitat",
        ],
        observed=True,
    )
    .agg(
        Records=("Raw_Record_ID", "count"),
        Sum_Reported_BA=("Basal_Area_Num", "sum"),
        Sum_Reported_BA_Percent=("BA_Percent_Num", "sum"),
    )
    .reset_index()
)


ba_percent_table_summary["Percent_Total_Error"] = (
    ba_percent_table_summary["Sum_Reported_BA_Percent"]
    - 100.0
).abs()


print("Basal-area percentage totals by source table")
print("=" * 72)

display(ba_percent_table_summary)


print("\nSummary")
print("-" * 72)

print(
    f"Source tables assessed : "
    f"{len(ba_percent_table_summary)}"
)

print(
    f"Minimum BA % total     : "
    f"{ba_percent_table_summary['Sum_Reported_BA_Percent'].min():.2f}"
)

print(
    f"Maximum BA % total     : "
    f"{ba_percent_table_summary['Sum_Reported_BA_Percent'].max():.2f}"
)

print(
    f"Maximum deviation from 100% : "
    f"{ba_percent_table_summary['Percent_Total_Error'].max():.2f}"
)


assert len(ba_percent_table_summary) == 9, (
    "Expected exactly nine structural source tables."
)

Basal-area percentage totals by source table
========================================================================

,Source_Table,Management_Zone,Habitat,Records,Sum_Reported_BA,Sum_Reported_BA_Percent,Percent_Total_Error
0,4.1,Core,Stream,25,39180.72,99.86,0.14
1,4.2,Core,Major River,26,17809.30,99.89,0.11
2,4.3,Core,Upland,24,11157.10,99.87,0.13
3,4.4,Buffer,Major River,25,28623.44,99.87,0.13
4,4.5,Buffer,Stream,33,25564.67,98.18,1.82
5,4.6,Buffer,Upland,28,19256.90,99.86,0.14
6,4.7,Transition,Major River,29,58134.00,99.86,0.14
7,4.8,Transition,Stream,14,11335.27,99.81,0.19
8,4.9,Transition,Upland,18,8040.30,204.16,104.16

Summary
------------------------------------------------------------------------
Source tables assessed : 9
Minimum BA % total     : 98.18
Maximum BA % total     : 204.16
Maximum deviation from 100% : 104.16

In [51]:
# =============================================================================
# 07A.6.19 — Reconstruct BA Percentages from Reported BA
# =============================================================================

structure_validation["BA_Table_Total"] = (
    structure_validation
    .groupby("Source_Table")["Basal_Area_Num"]
    .transform("sum")
)


structure_validation["BA_Percent_Reconstructed"] = (
    structure_validation["Basal_Area_Num"]
    / structure_validation["BA_Table_Total"]
    * 100
)


structure_validation["BA_Percent_Absolute_Error"] = (
    structure_validation["BA_Percent_Num"]
    - structure_validation["BA_Percent_Reconstructed"]
).abs()


print("Reconstructed basal-area percentages")
print("=" * 72)

print("\nAbsolute percentage-point error")
print("-" * 72)

display(
    structure_validation["BA_Percent_Absolute_Error"]
    .describe()
    .to_frame("BA_Percent_Absolute_Error")
)


print("\nReported versus reconstructed BA % — sample")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Basal_Area_Num",
            "BA_Table_Total",
            "BA_Percent_Num",
            "BA_Percent_Reconstructed",
            "BA_Percent_Absolute_Error",
        ]
    ].head(20)
)

Reconstructed basal-area percentages
========================================================================

Absolute percentage-point error
------------------------------------------------------------------------

       BA_Percent_Absolute_Error
count                 222.000000
mean                    0.482499
std                     6.994909
min                     0.000011
25%                     0.003202
50%                     0.006030
75%                     0.008912
max                   104.234270

Reported versus reconstructed BA % — sample
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Basal_Area_Num,BA_Table_Total,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error
0,OMO_STR_0001,Alstonia boonei,4.1,1037.60,39180.72,2.64,2.648241,0.008241
1,OMO_STR_0002,Blighia sapida,4.1,876.51,39180.72,2.23,2.237095,0.007095
2,OMO_STR_0003,Bombax buonopozene,4.1,779.63,39180.72,1.98,1.989831,0.009831
3,OMO_STR_0004,Bosquei angolensis,4.1,647.19,39180.72,1.65,1.651807,0.001807
4,OMO_STR_0005,Celtis zenkeri,4.1,679.14,39180.72,1.73,1.733353,0.003353
5,OMO_STR_0006,Cleistopholis Patens,4.1,755.07,39180.72,1.92,1.927147,0.007147
6,OMO_STR_0007,Dialium guinensis,4.1,860.84,39180.72,2.19,2.197101,0.007101
7,OMO_STR_0008,Diospyros dendo,4.1,363.20,39180.72,0.92,0.926987,0.006987
8,OMO_STR_0009,Drypetes,4.1,495.01,39180.72,1.26,1.263402,0.003402
9,OMO_STR_0010,Ficus exasperata,4.1,2499.30,39180.72,6.37,6.378903,0.008903
10,OMO_STR_0011,Grewia pubescens,4.1,779.63,39180.72,1.98,1.989831,0.009831
11,OMO_STR_0012,Homalium alymeri,4.1,2132.80,39180.72,5.44,5.443494,0.003494
12,OMO_STR_0013,Lecaniodiscus cupanioides,4.1,441.33,39180.72,1.12,1.126396,0.006396
13,OMO_STR_0014,Margaritaria discoidea,4.1,487.15,39180.72,1.24,1.243341,0.003341
14,OMO_STR_0015,Musanga cecropoides,4.1,568.55,39180.72,1.45,1.451096,0.001096
15,OMO_STR_0016,Nesodogornia papaverivera,4.1,2165.60,39180.72,5.52,5.527208,0.007208
16,OMO_STR_0017,Pavetta crassipes,4.1,804.57,39180.72,2.05,2.053484,0.003484
17,OMO_STR_0018,Picralima nitida,4.1,1698.90,39180.72,4.33,4.336061,0.006061
18,OMO_STR_0019,Picralima nitida,4.1,2402.80,39180.72,6.13,6.132608,0.002608
19,OMO_STR_0020,Pycnanthus angolensis,4.1,4743.60,39180.72,12.10,12.106975,0.006975

In [52]:
# =============================================================================
# 07A.6.20 — Evaluate BA Percentage Consistency
# =============================================================================

BA_PERCENT_TOLERANCE = 0.05


structure_validation["BA_Percent_Consistent"] = (
    structure_validation["BA_Percent_Absolute_Error"]
    <= BA_PERCENT_TOLERANCE
)


n_ba_percent_consistent = int(
    structure_validation["BA_Percent_Consistent"].sum()
)

n_ba_percent_inconsistent = int(
    (~structure_validation["BA_Percent_Consistent"]).sum()
)


print("Basal-area percentage consistency")
print("=" * 72)

print(
    f"Within ±{BA_PERCENT_TOLERANCE:.2f} percentage points : "
    f"{n_ba_percent_consistent} / {len(structure_validation)}"
)

print(
    f"Outside tolerance                         : "
    f"{n_ba_percent_inconsistent} / {len(structure_validation)}"
)


print("\nLargest BA percentage discrepancies")
print("-" * 72)

display(
    structure_validation[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Management_Zone",
            "Habitat",
            "Basal_Area_Num",
            "BA_Table_Total",
            "BA_Percent_Num",
            "BA_Percent_Reconstructed",
            "BA_Percent_Absolute_Error",
        ]
    ]
    .sort_values(
        "BA_Percent_Absolute_Error",
        ascending=False,
    )
    .head(20)
)

Basal-area percentage consistency
========================================================================
Within ±0.05 percentage points : 205 / 222
Outside tolerance                         : 17 / 222

Largest BA percentage discrepancies
------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Basal_Area_Num,BA_Table_Total,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error
213,OMO_STR_0214,Elaeis guineensis,4.9,Transition,Upland,946.0,8040.30,116.00,11.765730,104.234270
129,OMO_STR_0130,Sterculia oblonga,4.5,Buffer,Stream,2248.0,25564.67,8.64,8.793386,0.153386
127,OMO_STR_0128,Rothmania hispida,4.5,Buffer,Stream,1521.0,25564.67,5.84,5.949617,0.109617
102,OMO_STR_0103,Anthocleista djalonensis,4.5,Buffer,Stream,1514.0,25564.67,5.82,5.922236,0.102236
121,OMO_STR_0122,Musanga cecropoides,4.5,Buffer,Stream,1419.0,25564.67,5.45,5.550629,0.100629
109,OMO_STR_0110,Diospyrous dendo,4.5,Buffer,Stream,1439.0,25564.67,5.53,5.628862,0.098862
119,OMO_STR_0120,Melacantha alnifolia,4.5,Buffer,Stream,1479.0,25564.67,5.69,5.785328,0.095328
192,OMO_STR_0193,Anthocliesta vogelii,4.8,Transition,Stream,452.5,11335.27,3.90,3.991965,0.091965
118,OMO_STR_0119,Macaranga barteri,4.5,Buffer,Stream,1263.0,25564.67,4.85,4.940412,0.090412
132,OMO_STR_0133,Terminalia superba,4.5,Buffer,Stream,1164.0,25564.67,4.47,4.553159,0.083159
131,OMO_STR_0132,Strombosia pustulata,4.5,Buffer,Stream,1238.0,25564.67,4.76,4.842621,0.082621
112,OMO_STR_0113,Funtumia africana,4.5,Buffer,Stream,860.8,25564.67,3.30,3.367147,0.067147
126,OMO_STR_0127,Rauvolvia vomitoria,4.5,Buffer,Stream,908.2,25564.67,3.49,3.552559,0.062559
124,OMO_STR_0125,Nuclea diderrichi,4.5,Buffer,Stream,887.0,25564.67,3.41,3.469632,0.059632
111,OMO_STR_0112,Drypetes,4.5,Buffer,Stream,735.7,25564.67,2.82,2.877800,0.057800
123,OMO_STR_0124,Nothospondia staudtii,4.5,Buffer,Stream,868.6,25564.67,3.34,3.397658,0.057658
108,OMO_STR_0109,Cleistopholis patens,4.5,Buffer,Stream,764.8,25564.67,2.94,2.991629,0.051629
120,OMO_STR_0121,Micranga barteri,4.5,Buffer,Stream,651.7,25564.67,2.50,2.549221,0.049221
122,OMO_STR_0123,Nauclea diderrichi,4.5,Buffer,Stream,633.7,25564.67,2.43,2.478812,0.048812
116,OMO_STR_0117,Hexalobus crispiflorus,4.5,Buffer,Stream,633.7,25564.67,2.43,2.478812,0.048812

### 07A.6.21 — Diagnosis of Basal-Area Percentage Anomalies

The initial BA-percentage validation identified two source tables requiring
additional investigation:

- Table 4.5 — Buffer × Stream, where reported BA percentages sum to 98.18%;
- Table 4.9 — Transition × Upland, where reported BA percentages sum to
  204.16%.

These cases are investigated separately before any record-level QC flags are
assigned.

The objective is to distinguish between:

- rounding effects;
- incomplete or inconsistent table denominators;
- source transcription errors; and
- genuine record-level percentage inconsistencies.

Historical source values remain unchanged.

In [53]:
# =============================================================================
# 07A.6.21 — Diagnose BA Percentage Anomalies in Tables 4.5 and 4.9
# =============================================================================

for source_table in ["4.5", "4.9"]:

    diagnostic = (
        structure_validation.loc[
            structure_validation["Source_Table"] == source_table,
            [
                "Raw_Record_ID",
                "Source_Species",
                "Basal_Area_Num",
                "BA_Percent_Num",
                "BA_Percent_Reconstructed",
                "BA_Percent_Absolute_Error",
            ],
        ]
        .copy()
        .reset_index(drop=True)
    )

    print("\n" + "=" * 80)
    print(f"SOURCE TABLE {source_table}")
    print("=" * 80)

    display(diagnostic)

    print(f"Records           : {len(diagnostic)}")

    print(
        f"Sum reported BA   : "
        f"{diagnostic['Basal_Area_Num'].sum():.2f}"
    )

    print(
        f"Sum reported BA % : "
        f"{diagnostic['BA_Percent_Num'].sum():.2f}"
    )

================================================================================
SOURCE TABLE 4.5
================================================================================

,Raw_Record_ID,Source_Species,Basal_Area_Num,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error
0,OMO_STR_0101,Albizia zygia,638.20,2.45,2.496414,0.046414
1,OMO_STR_0102,Alstonia boonei,198.60,0.76,0.776853,0.016853
2,OMO_STR_0103,Anthocleista djalonensis,1514.00,5.82,5.922236,0.102236
3,OMO_STR_0104,Anthocliesta vogeli,78.57,0.30,0.307338,0.007338
4,OMO_STR_0105,Brachystegia eurycoma,387.20,1.48,1.514590,0.034590
5,OMO_STR_0106,Bridellia ferruginea,283.60,1.09,1.109343,0.019343
6,OMO_STR_0107,Cassia saimen,581.30,2.23,2.273841,0.043841
7,OMO_STR_0108,Ceiba pentandra,408.40,1.57,1.597517,0.027517
8,OMO_STR_0109,Cleistopholis patens,764.80,2.94,2.991629,0.051629
9,OMO_STR_0110,Diospyrous dendo,1439.00,5.53,5.628862,0.098862
10,OMO_STR_0111,Diospyrous melistoformis,304.90,1.17,1.192662,0.022662
11,OMO_STR_0112,Drypetes,735.70,2.82,2.877800,0.057800
12,OMO_STR_0113,Funtumia africana,860.80,3.30,3.367147,0.067147
13,OMO_STR_0114,Funtumia elastica,475.40,1.82,1.859598,0.039598
14,OMO_STR_0115,Gmelina arborea,452.50,1.74,1.770021,0.030021
15,OMO_STR_0116,Harungana madagascariensis,219.10,0.84,0.857042,0.017042
16,OMO_STR_0117,Hexalobus crispiflorus,633.70,2.43,2.478812,0.048812
17,OMO_STR_0118,Holarrhena floribunda,572.70,2.20,2.240201,0.040201
18,OMO_STR_0119,Macaranga barteri,1263.00,4.85,4.940412,0.090412
19,OMO_STR_0120,Melacantha alnifolia,1479.00,5.69,5.785328,0.095328
20,OMO_STR_0121,Micranga barteri,651.70,2.50,2.549221,0.049221
21,OMO_STR_0122,Musanga cecropoides,1419.00,5.45,5.550629,0.100629
22,OMO_STR_0123,Nauclea diderrichi,633.70,2.43,2.478812,0.048812
23,OMO_STR_0124,Nothospondia staudtii,868.60,3.34,3.397658,0.057658
24,OMO_STR_0125,Nuclea diderrichi,887.00,3.41,3.469632,0.059632
25,OMO_STR_0126,Pterocarpus osun,227.00,0.87,0.887944,0.017944
26,OMO_STR_0127,Rauvolvia vomitoria,908.20,3.49,3.552559,0.062559
27,OMO_STR_0128,Rothmania hispida,1521.00,5.84,5.949617,0.109617
28,OMO_STR_0129,Spondia mombin,224.40,0.86,0.877774,0.017774
29,OMO_STR_0130,Sterculia oblonga,2248.00,8.64,8.793386,0.153386
30,OMO_STR_0131,Sterculia rhinopetala,283.60,1.09,1.109343,0.019343
31,OMO_STR_0132,Strombosia pustulata,1238.00,4.76,4.842621,0.082621
32,OMO_STR_0133,Terminalia superba,1164.00,4.47,4.553159,0.083159

Records           : 33
Sum reported BA   : 25564.67
Sum reported BA % : 98.18

================================================================================
SOURCE TABLE 4.9
================================================================================

,Raw_Record_ID,Source_Species,Basal_Area_Num,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error
0,OMO_STR_0205,Artocarpus communis,380.2,4.72,4.728679,0.008679
1,OMO_STR_0206,Bambusa vulgaris,124.7,1.55,1.550937,0.000937
2,OMO_STR_0207,Bombax buonopozene,585.5,7.28,7.282067,0.002067
3,OMO_STR_0208,Carica papaya,169.7,2.11,2.110618,0.000618
4,OMO_STR_0209,Ceiba pentandra,206.2,2.56,2.564581,0.004581
5,OMO_STR_0210,Chrysophyllum albidum,115.0,1.43,1.430295,0.000295
6,OMO_STR_0211,Citrus sinenses,471.6,5.86,5.865453,0.005453
7,OMO_STR_0212,Cola nitida,224.4,2.79,2.790941,0.000941
8,OMO_STR_0213,Dracena manni,283.6,3.52,3.527232,0.007232
9,OMO_STR_0214,Elaeis guineensis,946.0,116.00,11.765730,104.234270
10,OMO_STR_0215,Ficus exasperata,607.2,7.55,7.551957,0.001957
11,OMO_STR_0216,Ficus mucosa,1833.0,22.79,22.797657,0.007657
12,OMO_STR_0217,Musa sapiensis,598.5,7.44,7.443752,0.003752
13,OMO_STR_0218,Raulvolfia vomitoria,102.1,1.26,1.269853,0.009853
14,OMO_STR_0219,Ricinodendron heudeloti,539.3,6.70,6.707461,0.007461
15,OMO_STR_0220,Theobroma cacao,263.1,3.27,3.272266,0.002266
16,OMO_STR_0221,Trema orientalis,363.2,4.51,4.517244,0.007244
17,OMO_STR_0222,Uapaca heudeloti,227.0,2.82,2.823278,0.003278

Records           : 18
Sum reported BA   : 8040.30
Sum reported BA % : 204.16

In [54]:
# =============================================================================
# 07A.6.22 — Infer Historical BA Percentage Denominators
# =============================================================================

structure_validation["BA_Implied_Denominator"] = (
    structure_validation["Basal_Area_Num"]
    * 100
    / structure_validation["BA_Percent_Num"]
)


denominator_summary = (
    structure_validation
    .groupby(
        [
            "Source_Table",
            "Management_Zone",
            "Habitat",
        ],
        observed=True,
    )
    .agg(
        Records=(
            "Raw_Record_ID",
            "count",
        ),
        Reconstructed_BA_Total=(
            "Basal_Area_Num",
            "sum",
        ),
        Median_Implied_Denominator=(
            "BA_Implied_Denominator",
            "median",
        ),
        Min_Implied_Denominator=(
            "BA_Implied_Denominator",
            "min",
        ),
        Max_Implied_Denominator=(
            "BA_Implied_Denominator",
            "max",
        ),
    )
    .reset_index()
)


denominator_summary["Denominator_Difference"] = (
    denominator_summary["Median_Implied_Denominator"]
    - denominator_summary["Reconstructed_BA_Total"]
)


denominator_summary["Denominator_Difference_Percent"] = (
    denominator_summary["Denominator_Difference"]
    / denominator_summary["Reconstructed_BA_Total"]
    * 100
)


print("Historical BA-percentage denominator assessment")
print("=" * 80)

display(denominator_summary)

Historical BA-percentage denominator assessment
================================================================================

,Source_Table,Management_Zone,Habitat,Records,Reconstructed_BA_Total,Median_Implied_Denominator,Min_Implied_Denominator,Max_Implied_Denominator,Denominator_Difference,Denominator_Difference_Percent
0,4.1,Core,Stream,25,39180.72,39250.883392,39191.499522,39478.260870,70.163392,0.179076
1,4.2,Core,Major River,26,17809.30,17825.407971,17809.523810,17952.000000,16.107971,0.090447
2,4.3,Core,Upland,24,11157.10,11172.043011,11156.996587,11255.813953,14.943011,0.133933
3,4.4,Buffer,Major River,25,28623.44,28702.127660,28625.592417,28803.030303,78.687660,0.274906
4,4.5,Buffer,Stream,33,25564.67,26041.237113,25992.970123,26190.000000,476.567113,1.864163
5,4.6,Buffer,Upland,28,19256.90,19290.091345,19250.814332,19484.375000,33.191345,0.172361
6,4.7,Transition,Major River,29,58134.00,58430.107527,58097.826087,59666.666667,296.107527,0.509353
7,4.8,Transition,Stream,14,11335.27,11347.023773,11337.228715,11602.564103,11.753773,0.103692
8,4.9,Transition,Upland,18,8040.30,8045.516425,815.517241,8103.174603,5.216425,0.064878

In [55]:
# =============================================================================
# 07A.6.23 — Inspect Table 4.5 Implied Percentage Denominator
# =============================================================================

table_45_denominator = (
    structure_validation.loc[
        structure_validation["Source_Table"] == "4.5",
        [
            "Raw_Record_ID",
            "Source_Species",
            "Basal_Area_Num",
            "BA_Percent_Num",
            "BA_Implied_Denominator",
        ],
    ]
    .copy()
    .reset_index(drop=True)
)


print("Table 4.5 implied BA-percentage denominator")
print("=" * 80)

display(table_45_denominator)


print("\nImplied denominator statistics")
print("-" * 80)

display(
    table_45_denominator[
        "BA_Implied_Denominator"
    ]
    .describe()
    .to_frame("Implied_Denominator")
)


TABLE_45_SOURCE_BA_TOTAL = 26007.0

reconstructed_45_total = (
    table_45_denominator["Basal_Area_Num"]
    .sum()
)

missing_45_ba = (
    TABLE_45_SOURCE_BA_TOTAL
    - reconstructed_45_total
)


print("\nComparison with historical table total")
print("-" * 80)

print(
    f"Source-reported table BA total : "
    f"{TABLE_45_SOURCE_BA_TOTAL:.2f}"
)

print(
    f"Reconstructed species BA total : "
    f"{reconstructed_45_total:.2f}"
)

print(
    f"Difference                    : "
    f"{missing_45_ba:.2f}"
)

print(
    f"Percentage represented        : "
    f"{reconstructed_45_total / TABLE_45_SOURCE_BA_TOTAL * 100:.2f}%"
)

Table 4.5 implied BA-percentage denominator
================================================================================

,Raw_Record_ID,Source_Species,Basal_Area_Num,BA_Percent_Num,BA_Implied_Denominator
0,OMO_STR_0101,Albizia zygia,638.20,2.45,26048.979592
1,OMO_STR_0102,Alstonia boonei,198.60,0.76,26131.578947
2,OMO_STR_0103,Anthocleista djalonensis,1514.00,5.82,26013.745704
3,OMO_STR_0104,Anthocliesta vogeli,78.57,0.30,26190.000000
4,OMO_STR_0105,Brachystegia eurycoma,387.20,1.48,26162.162162
5,OMO_STR_0106,Bridellia ferruginea,283.60,1.09,26018.348624
6,OMO_STR_0107,Cassia saimen,581.30,2.23,26067.264574
7,OMO_STR_0108,Ceiba pentandra,408.40,1.57,26012.738854
8,OMO_STR_0109,Cleistopholis patens,764.80,2.94,26013.605442
9,OMO_STR_0110,Diospyrous dendo,1439.00,5.53,26021.699819
10,OMO_STR_0111,Diospyrous melistoformis,304.90,1.17,26059.829060
11,OMO_STR_0112,Drypetes,735.70,2.82,26088.652482
12,OMO_STR_0113,Funtumia africana,860.80,3.30,26084.848485
13,OMO_STR_0114,Funtumia elastica,475.40,1.82,26120.879121
14,OMO_STR_0115,Gmelina arborea,452.50,1.74,26005.747126
15,OMO_STR_0116,Harungana madagascariensis,219.10,0.84,26083.333333
16,OMO_STR_0117,Hexalobus crispiflorus,633.70,2.43,26078.189300
17,OMO_STR_0118,Holarrhena floribunda,572.70,2.20,26031.818182
18,OMO_STR_0119,Macaranga barteri,1263.00,4.85,26041.237113
19,OMO_STR_0120,Melacantha alnifolia,1479.00,5.69,25992.970123
20,OMO_STR_0121,Micranga barteri,651.70,2.50,26068.000000
21,OMO_STR_0122,Musanga cecropoides,1419.00,5.45,26036.697248
22,OMO_STR_0123,Nauclea diderrichi,633.70,2.43,26078.189300
23,OMO_STR_0124,Nothospondia staudtii,868.60,3.34,26005.988024
24,OMO_STR_0125,Nuclea diderrichi,887.00,3.41,26011.730205
25,OMO_STR_0126,Pterocarpus osun,227.00,0.87,26091.954023
26,OMO_STR_0127,Rauvolvia vomitoria,908.20,3.49,26022.922636
27,OMO_STR_0128,Rothmania hispida,1521.00,5.84,26044.520548
28,OMO_STR_0129,Spondia mombin,224.40,0.86,26093.023256
29,OMO_STR_0130,Sterculia oblonga,2248.00,8.64,26018.518519
30,OMO_STR_0131,Sterculia rhinopetala,283.60,1.09,26018.348624
31,OMO_STR_0132,Strombosia pustulata,1238.00,4.76,26008.403361
32,OMO_STR_0133,Terminalia superba,1164.00,4.47,26040.268456

Implied denominator statistics
--------------------------------------------------------------------------------

       Implied_Denominator
count            33.000000
mean          26054.733098
std              47.587924
min           25992.970123
25%           26018.348624
50%           26041.237113
75%           26083.333333
max           26190.000000

Comparison with historical table total
--------------------------------------------------------------------------------
Source-reported table BA total : 26007.00
Reconstructed species BA total : 25564.67
Difference                    : 442.33
Percentage represented        : 98.30%

In [56]:
# =============================================================================
# 07A.6.24 — Formalize Table 4.5 BA-Percentage Denominator Diagnosis
# =============================================================================

TABLE_45_SOURCE_BA_TOTAL = 26007.0

table_45_mask = (
    structure_validation["Source_Table"] == "4.5"
)

table_45 = (
    structure_validation.loc[
        table_45_mask
    ]
    .copy()
)


table_45_reconstructed_total = (
    table_45["Basal_Area_Num"].sum()
)

table_45_missing_ba = (
    TABLE_45_SOURCE_BA_TOTAL
    - table_45_reconstructed_total
)

table_45_ba_coverage = (
    table_45_reconstructed_total
    / TABLE_45_SOURCE_BA_TOTAL
    * 100
)


# -----------------------------------------------------------------------------
# Reconstruct percentages using the source-reported denominator
# -----------------------------------------------------------------------------

table_45["BA_Percent_From_Source_Total"] = (
    table_45["Basal_Area_Num"]
    / TABLE_45_SOURCE_BA_TOTAL
    * 100
)


table_45["BA_Percent_Source_Total_Error"] = (
    table_45["BA_Percent_Num"]
    - table_45["BA_Percent_From_Source_Total"]
).abs()


print("Table 4.5 BA-percentage denominator diagnosis")
print("=" * 80)

print(
    f"Source-reported BA total       : "
    f"{TABLE_45_SOURCE_BA_TOTAL:.2f}"
)

print(
    f"Reconstructed species BA total : "
    f"{table_45_reconstructed_total:.2f}"
)

print(
    f"Unaccounted BA                 : "
    f"{table_45_missing_ba:.2f}"
)

print(
    f"Reconstructed BA coverage      : "
    f"{table_45_ba_coverage:.2f}%"
)

print(
    f"Reported BA % total            : "
    f"{table_45['BA_Percent_Num'].sum():.2f}%"
)


print("\nBA-% error using source-reported denominator")
print("-" * 80)

display(
    table_45[
        "BA_Percent_Source_Total_Error"
    ]
    .describe()
    .to_frame("Absolute_Percentage_Point_Error")
)


print("\nLargest discrepancies")
print("-" * 80)

display(
    table_45[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Basal_Area_Num",
            "BA_Percent_Num",
            "BA_Percent_From_Source_Total",
            "BA_Percent_Source_Total_Error",
        ]
    ]
    .sort_values(
        "BA_Percent_Source_Total_Error",
        ascending=False,
    )
    .head(10)
)

Table 4.5 BA-percentage denominator diagnosis
================================================================================
Source-reported BA total       : 26007.00
Reconstructed species BA total : 25564.67
Unaccounted BA                 : 442.33
Reconstructed BA coverage      : 98.30%
Reported BA % total            : 98.18%

BA-% error using source-reported denominator
--------------------------------------------------------------------------------

       Absolute_Percentage_Point_Error
count                        33.000000
mean                          0.003811
std                           0.002952
min                           0.000084
25%                           0.001510
50%                           0.003070
75%                           0.006223
max                           0.009878

Largest discrepancies
--------------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Basal_Area_Num,BA_Percent_Num,BA_Percent_From_Source_Total,BA_Percent_Source_Total_Error
112,OMO_STR_0113,Funtumia africana,860.8,3.30,3.309878,0.009878
111,OMO_STR_0112,Drypetes,735.7,2.82,2.828854,0.008854
104,OMO_STR_0105,Brachystegia eurycoma,387.2,1.48,1.488830,0.008830
127,OMO_STR_0128,Rothmania hispida,1521.0,5.84,5.848425,0.008425
113,OMO_STR_0114,Funtumia elastica,475.4,1.82,1.827969,0.007969
122,OMO_STR_0123,Nauclea diderrichi,633.7,2.43,2.436652,0.006652
116,OMO_STR_0117,Hexalobus crispiflorus,633.7,2.43,2.436652,0.006652
118,OMO_STR_0119,Macaranga barteri,1263.0,4.85,4.856385,0.006385
121,OMO_STR_0122,Musanga cecropoides,1419.0,5.45,5.456223,0.006223
120,OMO_STR_0121,Micranga barteri,651.7,2.50,2.505864,0.005864

In [57]:
# =============================================================================
# 07A.6.25 — Diagnose Table 4.9 BA-Percentage Anomaly
# =============================================================================

table_49 = (
    structure_validation.loc[
        structure_validation["Source_Table"] == "4.9"
    ]
    .copy()
)


# -----------------------------------------------------------------------------
# Calculate totals with and without the extreme percentage value
# -----------------------------------------------------------------------------

table_49_percent_total = (
    table_49["BA_Percent_Num"].sum()
)


table_49_without_extreme = (
    table_49.loc[
        table_49["BA_Percent_Num"] < 100
    ]
    .copy()
)


table_49_percent_without_extreme = (
    table_49_without_extreme[
        "BA_Percent_Num"
    ].sum()
)


print("Table 4.9 BA-percentage diagnosis")
print("=" * 80)

print(
    f"Records                 : "
    f"{len(table_49)}"
)

print(
    f"Reported BA total       : "
    f"{table_49['Basal_Area_Num'].sum():.2f}"
)

print(
    f"Reported BA % total     : "
    f"{table_49_percent_total:.2f}%"
)

print(
    f"BA % excluding >=100%   : "
    f"{table_49_percent_without_extreme:.2f}%"
)


print("\nComplete Table 4.9")
print("-" * 80)

display(
    table_49[
        [
            "Raw_Record_ID",
            "Source_Species",
            "Basal_Area_Num",
            "BA_Percent_Num",
            "BA_Percent_Reconstructed",
            "BA_Percent_Absolute_Error",
        ]
    ]
    .sort_values(
        "BA_Percent_Num",
        ascending=False,
    )
)


# -----------------------------------------------------------------------------
# Identify impossible/extreme percentage values
# -----------------------------------------------------------------------------

table_49_extreme = (
    table_49.loc[
        table_49["BA_Percent_Num"] >= 100,
        [
            "Raw_Record_ID",
            "Source_Species",
            "Basal_Area_Num",
            "BA_Percent_Num",
            "BA_Percent_Reconstructed",
            "BA_Percent_Absolute_Error",
        ],
    ]
    .copy()
)


print("\nRecords with reported BA % >= 100")
print("-" * 80)

display(table_49_extreme)

Table 4.9 BA-percentage diagnosis
================================================================================
Records                 : 18
Reported BA total       : 8040.30
Reported BA % total     : 204.16%
BA % excluding >=100%   : 88.16%

Complete Table 4.9
--------------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Basal_Area_Num,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error
213,OMO_STR_0214,Elaeis guineensis,946.0,116.00,11.765730,104.234270
215,OMO_STR_0216,Ficus mucosa,1833.0,22.79,22.797657,0.007657
214,OMO_STR_0215,Ficus exasperata,607.2,7.55,7.551957,0.001957
216,OMO_STR_0217,Musa sapiensis,598.5,7.44,7.443752,0.003752
206,OMO_STR_0207,Bombax buonopozene,585.5,7.28,7.282067,0.002067
218,OMO_STR_0219,Ricinodendron heudeloti,539.3,6.70,6.707461,0.007461
210,OMO_STR_0211,Citrus sinenses,471.6,5.86,5.865453,0.005453
204,OMO_STR_0205,Artocarpus communis,380.2,4.72,4.728679,0.008679
220,OMO_STR_0221,Trema orientalis,363.2,4.51,4.517244,0.007244
212,OMO_STR_0213,Dracena manni,283.6,3.52,3.527232,0.007232
219,OMO_STR_0220,Theobroma cacao,263.1,3.27,3.272266,0.002266
221,OMO_STR_0222,Uapaca heudeloti,227.0,2.82,2.823278,0.003278
211,OMO_STR_0212,Cola nitida,224.4,2.79,2.790941,0.000941
208,OMO_STR_0209,Ceiba pentandra,206.2,2.56,2.564581,0.004581
207,OMO_STR_0208,Carica papaya,169.7,2.11,2.110618,0.000618
205,OMO_STR_0206,Bambusa vulgaris,124.7,1.55,1.550937,0.000937
209,OMO_STR_0210,Chrysophyllum albidum,115.0,1.43,1.430295,0.000295
217,OMO_STR_0218,Raulvolfia vomitoria,102.1,1.26,1.269853,0.009853

Records with reported BA % >= 100
--------------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Basal_Area_Num,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error
213,OMO_STR_0214,Elaeis guineensis,946.0,116.0,11.76573,104.23427

### 07A.6.26 — Final Basal-Area Percentage QC Classification

Basal-area percentage validation identified two distinct source issues.

For Table 4.5 (Buffer × Stream), the 33 reconstructed species records sum to
25,564.67 BA units, whereas the historical table reports a total of 26,007.
The individual reported percentages are nevertheless highly consistent with
the source-reported denominator of 26,007. This is therefore treated as a
table-level completeness or denominator discrepancy rather than as 33
individual percentage errors.

For Table 4.9 (Transition × Upland), one record (`Elaeis guineensis`) reports
BA = 946.0 and BA% = 116.00. The reported BA and the table denominator imply
approximately 11.77%. Because the historical value must be preserved, 116.00
is retained unchanged and the record is flagged as `BA_INCONSISTENT`.

No historical numerical value is corrected in Notebook 07A.

In [58]:
# =============================================================================
# 07A.6.26 — Final BA-Percentage QC Classification
# =============================================================================

# Start with no record-level BA-percentage inconsistency.
structure_validation["BA_Percent_QC"] = "OK"


# -----------------------------------------------------------------------------
# 1. Table 4.9 individual anomaly
# -----------------------------------------------------------------------------

ba_percent_anomaly_mask = (
    structure_validation["Raw_Record_ID"]
    == "OMO_STR_0214"
)

assert ba_percent_anomaly_mask.sum() == 1, (
    "Expected exactly one OMO_STR_0214 record."
)


structure_validation.loc[
    ba_percent_anomaly_mask,
    "BA_Percent_QC"
] = "BA_INCONSISTENT"


# -----------------------------------------------------------------------------
# 2. Verify the anomalous record
# -----------------------------------------------------------------------------

ba_anomaly_record = (
    structure_validation.loc[
        ba_percent_anomaly_mask,
        [
            "Raw_Record_ID",
            "Source_Species",
            "Source_Table",
            "Management_Zone",
            "Habitat",
            "Basal_Area_Num",
            "BA_Percent_Num",
            "BA_Percent_Reconstructed",
            "BA_Percent_Absolute_Error",
            "BA_Percent_QC",
        ],
    ]
    .copy()
)


print("Final BA-percentage QC classification")
print("=" * 80)

print("\nRecord-level BA-percentage anomaly")
print("-" * 80)

display(ba_anomaly_record)


# -----------------------------------------------------------------------------
# 3. Table-level issue for Table 4.5
# -----------------------------------------------------------------------------

print("\nTable-level source completeness issue")
print("-" * 80)

print("Source table                    : 4.5")
print("Management zone                 : Buffer")
print("Habitat                         : Stream")
print(f"Source-reported BA total        : {TABLE_45_SOURCE_BA_TOTAL:.2f}")
print(f"Reconstructed species BA total  : {table_45_reconstructed_total:.2f}")
print(f"Unaccounted BA                  : {table_45_missing_ba:.2f}")
print(f"Reconstructed BA coverage       : {table_45_ba_coverage:.2f}%")

print(
    "Interpretation                   : "
    "TABLE_LEVEL_COMPLETENESS_DISCREPANCY"
)


# -----------------------------------------------------------------------------
# 4. Record-level summary
# -----------------------------------------------------------------------------

ba_qc_summary = (
    structure_validation["BA_Percent_QC"]
    .value_counts()
    .rename_axis("BA_Percent_QC")
    .reset_index(name="Records")
)


print("\nRecord-level BA-percentage QC")
print("-" * 80)

display(ba_qc_summary)


# -----------------------------------------------------------------------------
# 5. Validation
# -----------------------------------------------------------------------------

assert (
    structure_validation["BA_Percent_QC"]
    .eq("BA_INCONSISTENT")
    .sum()
    == 1
), (
    "Expected exactly one record-level BA-percentage inconsistency."
)


assert (
    structure_validation.loc[
        ba_percent_anomaly_mask,
        "Source_Table"
    ].iloc[0]
    == "4.9"
), (
    "The expected BA-percentage anomaly is not in Table 4.9."
)


assert (
    structure_validation.loc[
        ba_percent_anomaly_mask,
        "BA_Percent_Num"
    ].iloc[0]
    == 116.0
), (
    "Unexpected historical BA-percent value for OMO_STR_0214."
)


print("\nFinal BA-percentage QC classification: PASSED")

Final BA-percentage QC classification
================================================================================

Record-level BA-percentage anomaly
--------------------------------------------------------------------------------

,Raw_Record_ID,Source_Species,Source_Table,Management_Zone,Habitat,Basal_Area_Num,BA_Percent_Num,BA_Percent_Reconstructed,BA_Percent_Absolute_Error,BA_Percent_QC
213,OMO_STR_0214,Elaeis guineensis,4.9,Transition,Upland,946.0,116.0,11.76573,104.23427,BA_INCONSISTENT

Table-level source completeness issue
--------------------------------------------------------------------------------
Source table                    : 4.5
Management zone                 : Buffer
Habitat                         : Stream
Source-reported BA total        : 26007.00
Reconstructed species BA total  : 25564.67
Unaccounted BA                  : 442.33
Reconstructed BA coverage       : 98.30%
Interpretation                   : TABLE_LEVEL_COMPLETENESS_DISCREPANCY

Record-level BA-percentage QC
--------------------------------------------------------------------------------

     BA_Percent_QC  Records
0               OK      221
1  BA_INCONSISTENT        1

Final BA-percentage QC classification: PASSED

## 07A.7 — Structural Internal-Consistency Product

This section consolidates the validated structural diagnostics into a reusable
processed dataset.

The product preserves one row per historical structural record and contains
derived fields describing:

- inferred individual counts from DBH and height;
- total/mean consistency;
- basal-area formula agreement;
- basal-area percentage consistency;
- statistical DBH and height screening; and
- measurement interpretation fields required for downstream QC.

No historical source value is altered.

Output:

`structure_internal_consistency.csv`

In [59]:
# =============================================================================
# 07A.7.1 — Build Structural Internal-Consistency Dataset
# =============================================================================

consistency_columns = [
    "Raw_Record_ID",
    "Source_Species",
    "Canonical_Species",
    "Management_Zone",
    "Habitat",
    "Source_Table",
    "Source_Page",
    "Source_Row",

    # Inferred counts
    "Inferred_N_DBH",
    "Rounded_N_DBH",
    "DBH_N_Integer_Error",
    "DBH_Count_Consistent",

    "Inferred_N_Height",
    "Rounded_N_Height",
    "Height_N_Integer_Error",
    "Height_Count_Consistent",

    "DBH_Height_Count_Agree",
    "Total_Mean_Consistent",
    "Count_Consistency_Class",

    # Basal-area validation
    "BA_From_Mean_DBH",
    "BA_Absolute_Error",
    "BA_Relative_Error",
    "BA_Percent_Error",
    "BA_Reported_Predicted_Ratio",
    "BA_Formula_Consistent",
    "BA_Strictly_Consistent",

    # BA percentage validation
    "BA_Table_Total",
    "BA_Percent_Reconstructed",
    "BA_Percent_Absolute_Error",
    "BA_Percent_Consistent",
    "BA_Implied_Denominator",
    "BA_Percent_QC",

    # Statistical screening
    "DBH_IQR_Outlier",
    "Height_IQR_Outlier",

    # Current QC flags
    "QC_Flag",
]


structure_internal_consistency = (
    structure_validation[
        consistency_columns
    ]
    .copy()
)


print("Structural internal-consistency dataset")
print("=" * 72)

print(
    f"Records : "
    f"{len(structure_internal_consistency)}"
)

print(
    f"Columns : "
    f"{structure_internal_consistency.shape[1]}"
)


display(
    structure_internal_consistency.head(10)
)

Structural internal-consistency dataset
========================================================================
Records : 222
Columns : 35

,Raw_Record_ID,Source_Species,Canonical_Species,Management_Zone,Habitat,Source_Table,Source_Page,Source_Row,Inferred_N_DBH,Rounded_N_DBH,...,BA_Strictly_Consistent,BA_Table_Total,BA_Percent_Reconstructed,BA_Percent_Absolute_Error,BA_Percent_Consistent,BA_Implied_Denominator,BA_Percent_QC,DBH_IQR_Outlier,Height_IQR_Outlier,QC_Flag
0,OMO_STR_0001,Alstonia boonei,Alstonia boonei,Core,Stream,4.1,1,2,5.000000,5.0,...,True,39180.72,2.648241,0.008241,True,39303.030303,OK,False,False,NAME_HARMONIZED
1,OMO_STR_0002,Blighia sapida,Blighia sapida,Core,Stream,4.1,1,3,7.000000,7.0,...,True,39180.72,2.237095,0.007095,True,39305.381166,OK,False,False,
2,OMO_STR_0003,Bombax buonopozene,Bombax buonopozense,Core,Stream,4.1,1,4,4.003175,4.0,...,True,39180.72,1.989831,0.009831,True,39375.252525,OK,False,False,NAME_HARMONIZED
3,OMO_STR_0004,Bosquei angolensis,Bosqueia angolensis,Core,Stream,4.1,1,5,3.003484,3.0,...,True,39180.72,1.651807,0.001807,True,39223.636364,OK,False,False,NAME_HARMONIZED;TOTAL_MEAN_INCONSISTENT
4,OMO_STR_0005,Celtis zenkeri,Celtis zenkeri,Core,Stream,4.1,1,6,8.020408,8.0,...,True,39180.72,1.733353,0.003353,True,39256.647399,OK,False,False,TOTAL_MEAN_INCONSISTENT
5,OMO_STR_0006,Cleistopholis Patens,Cleistopholis patens,Core,Stream,4.1,1,7,8.016129,8.0,...,True,39180.72,1.927147,0.007147,True,39326.562500,OK,False,False,NAME_HARMONIZED;TOTAL_MEAN_INCONSISTENT
6,OMO_STR_0007,Dialium guinensis,Dialium guinensis,Core,Stream,4.1,1,8,2.000000,2.0,...,True,39180.72,2.197101,0.007101,True,39307.762557,OK,False,False,
7,OMO_STR_0008,Diospyros dendo,Diospyros dendo,Core,Stream,4.1,1,9,30.381395,30.0,...,True,39180.72,0.926987,0.006987,True,39478.260870,OK,False,False,TOTAL_MEAN_INCONSISTENT
8,OMO_STR_0009,Drypetes,Drypetes,Core,Stream,4.1,1,10,27.099602,27.0,...,True,39180.72,1.263402,0.003402,True,39286.507937,OK,False,False,
9,OMO_STR_0010,Ficus exasperata,Ficus exasperata,Core,Stream,4.1,1,11,4.000000,4.0,...,True,39180.72,6.378903,0.008903,True,39235.478807,OK,True,True,

In [60]:
# =============================================================================
# 07A.7.2 — Validate Internal-Consistency Product
# =============================================================================

assert len(structure_internal_consistency) == 222, (
    "Expected exactly 222 internal-consistency records."
)

assert structure_internal_consistency[
    "Raw_Record_ID"
].is_unique, (
    "Raw_Record_ID values are not unique."
)

assert structure_internal_consistency[
    "Raw_Record_ID"
].notna().all(), (
    "Missing Raw_Record_ID values detected."
)


# -----------------------------------------------------------------------------
# Locked validation counts
# -----------------------------------------------------------------------------

assert (
    structure_internal_consistency[
        "Total_Mean_Consistent"
    ].sum()
    == 196
), (
    "Unexpected total/mean consistency count."
)

assert (
    structure_internal_consistency[
        "BA_Strictly_Consistent"
    ].sum()
    == 222
), (
    "Expected all 222 records to pass strict basal-area validation."
)

assert (
    structure_internal_consistency[
        "BA_Percent_QC"
    ].eq("BA_INCONSISTENT").sum()
    == 1
), (
    "Expected exactly one BA-percentage inconsistency."
)

assert (
    structure_internal_consistency[
        "DBH_IQR_Outlier"
    ].sum()
    == 13
), (
    "Expected exactly 13 DBH IQR screening outliers."
)

assert (
    structure_internal_consistency[
        "Height_IQR_Outlier"
    ].sum()
    == 14
), (
    "Expected exactly 14 height IQR screening outliers."
)


print("Internal-consistency validation")
print("=" * 72)

print(
    "Total/mean consistent       : "
    f"{structure_internal_consistency['Total_Mean_Consistent'].sum()} / 222"
)

print(
    "Strict BA consistent        : "
    f"{structure_internal_consistency['BA_Strictly_Consistent'].sum()} / 222"
)

print(
    "BA % inconsistent           : "
    f"{structure_internal_consistency['BA_Percent_QC'].eq('BA_INCONSISTENT').sum()}"
)

print(
    "DBH IQR screening outliers  : "
    f"{structure_internal_consistency['DBH_IQR_Outlier'].sum()}"
)

print(
    "Height IQR screening outliers: "
    f"{structure_internal_consistency['Height_IQR_Outlier'].sum()}"
)


print("\nStructural internal-consistency product: PASSED")

Internal-consistency validation
========================================================================
Total/mean consistent       : 196 / 222
Strict BA consistent        : 222 / 222
BA % inconsistent           : 1
DBH IQR screening outliers  : 13
Height IQR screening outliers: 14

Structural internal-consistency product: PASSED

In [61]:
# =============================================================================
# 07A.7.3 — Export Structural Internal-Consistency Dataset
# =============================================================================

structure_internal_consistency.to_csv(
    STRUCTURE_CONSISTENCY_FILE,
    index=False,
    encoding="utf-8",
)


assert STRUCTURE_CONSISTENCY_FILE.exists(), (
    "structure_internal_consistency.csv was not created."
)


print("Structural internal-consistency dataset exported successfully.")
print("=" * 72)

print(
    f"Output file : "
    f"{STRUCTURE_CONSISTENCY_FILE}"
)

print(
    f"Records     : "
    f"{len(structure_internal_consistency)}"
)

Structural internal-consistency dataset exported successfully.
========================================================================
Output file : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\notebook_07a\structure_internal_consistency.csv
Records     : 222

## 07A.8 — Final Structural QC Report

This section consolidates the validated quality-control findings from Notebook 07A
into a single reusable QC report.

The report distinguishes between:

- record-level issues affecting individual structural records; and
- table-level issues affecting the interpretation or completeness of an entire
  historical source table.

No historical source value is modified.

Output:

`structure_qc_report.csv`

In [62]:
# =============================================================================
# 07A.8.1 — Build Record-Level Structural QC Report
# =============================================================================

record_qc_entries = []


for _, row in structure_validation.iterrows():

    raw_record_id = row["Raw_Record_ID"]

    # -------------------------------------------------------------------------
    # Existing propagated QC flags
    # -------------------------------------------------------------------------

    existing_flags = []

    if pd.notna(row["QC_Flag"]) and str(row["QC_Flag"]).strip():

        existing_flags = [
            flag.strip()
            for flag in str(row["QC_Flag"]).split(";")
            if flag.strip()
        ]


    for flag in existing_flags:

        record_qc_entries.append(
            {
                "QC_Level": "RECORD",
                "Raw_Record_ID": raw_record_id,
                "Source_Table": row["Source_Table"],
                "Source_Species": row["Source_Species"],
                "Canonical_Species": row["Canonical_Species"],
                "Management_Zone": row["Management_Zone"],
                "Habitat": row["Habitat"],
                "QC_Flag": flag,
                "QC_Status": "FLAGGED",
                "QC_Detail": pd.NA,
            }
        )


    # -------------------------------------------------------------------------
    # BA-percentage inconsistency
    # -------------------------------------------------------------------------

    if row["BA_Percent_QC"] == "BA_INCONSISTENT":

        record_qc_entries.append(
            {
                "QC_Level": "RECORD",
                "Raw_Record_ID": raw_record_id,
                "Source_Table": row["Source_Table"],
                "Source_Species": row["Source_Species"],
                "Canonical_Species": row["Canonical_Species"],
                "Management_Zone": row["Management_Zone"],
                "Habitat": row["Habitat"],
                "QC_Flag": "BA_INCONSISTENT",
                "QC_Status": "FLAGGED",
                "QC_Detail": (
                    "Reported BA percentage is inconsistent with "
                    "the table denominator. Historical source value "
                    "retained unchanged."
                ),
            }
        )


record_qc_report = pd.DataFrame(record_qc_entries)


print("Record-level structural QC entries")
print("=" * 72)

print(
    f"QC entries created : "
    f"{len(record_qc_report)}"
)

display(
    record_qc_report.head(20)
)

Record-level structural QC entries
========================================================================
QC entries created : 65

,QC_Level,Raw_Record_ID,Source_Table,Source_Species,Canonical_Species,Management_Zone,Habitat,QC_Flag,QC_Status,QC_Detail
0,RECORD,OMO_STR_0001,4.1,Alstonia boonei,Alstonia boonei,Core,Stream,NAME_HARMONIZED,FLAGGED,<NA>
1,RECORD,OMO_STR_0003,4.1,Bombax buonopozene,Bombax buonopozense,Core,Stream,NAME_HARMONIZED,FLAGGED,<NA>
2,RECORD,OMO_STR_0004,4.1,Bosquei angolensis,Bosqueia angolensis,Core,Stream,NAME_HARMONIZED,FLAGGED,<NA>
3,RECORD,OMO_STR_0004,4.1,Bosquei angolensis,Bosqueia angolensis,Core,Stream,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
4,RECORD,OMO_STR_0005,4.1,Celtis zenkeri,Celtis zenkeri,Core,Stream,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
5,RECORD,OMO_STR_0006,4.1,Cleistopholis Patens,Cleistopholis patens,Core,Stream,NAME_HARMONIZED,FLAGGED,<NA>
6,RECORD,OMO_STR_0006,4.1,Cleistopholis Patens,Cleistopholis patens,Core,Stream,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
7,RECORD,OMO_STR_0008,4.1,Diospyros dendo,Diospyros dendo,Core,Stream,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
8,RECORD,OMO_STR_0012,4.1,Homalium alymeri,Homalium alymeri,Core,Stream,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
9,RECORD,OMO_STR_0017,4.1,Pavetta crassipes,<NA>,Core,Stream,NOT_IN_CANONICAL_127,FLAGGED,<NA>
10,RECORD,OMO_STR_0018,4.1,Picralima nitida,Picralima nitida,Core,Stream,DUPLICATE_SOURCE_RECORD,FLAGGED,<NA>
11,RECORD,OMO_STR_0019,4.1,Picralima nitida,Picralima nitida,Core,Stream,DUPLICATE_SOURCE_RECORD,FLAGGED,<NA>
12,RECORD,OMO_STR_0029,4.2,Blighia Sapida,Blighia sapida,Core,Major River,NAME_HARMONIZED,FLAGGED,<NA>
13,RECORD,OMO_STR_0033,4.2,Drypetes,Drypetes,Core,Major River,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
14,RECORD,OMO_STR_0036,4.2,irvinga gabonensis,Irvinga gabonensis,Core,Major River,NAME_HARMONIZED,FLAGGED,<NA>
15,RECORD,OMO_STR_0036,4.2,irvinga gabonensis,Irvinga gabonensis,Core,Major River,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>
16,RECORD,OMO_STR_0038,4.2,Lonchocarpus ciliata,Lonchocarpus cilliata,Core,Major River,NAME_HARMONIZED,FLAGGED,<NA>
17,RECORD,OMO_STR_0041,4.2,Monodora lenuifolia,Monodora tenuifolia,Core,Major River,NAME_HARMONIZED,FLAGGED,<NA>
18,RECORD,OMO_STR_0048,4.2,Strombosia pustulata,Strombosia pustulata,Core,Major River,NAME_HARMONIZED,FLAGGED,<NA>
19,RECORD,OMO_STR_0056,4.3,Diospyrous dendo,Diospyrous dendo,Core,Upland,TOTAL_MEAN_INCONSISTENT,FLAGGED,<NA>

In [63]:
# =============================================================================
# 07A.8.2 — Build Table-Level Structural QC Report
# =============================================================================

table_qc_entries = []


# -----------------------------------------------------------------------------
# Table 4.5 completeness / denominator discrepancy
# -----------------------------------------------------------------------------

table_qc_entries.append(
    {
        "QC_Level": "TABLE",
        "Raw_Record_ID": pd.NA,
        "Source_Table": "4.5",
        "Source_Species": pd.NA,
        "Canonical_Species": pd.NA,
        "Management_Zone": "Buffer",
        "Habitat": "Stream",
        "QC_Flag": "TABLE_LEVEL_COMPLETENESS_DISCREPANCY",
        "QC_Status": "FLAGGED",
        "QC_Detail": (
            "Source-reported BA total = 26007.00, while reconstructed "
            "species-level BA sums to 25564.67. Difference = 442.33. "
            "Individual BA percentages are internally consistent with "
            "the source-reported denominator, indicating a table-level "
            "completeness or denominator discrepancy rather than "
            "record-level percentage errors."
        ),
    }
)


# -----------------------------------------------------------------------------
# Dataset-level DBH unit uncertainty
# -----------------------------------------------------------------------------

table_qc_entries.append(
    {
        "QC_Level": "DATASET",
        "Raw_Record_ID": pd.NA,
        "Source_Table": pd.NA,
        "Source_Species": pd.NA,
        "Canonical_Species": pd.NA,
        "Management_Zone": pd.NA,
        "Habitat": pd.NA,
        "QC_Flag": "UNIT_UNCERTAIN",
        "QC_Status": "DOCUMENTED",
        "QC_Detail": (
            "The variable labelled dbh behaves mathematically as diameter. "
            "Magnitude and basal-area relationships strongly suggest centimetres, "
            "but the historical source does not independently document the unit."
        ),
    }
)


# -----------------------------------------------------------------------------
# Dataset-level height unit uncertainty
# -----------------------------------------------------------------------------

table_qc_entries.append(
    {
        "QC_Level": "DATASET",
        "Raw_Record_ID": pd.NA,
        "Source_Table": pd.NA,
        "Source_Species": pd.NA,
        "Canonical_Species": pd.NA,
        "Management_Zone": pd.NA,
        "Habitat": pd.NA,
        "QC_Flag": "HEIGHT_UNIT_UNCERTAIN",
        "QC_Status": "DOCUMENTED",
        "QC_Detail": (
            "Reported height magnitudes are biologically plausible as metres "
            "and internally coherent, but the historical source does not "
            "independently document the unit."
        ),
    }
)


# -----------------------------------------------------------------------------
# Dataset-level basal-area unit interpretation
# -----------------------------------------------------------------------------

table_qc_entries.append(
    {
        "QC_Level": "DATASET",
        "Raw_Record_ID": pd.NA,
        "Source_Table": pd.NA,
        "Source_Species": pd.NA,
        "Canonical_Species": pd.NA,
        "Management_Zone": pd.NA,
        "Habitat": pd.NA,
        "QC_Flag": "BA_UNIT_LABEL_INCONSISTENT",
        "QC_Status": "DOCUMENTED",
        "QC_Detail": (
            "All 222 reported basal-area values reproduce pi*d^2/4 from Mean_DBH. "
            "Therefore BA is expressed in squared DBH units. If DBH is centimetres, "
            "the numerical BA values are cm2 rather than m2, despite the source "
            "heading 'BA m2'."
        ),
    }
)


table_qc_report = pd.DataFrame(table_qc_entries)


print("Table/dataset-level structural QC entries")
print("=" * 72)

display(table_qc_report)

Table/dataset-level structural QC entries
========================================================================

,QC_Level,Raw_Record_ID,Source_Table,Source_Species,Canonical_Species,Management_Zone,Habitat,QC_Flag,QC_Status,QC_Detail
0,TABLE,<NA>,4.5,<NA>,<NA>,Buffer,Stream,TABLE_LEVEL_COMPLETENESS_DISCREPANCY,FLAGGED,"Source-reported BA total = 26007.00, while rec..."
1,DATASET,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,UNIT_UNCERTAIN,DOCUMENTED,The variable labelled dbh behaves mathematical...
2,DATASET,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,HEIGHT_UNIT_UNCERTAIN,DOCUMENTED,Reported height magnitudes are biologically pl...
3,DATASET,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,BA_UNIT_LABEL_INCONSISTENT,DOCUMENTED,All 222 reported basal-area values reproduce p...

In [64]:
# =============================================================================
# 07A.8.3 — Combine and Validate Structural QC Report
# =============================================================================

structure_qc_report = pd.concat(
    [
        record_qc_report,
        table_qc_report,
    ],
    ignore_index=True,
)


print("Combined structural QC report")
print("=" * 72)

print(
    f"Total QC entries : "
    f"{len(structure_qc_report)}"
)


print("\nQC flag summary")
print("-" * 72)

display(
    structure_qc_report["QC_Flag"]
    .value_counts()
    .rename_axis("QC_Flag")
    .reset_index(name="Entries")
)


# -----------------------------------------------------------------------------
# Locked checks
# -----------------------------------------------------------------------------

assert (
    structure_qc_report["QC_Flag"]
    .eq("TOTAL_MEAN_INCONSISTENT")
    .sum()
    == 26
), (
    "Expected 26 TOTAL_MEAN_INCONSISTENT record-level entries."
)

assert (
    structure_qc_report["QC_Flag"]
    .eq("BA_INCONSISTENT")
    .sum()
    == 1
), (
    "Expected exactly one BA_INCONSISTENT entry."
)

assert (
    structure_qc_report["QC_Flag"]
    .eq("TABLE_LEVEL_COMPLETENESS_DISCREPANCY")
    .sum()
    == 1
), (
    "Expected exactly one table-level completeness discrepancy."
)

assert (
    structure_qc_report["QC_Flag"]
    .eq("UNIT_UNCERTAIN")
    .sum()
    == 1
), (
    "Expected one dataset-level DBH unit uncertainty entry."
)


print("\nStructural QC report validation: PASSED")

Combined structural QC report
========================================================================
Total QC entries : 69

QC flag summary
------------------------------------------------------------------------

                                QC_Flag  Entries
0                       NAME_HARMONIZED       31
1               TOTAL_MEAN_INCONSISTENT       26
2                       AMBIGUOUS_TAXON        3
3                  NOT_IN_CANONICAL_127        2
4               DUPLICATE_SOURCE_RECORD        2
5                       BA_INCONSISTENT        1
6  TABLE_LEVEL_COMPLETENESS_DISCREPANCY        1
7                        UNIT_UNCERTAIN        1
8                 HEIGHT_UNIT_UNCERTAIN        1
9            BA_UNIT_LABEL_INCONSISTENT        1

Structural QC report validation: PASSED

In [65]:
# =============================================================================
# 07A.8.4 — Export Structural QC Report
# =============================================================================

structure_qc_report.to_csv(
    STRUCTURE_QC_REPORT_FILE,
    index=False,
    encoding="utf-8",
)


assert STRUCTURE_QC_REPORT_FILE.exists(), (
    "structure_qc_report.csv was not created."
)


print("Structural QC report exported successfully.")
print("=" * 72)

print(
    f"Output file : "
    f"{STRUCTURE_QC_REPORT_FILE}"
)

print(
    f"QC entries  : "
    f"{len(structure_qc_report)}"
)

Structural QC report exported successfully.
========================================================================
Output file : C:\Peter\SDM_data\omo_ecodb\omo-ecological-informatics\data\processed\notebook_07a\structure_qc_report.csv
QC entries  : 69

## 07A.9 — Final Validation Summary and Handover to Notebook 07B

This section performs the final Notebook 07A validation and records the
validated structural-data state for downstream functional-ecology work.

Notebook 07A is considered complete only if:

- all required processed outputs exist;
- the historical reconstruction contains 222 structural records;
- the taxonomic matching audit contains 137 source taxa;
- the harmonized structural dataset preserves all 222 raw records;
- the internal-consistency product contains 222 validated records;
- the QC report contains the documented record-, table-, and dataset-level issues;
- no historical source value has been silently corrected; and
- the notebook runs successfully from a restarted kernel.

The resulting handover establishes the structural-data foundation for
Notebook 07B — Functional Trait Acquisition and Harmonization.

In [66]:
# =============================================================================
# 07A.9.1 — Final Notebook 07A Validation
# =============================================================================

print("NOTEBOOK 07A — FINAL VALIDATION")
print("=" * 80)


# -----------------------------------------------------------------------------
# 1. Required output files
# -----------------------------------------------------------------------------

required_outputs = {
    "Raw structural reconstruction":
        STRUCTURE_RAW_FILE,

    "Harmonized structural dataset":
        STRUCTURE_HARMONIZED_FILE,

    "Taxonomic matching audit":
        STRUCTURE_TAXONOMIC_MATCHING_FILE,

    "Structural QC report":
        STRUCTURE_QC_REPORT_FILE,

    "Internal consistency":
        STRUCTURE_CONSISTENCY_FILE,
}


print("\nRequired processed outputs")
print("-" * 80)

for label, path in required_outputs.items():

    status = "FOUND" if path.exists() else "MISSING"

    print(f"{label:<35}: {status}")

    assert path.exists(), (
        f"Required Notebook 07A output missing: {path}"
    )


# -----------------------------------------------------------------------------
# 2. Locked dataset dimensions
# -----------------------------------------------------------------------------

assert len(structure_raw) == 222, (
    "Raw structural reconstruction must contain 222 records."
)

assert len(structure_harmonized) == 222, (
    "Harmonized structural dataset must contain 222 records."
)

assert len(structure_taxonomic_matching) == 137, (
    "Taxonomic matching audit must contain 137 source taxa."
)

assert len(structure_internal_consistency) == 222, (
    "Internal-consistency product must contain 222 records."
)


print("\nValidated dataset dimensions")
print("-" * 80)

print(f"Raw structural records          : {len(structure_raw)}")
print(f"Harmonized structural records   : {len(structure_harmonized)}")
print(f"Unique structural source taxa   : {len(structure_taxonomic_matching)}")
print(f"Internal-consistency records    : {len(structure_internal_consistency)}")


# -----------------------------------------------------------------------------
# 3. Taxonomic reconciliation status
# -----------------------------------------------------------------------------

taxonomic_status = (
    structure_taxonomic_matching["Match_Status"]
    .value_counts()
)


print("\nTaxonomic reconciliation")
print("-" * 80)

for status, count in taxonomic_status.items():
    print(f"{status:<30}: {count}")


assert taxonomic_status.get(
    "EXACT_CANONICAL_MATCH",
    0,
) == 105

assert taxonomic_status.get(
    "NORMALIZED_CANONICAL_MATCH",
    0,
) == 8

assert taxonomic_status.get(
    "HARMONIZED_MATCH",
    0,
) == 19

assert taxonomic_status.get(
    "AMBIGUOUS",
    0,
) == 3

assert taxonomic_status.get(
    "NOT_IN_CANONICAL_127",
    0,
) == 2


# -----------------------------------------------------------------------------
# 4. Structural consistency status
# -----------------------------------------------------------------------------

n_total_mean_consistent = int(
    structure_internal_consistency[
        "Total_Mean_Consistent"
    ].sum()
)

n_total_mean_inconsistent = (
    len(structure_internal_consistency)
    - n_total_mean_consistent
)


print("\nStructural internal consistency")
print("-" * 80)

print(
    f"Total/mean consistent          : "
    f"{n_total_mean_consistent}"
)

print(
    f"Total/mean inconsistent        : "
    f"{n_total_mean_inconsistent}"
)

print(
    f"Strict BA-formula consistent   : "
    f"{structure_internal_consistency['BA_Strictly_Consistent'].sum()}"
)

print(
    f"BA-percent inconsistencies     : "
    f"{structure_internal_consistency['BA_Percent_QC'].eq('BA_INCONSISTENT').sum()}"
)


assert n_total_mean_consistent == 196

assert n_total_mean_inconsistent == 26

assert (
    structure_internal_consistency[
        "BA_Strictly_Consistent"
    ].sum()
    == 222
)

assert (
    structure_internal_consistency[
        "BA_Percent_QC"
    ].eq("BA_INCONSISTENT").sum()
    == 1
)


# -----------------------------------------------------------------------------
# 5. Source preservation validation
# -----------------------------------------------------------------------------

raw_source_fields = [
    "Raw_Record_ID",
    "Source_Species",
    "Source_Family",
    "Management_Zone",
    "Habitat",
    "Total_DBH",
    "Mean_DBH",
    "Total_Height",
    "Mean_Height",
    "Basal_Area",
    "BA_Percent",
    "Source_Table",
    "Source_Page",
    "Source_Row",
]


raw_preservation_check = (
    structure_raw[raw_source_fields]
    .sort_values("Raw_Record_ID")
    .reset_index(drop=True)
)


harmonized_preservation_check = (
    structure_harmonized[raw_source_fields]
    .sort_values("Raw_Record_ID")
    .reset_index(drop=True)
)


assert raw_preservation_check.equals(
    harmonized_preservation_check
), (
    "Historical source values changed between raw and harmonized products."
)


print("\nHistorical source-value preservation : PASSED")


# -----------------------------------------------------------------------------
# 6. Final validation
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("NOTEBOOK 07A FINAL VALIDATION: PASSED")
print("=" * 80)

NOTEBOOK 07A — FINAL VALIDATION
================================================================================

Required processed outputs
--------------------------------------------------------------------------------
Raw structural reconstruction      : FOUND
Harmonized structural dataset      : FOUND
Taxonomic matching audit           : FOUND
Structural QC report               : FOUND
Internal consistency               : FOUND

Validated dataset dimensions
--------------------------------------------------------------------------------
Raw structural records          : 222
Harmonized structural records   : 222
Unique structural source taxa   : 137
Internal-consistency records    : 222

Taxonomic reconciliation
--------------------------------------------------------------------------------
EXACT_CANONICAL_MATCH         : 105
HARMONIZED_MATCH              : 19
NORMALIZED_CANONICAL_MATCH    : 8
AMBIGUOUS                     : 3
NOT_IN_CANONICAL_127          : 2

Structural internal consistency
--------------------------------------------------------------------------------
Total/mean consistent          : 196
Total/mean inconsistent        : 26
Strict BA-formula consistent   : 222
BA-percent inconsistencies     : 1

Historical source-value preservation : PASSED

================================================================================
NOTEBOOK 07A FINAL VALIDATION: PASSED
================================================================================

In [67]:
# =============================================================================
# 07A.9.2 — Notebook 07A Validation Summary
# =============================================================================

validation_summary = pd.DataFrame(
    [
        {
            "Metric": "Structural source tables reconstructed",
            "Value": 9,
        },
        {
            "Metric": "Structural records",
            "Value": 222,
        },
        {
            "Metric": "Unique historical source taxa",
            "Value": 137,
        },
        {
            "Metric": "Canonical mappings assigned",
            "Value": 132,
        },
        {
            "Metric": "Ambiguous taxa",
            "Value": 3,
        },
        {
            "Metric": "Outside canonical 127",
            "Value": 2,
        },
        {
            "Metric": "Total/mean consistent records",
            "Value": 196,
        },
        {
            "Metric": "Total/mean inconsistent records",
            "Value": 26,
        },
        {
            "Metric": "Strict BA-formula consistent records",
            "Value": 222,
        },
        {
            "Metric": "BA-percentage inconsistent records",
            "Value": 1,
        },
        {
            "Metric": "DBH IQR screening outliers",
            "Value": 13,
        },
        {
            "Metric": "Height IQR screening outliers",
            "Value": 14,
        },
    ]
)


print("Notebook 07A validation summary")
print("=" * 80)

display(validation_summary)

Notebook 07A validation summary
================================================================================

                                    Metric  Value
0   Structural source tables reconstructed      9
1                       Structural records    222
2            Unique historical source taxa    137
3              Canonical mappings assigned    132
4                           Ambiguous taxa      3
5                    Outside canonical 127      2
6            Total/mean consistent records    196
7          Total/mean inconsistent records     26
8     Strict BA-formula consistent records    222
9       BA-percentage inconsistent records      1
10              DBH IQR screening outliers     13
11           Height IQR screening outliers     14

## Notebook 07A — Validated Handover to Notebook 07B

Notebook 07A successfully reconstructed, reconciled and validated the historical
Omo structural dataset.

### Validated structural foundation

- 9 Management Zone × Habitat source tables reconstructed
- 222 species-context structural records
- 137 unique historical source taxa
- 132 source taxa mapped to the validated canonical inventory
- 3 taxa retained as ambiguous
- 2 taxa retained outside the canonical 127
- 196 records fully consistent across DBH and height total/mean checks
- 26 records flagged for total/mean inconsistency
- all 222 basal-area values mathematically reproduce the reported Mean DBH
- one record contains a BA-percentage inconsistency
- Table 4.5 contains a documented table-level completeness/denominator discrepancy
- DBH behaves as a diameter-based variable and is likely expressed in centimetres
- reported basal area is derived from Mean DBH using πd²/4 and is therefore in
  squared DBH units
- height values are biologically plausible as metres, although the historical
  source does not independently document the unit
- no DBH or height IQR observation was automatically treated as an error
- no historical source value was silently corrected

### Processed outputs

- `omo_tree_structure_raw.csv`
- `omo_tree_structure_harmonized.csv`
- `structure_taxonomic_matching.csv`
- `structure_internal_consistency.csv`
- `structure_qc_report.csv`

### Analytical boundary for Notebook 07B

Notebook 07B may use the validated canonical taxonomy and structural provenance
established here, but it must not reinterpret realized DBH, observed height or
derived basal area as intrinsic functional traits.

Notebook 07B should focus on acquisition and harmonization of external intrinsic
functional traits such as wood density, SLA, seed mass and maximum potential
height.